### ISSUE TITLE
Incorporating 3rd Party Filters Available in UBlock Origin

### ISSUE THREAD

**Issue by XIncognito10** [uBlockOrigin/uMatrix-issues#1]
### Prerequisites

* [x] Did you perform a cursory search of the issue tracker?
    * Your issue may already be reported.
* Can you reproduce the problem when... 
    * [x] uMatrix is the only extension?
    * [x] uMatrix with default lists/settings?
    * [x] using a new, unmodified browser profile?
* [x] Are you running the latest version?
* [x] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

My current setup is to use uMatrix for fine grained content management for the site and uBlock for general ad blocking. I would like to know if it is possible to incorporate the same 3rd party filters available in uBO so they can be available in uMatrix as well. That way others who have no need for ublock apart from ads can just use umatrix alone and reduce the complexity and risk of the two interfering with each other

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior:

Having all the 3rd party lists shown in ublock origin, being shown in umatrix as well

### Actual behavior:

uMatrix only has rules from the multi purpose section and 2 of malware domain sections in ublock origin

### Your environment

* uMatrix version: 1.3.6
* Browser Name and version: Mozilla Firefox 59.0.2 (64-bit)
* Operating System and version: Ubuntu 17.10

**Comment by uBlock-user** [comment]
> I would like to know if it is possible to incorporate the same 3rd party filters available in uBO so they can be available in uMatrix as well.

No. For such questions and support post over - https://www.reddit.com/r/uMatrix/

**Comment by gorhill** [comment]
uMatrix deals with hosts files. These are not the same as ABP/uBO/Adguard filter lists.

**Comment by Exagone313** [comment]
I added a `* * * allow` rule in uBlock so it just filter content, and I use uMatrix for blocking access to resources. The reason is that you can't control extension priorities, at least in Firefox.
