### ISSUE TITLE
impossible to enable/disable scripts/frames/etc if host list is long enough for a scroll bar

### ISSUE THREAD

**Issue by craig-sanders** [uBlockOrigin/uMatrix-issues#1]
Firefox 55.0.3 on Debian sid
uMatrix 1.01rc1

If the list of 3rd party hosts is long enough to require a scrollbar, it becomes impossible to enable or disable scripts, frames, XHR, etc for any host that can only be seen after scrolling.  As soon as you move the mouse cursor off the scroll bar onto the host matrix, it immediately jumps back to the top of the list.

Same happens if you use the scroll wheel...because the cursor is already in the host matrix area, it's constantly jumping back to the top while you're trying to scroll.

e.g. go to [https://boingboing.net/blog](https://boingboing.net/blog) and try to enable youtube videos on it.  BB typically has frames, videos, etc from many different sites.  I don't want to enable them all, nor do I want to enable youtube videos globally - I carefully choose which sites are allowed to run scripts or show frames from youtube or any other site.

Note: workaround is to manually edit "My rules" and, e.g., add something like:

```
boingboing.net googlevideo.com xhr allow
boingboing.net www.youtube.com frame allow
boingboing.net www.youtube.com script allow
boingboing.net www.youtube.com xhr allow
```

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1324499
