### ISSUE TITLE
Info regarding new browser <-> CDN features...!

### ISSUE THREAD

**Issue by EC-O-DE** [uBlockOrigin/uMatrix-issues#10]
A lot to take into consideration!
https://www.keycdn.com/blog/resource-hints/

**Comment by uBlock-user** [comment]
How about you actually follow the template and make a case about something rather than just posting something randomly ?

**Comment by EC-O-DE** [comment]
Sometime ago there was only prefecth, now it's 4 different browser - server chatters. It's good to keep an eye on as evolution of "prefetch" isn't stopping here.

**Comment by uBlock-user** [comment]
Old news, anyways, there is already a bug  filed in Chromium tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=786038

**Comment by gwarser** [comment]
@EC-O-DE please add more explanation next time, I wanted to flag you as a spamer / hijacked account :)

**Comment by gwarser** [comment]
Even if you want support for more prefetching options, you will need to ask browser devs. This is all that can be done: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network
