### ISSUE TITLE
Enabling blocked media breaks going back in history

### ISSUE THREAD

**Issue by quasicomputational** [uBlockOrigin/uMatrix-issues#100]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Enabling blocked media breaks going back in history

### A specific URL where the issue occurs

https://thumbs.gfycat.com/EvilSmoggyCapeghostfrog-mobile.mp4 (or any .mp4, .webm, etc)

### Steps to Reproduce

0. Block first-party media on thumbs.gfycat.com
1. Navigate to https://thumbs.gfycat.com/EvilSmoggyCapeghostfrog-mobile.mp4 in a tab with some history (i.e., don't just middle-click the link - go somewhere else first and then go there in the same tab)
2. Observe the 'blocked by uMatrix' page, as expected
3. Allow thumbs.gfycat.com to play media
4. Reload the page, observe the amusing video.
5. Click the browser's 'back' button.
6. Note that clicking 'back' keeps you stuck on the video page!

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 64
* Operating System and version: Debian

What's happening here is that the 'blocked by uMatrix' page is lurking in the history, and when we go back to it, it's immediately sending us back to the media. This is helpful when we have just unblocked the media and we're reloading the page, but not so helpful when we want to go back!

I think the optimal solution here is for the 'blocked by uMatrix' page to remove itself from the history immediately prior to navigating to the newly-allowed media. But I am not sure if there's an API for that, so this bug might be blocked on browsers implementing an API for this use-case (so I am not holding my breath).

uMatrix can use `history.replaceState` in the meantime - this will still leave a spurious entry in the history that has to be gone past, but it's miles better than the current solution. The 'blocked by uMatrix' page could definitely replace itself with an inert page (i.e., that just sits there and tells the user to click back/forwards again), and it *might* be able to replace itself with another instance of the target page.
Whether that can be done will depend on whether WebExtensions' use of that API are subject to the same restrictions as Web content, which I haven't tested.

Some possibly relevant Firefox bugs:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1411724
- https://bugzilla.mozilla.org/show_bug.cgi?id=1378651
- https://bugzilla.mozilla.org/show_bug.cgi?id=1381922

**Comment by uBlock-user** [comment]
Can reproduce on Nightly too..

**Comment by gorhill** [comment]
This has been discussed before somewhere else here. For some it works, for others it doesn't. My decision was to leave this as is, the workaround is simple enough: right-click the back tab and directly select the history entry you want to go back to.

**Comment by quasicomputational** [comment]
Yeah, finding the workaround wasn't hard once I knew what was happening. Since back button misbehaviour is very annoying even with that option, I do still consider this a bug. Would you accept a PR for the `replaceState` inert hack?

RE Chromium, there's been a recent change there to prevent back button hijacking which might be relevant? But that can't explain all of the observed variance, since that's a recent change and the linked bugs have failures to reproduce on Firefox.

**Comment by quasicomputational** [comment]
Actually, I think I can fix this entirely with the `loadReplace` parameter to `tabs.update`... I'll put together a PR, since I'm already looking at the code.
