### ISSUE TITLE
localhost could use some special treatment

### ISSUE THREAD

**Issue by SmilingHorse** [uBlockOrigin/uMatrix-issues#102]
when running services that expose webguis via localhost (http://localhost or https://... or http://localhost:someport/...) there should a way to block per path.

So, for instance, say I have syncthing, transmission-daemon, a music server and ipfs. I would want syncthing and transmission fully allowed but I might need to block some stuff in http://localhost:8080/ipns/foo/ but not in http://localhost:8080/ipns/bar/. also when developing a service and exposing a webgui we'd obviously want that allowed as well...

So, localhost could use some special treatment.
thx

**Comment by gorhill** [comment]
I will decline this. uMatrix's filtering engine is entirely based on hostname-based rules, trying to fit in more than hostname-based rules would require a major refactoring, not something I want to do.

**Comment by SmilingHorse** [comment]
> uMatrix's filtering engine is entirely based on hostname-based rules

oh I just assumed you're distinguishing between https://www.freewebs.com/foo/ and https://www.freewebs.com/bar/ somehow so you'd be able to use... but checking it out now it seems you don't.

> You can use static filters or dynamic URL rules in uBO for that purpose.

I'm fine with "matrix-off: localhost false" and temporary approving whatever since I'm only using ipfs to browse wikipedia when vacationing in less fortunate regions of the world... Well, I just guessed when ipfs matures a bit someone will realize localhost:8081/ipfs/foo/bar.js can get rather naughty and do the equivalent of XHR to local services and since mozilla won't address something like this it can only come from plugins like yourself's... well, once it get popular I'm sure someone will figure it out.

peace out :)
