### ISSUE TITLE
uMatrix doesn't delete local storage

### ISSUE THREAD

**Issue by lacepede** [uBlockOrigin/uMatrix-issues#104]
### Prerequisites

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

uMatrix doesn't delete local storage

### A specific URL where the issue occurs
https://chromium.woolyss.com/

https://portableappz.blogspot.com/

### Steps to Reproduce

1. [First Step]
Only go to the site 
2. [Second Step]
3. [and so on...]

### Ruleset
All blocked
Spoof <noscript> tags when 1st-party scripts are blocked cheked
Only firts part of image and css allow

### Supporting evidence

No scenshot needed.
Go to All cookies and site data you will see

### Your environment

* uMatrix version: uMatrix 1.3.17.1
* Browser Name and version: Chromium 74.0.3689.0 (627581) • Thursday, 31 Jan 2019 compiled by Nik download on https://github.com/henrypp/chromium/releases/tag/v74.0.3689.0-r627581-win32
* Operating System and version: Windows 7 ultimate 32 bit

**Comment by uBlock-user** [comment]
incomplete steps, doesn't help in assessing the issue

**Comment by uBlock-user** [comment]
post ruleset and detailed repro steps for further investigation

**Comment by gorhill** [comment]
Also Chromium 74 is Canary, not supported.

**Comment by gorhill** [comment]
> incomplete steps

Yes, pretty bad. Visiting both sites given as example, I don't see localStorage being used, so to claim that uMatrix is not deleting empty local storage makes no sense.

**Comment by uBlock-user** [comment]
localStorage is empty for both, 3 cookies are inserted by `https://chromium.woolyss.com/` and `https://portableappz.blogspot.com/` doesn't try to store any cookies either.
