### ISSUE TITLE
Signing up to github goes "Oh no" despite having everything on "green"

### ISSUE THREAD

**Issue by RadoQS** [uBlockOrigin/uMatrix-issues#105]
### Prerequisites

- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uMatrix
- [ x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Creating an account or logging in with one created outside of µM brower fails inside µM browser with all permissions "green".

### A specific URL where the issue occurs

https://github.com/login

### Steps to Reproduce

1. Set rules as below.
2. Go to URL, fill-in, hit "Sign in".
3. returns "Oh no" something went wrong response.

### Supporting evidence

Logger:
![grafik](https://user-images.githubusercontent.com/47253619/52139567-c96b4380-2650-11e9-8b60-6f555d557e87.png)

µM on /login before pressing "sign in":
![grafik](https://user-images.githubusercontent.com/47253619/52139743-3ed71400-2651-11e9-8860-e89fc15901b7.png)

µM on /session after pressing "sign in":
![grafik](https://user-images.githubusercontent.com/47253619/52139812-6f1eb280-2651-11e9-873c-233ef68669d6.png)

rules:
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
"* * * block"
"* 1st-party css allow"
"* doubleclick.net * block"
"* etracker.com * block"
"* google-analytics.com * block"
"* googlesyndication.com * block"
github.com github.com * allow
github.com githubapp.com * allow
github.com githubassets.com * allow
github.com githubassets.com css allow
github.com githubassets.com script allow

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: FF 60.4.0 esr
* Operating System and version: win10

**Comment by uBlock-user** [comment]
> returns "Oh no" something went wrong response.

This WILL only occurr if you're blocking first-party cookies either via uMatrix or via Firefox's Content Blocking options. Since you're not blocking cookies via uMatrix, the latter is causing this. Anyways, this is not a uMatrix issue.

**Comment by gorhill** [comment]
He may have changed the rules without trying to force reload the page in order to bypass the browser cache.

**Comment by uBlock-user** [comment]
Disable blocking all cookies or set it to third-party and you will be able to login.

**Comment by RadoQS** [comment]
> Disable blocking all cookies or set it to third-party and you will be able to login.

I did have "block all cookies" in FF itself enabled. I wasn't aware this would still "matter" assuming when µM takes over control it does so exclusively. My bad, sorry.
Does this apply to javascript, too?

**Comment by uBlock-user** [comment]
> I wasn't aware this would still "matter" assuming when µM takes over control it does so exclusively.

It doesn't take control over the browser, Extensions have restrictions too.
