### ISSUE TITLE
With "* * * block" page won't load its plain-text/doc content

### ISSUE THREAD

**Issue by RadoQS** [uBlockOrigin/uMatrix-issues#108]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Opening the page with the given rules produces a blank page even though it contains plain-text content in the source view.

### A specific URL where the issue occurs

https://www.buecherhallen.de/

### Steps to Reproduce

1. Enable "block all" rules as below.
2. Go to URL.
3. Browser shows empty page.
4. Source of page shows content.

For reference I opened the page in lynx (text-only browser, its behaviour is mimiced by the block-all rule), the plaint-text content is rendered.

### Ruleset
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
"* * * block"
"* 1st-party css allow"
"* doubleclick.net * block"
"* etracker.com * block"
"* google-analytics.com * block"
"* googlesyndication.com * block"

### Supporting evidence

Uploading screenshot of µM failed, see rules section. :-/

In the log all the extra stuff (cookies, images, scripts, frame) is blocked as desired, there are only 4 lines passing through:

20:27:19	www.buecherhallen.de		css	https://www.buecherhallen.de/{inline_style}
20:27:19	www.buecherhallen.de		css	https://www.buecherhallen.de/assets/css/3a7d01e5c4b7.css	
20:27:19	www.buecherhallen.de		CSP	script-src 'unsafe-eval' blob: *	
20:27:18	www.buecherhallen.de		doc	https://www.buecherhallen.de/

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: FF 60.4.0 esr
* Operating System and version: win10

**Comment by uBlock-user** [comment]
> I opened the page in lynx

Lynx is not suported.

**Comment by uBlock-user** [comment]
As per ruleset and repro steps, plain text document still loads --

![](https://i.gyazo.com/f6709e8cf2a8dd4db39273def8bb61af.png)

**Comment by gorhill** [comment]
@RadoQS Can you please take a break from opening issues? You are currently opening too many invalid issues, this is a burden on volunteers here. Thank you.

**Comment by uBlock-user** [comment]
```
"* * * block"
"* 1st-party css allow"
"* doubleclick.net * block"
"* etracker.com * block"
"* google-analytics.com * block"
"* googlesyndication.com * block"
```
 Quotes are invalid, secondly you have `* 1st-party css allow` which takes precedence over larger block all rule, so this issue is invalid.

**Comment by RadoQS** [comment]
=- Raymond Hill wrote on Fri  1.Feb'19 at 11:51:32 -0800 -=

> @RadoQS Can you please take a break from opening issues?

I stop.

> You are currently opening too many invalid issues, this is a
> burden on volunteers here. Thank you.

I see I was mistaken with the cookies settings (github) and it was
"fixed", really sorry for that.

As for the rest, I know you can't reproduce, therefore it's useless
for you, but for me it is reproducible.
As for the blank page, I'll investigate on my own.
As for the GUI, I noticed FF has similar behaviour in other areas,
so it's probably not µM's responsibility or even possibility to fix.
But nevertheless maybe it helps you being aware of it.

Thank you for a great tool, I finally found it after looking for
years for a noScript+ (in 1 interface).

Good luck,
Rado

**Comment by RadoQS** [comment]
@uBlock-user, the "lynx" was just for reference what result I expected (txt-only), I know you don't support it. The css being allowed would actually help rather than block content to be displayed correctly, but the page should display without css well, too (the lynx reference).
I've put the quotes for formatting reasons, otherwise the "*" would be interpreted as list bullets.
How else do you put "*" in reports?
I'm sorry for all inconveniences created.

**Comment by uBlock-user** [comment]
> How else do you put "" in reports?

Insert rules inside code format like I did.

**Comment by gorhill** [comment]
> How else do you put "" in reports?

Use backticks => \`*\` => `*`

**Comment by RadoQS** [comment]
Oouuuk, I'll try to remember that, ... is this used just here or common for "quoting/ code" snippets in other tools?

**Comment by gorhill** [comment]
Common, it's [markdown syntax](https://daringfireball.net/projects/markdown/syntax).

**Comment by RadoQS** [comment]
Thanks for clarification about markdown, heard of it before, never seen & used it yet.
Since you can't reproduce but the prob persists for me, any clues on how _I_ can debug/ analyze this further?
I've seen some debug feature in FF itself for externsions, but it doesn't seem to work as I expect it.
Do you have pointers to FF-extension-analyzing tutorials/ howtos?

**Comment by RadoQS** [comment]
Just FYI, not sure whether it matters (as µM problem):

- with µM enabled
- with "security.csp.enabled=false" (in about:config)

it shows an empty page in FF when opening that page https://www.buecherhallen.de/.

If only one condition is met or none, then the page loads fine.
