### ISSUE TITLE
Local asset empty after restarting browser

### ISSUE THREAD

**Issue by eduardoeae** [uBlockOrigin/uMatrix-issues#11]
I have a hosts file and I use a simple http server (python2 -m SimpleHTTPServer) for loading it to uMatrix's assets.
I don't want the server running all the time, so I launch it when my hosts file is updated and I want to update the asset in uMatrix, and close it afterwards.
So when the browser is restarted, uMatrix looks for the file in the server (even though I have "Auto-update assets" disabled) and as the server is not up, the connection fails and, here is the problem, the asset is emptied. 0 hosts blocked.
I know that uMatrix looks for the asset at boot, because I can see it in the log of the python server (when is running).

This is Archlinux on Firefox 60.0.1

**Comment by uBlock-user** [comment]
Do you have private browsing mode activated ?

**Comment by gorhill** [comment]
> I know that uMatrix looks for the asset at boot, because I can see it in the log of the python server 

No, it shouldn't look at the asset at launch, they are supposed to be cached locally. If they are not cached locally, it's because you have specific Firefox or system settings which prevent this.

**Comment by eduardoeae** [comment]
I don't have private mode enabled, but I do have some settings for not storing history, etc. I disabled the option "Offline Website Data" in "Clear history when Firefox closes" and it no longer connects looking for the file at start, so it is not emptied anymore.
Not sure why the asset was empty if the connection failed, but my main problem is fixed.

**Comment by gwarser** [comment]
>Not sure why the asset was empty if the connection failed, but my main problem is fixed.

Because you removed it.

https://github.com/uBlockOrigin/uBlock-issues/issues/30#issuecomment-387200904
