### ISSUE TITLE
security.mixed_content.* vs. uMatrix mixed content settings

### ISSUE THREAD

**Issue by jedie** [uBlockOrigin/uMatrix-issues#112]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X] uMatrix is the only extension
    - [X] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

uMatrix default settings blocks image loaded via unsecure-http

Firefox has these "about:config" settings:

![grafik](https://user-images.githubusercontent.com/71315/52938959-40981b80-3363-11e9-9fcd-77e0f4e221af.png)

So, only "Active Content" should be blocked. So only JavaScript files, isn't it?

uMatrix default "deny mixed content" is on and blocks also Images from unsecure-http.

### Steps to Reproduce

1. install default uMatrix
2. goto a web page with mixed content images

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox v65
* Operating System and version: Ubuntu Mate 18.04

**Comment by uBlock-user** [comment]
Firefox settings are not used by uMatrix, so they don't matter.

**Comment by jedie** [comment]
That's not the point.

I think it's important to distinguish: Between active and passive content. Only active contents should be blocked.

I see two possibilities:

A) Remove uMatrix setup/functionality. Because Firefox can do it itself.

B) The uMatrix setting is separated into two settings: For active/inactive content. The uMatrix setting only sets the Firefox setting. The actual filter function is done by Firefox itself.

**Comment by uBlock-user** [comment]
> That's not the point.

You misunderstand the concept here, all mixed content is blocked if Forbid Mixed Content switch is enabled. Justb disable the switch if you don't want mixed content to be blocked.

> I think it's important to distinguish: Between active and passive content. Only active contents should be blocked.

No, that's not how CSP for mixed content works. 

> A) Remove uMatrix setup/functionality. Because Firefox can do it itself.

Why remove it when you can simply disable the switch yourself ? You may not like the way it works, but others do. Just disable the switch and mixed content won't be blocked by uMatrix.

**Comment by jedie** [comment]
> You misunderstand the concept here, all mixed content is blocked if _Forbid Mixed Content_ switch is enabled.

If i enable **security.mixed_content.block_active_content** and **security.mixed_content.block_display_content** in Firefox "about:config" then that's the same as uMatrix **Forbid Mixed Content**, isn't it?

I think the default should be to allow _display_content_ and deny _active_content_ ... 
So if the uMatrix should be not "changed" then i think it's better to disable "Forbid Mixed Content" as default.

Deny passive content like images in a "mixed-content" situation by default is IMHO overacting.

**Comment by uBlock-user** [comment]
Read up on https://github.com/gorhill/uMatrix/issues/67, I was wrong about CSP, uMatrix itself directly blocks all unsecure resource requests begining with v0.9.0.0.

**Comment by Remu-rin** [comment]
@jedie 
> So if the uMatrix should be not "changed" then i think it's better to disable "Forbid Mixed Content" as default.

It is disabled by default.
