### ISSUE TITLE
uMatrix extension console errors

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uMatrix-issues#116]
### Description

Some errors are appearing in extension console of Chromium

### A specific URL where the issue occurs

chrome-extension://eckgcipdkhcfghnmincccnhpdmnbefki/background.html

### Steps to Reproduce

No specific repro steps but these should help.

1. Browse for some time with multiple tabs open.
2. Make sure Developer Mode is enabled, if not do it. Open extension console of uMatrix by visiting chrome://extensions and then clicking background.html of uMatrix, 

### Supporting evidence

![](https://i.gyazo.com/f8914fe9f8b3c75be9146108d8d450c4.png)
![](https://i.gyazo.com/296262bdaffe20cf1474fdf5e7eec18c.png)

### Your environment

* uMatrix version: uMatrix 1.3.17.1
* Browser Name and version: Chromium 74
* Operating System and version: win10

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/d23ec182995980718a08eb882748bbf8.png)

**Comment by uBlock-user** [comment]
![image](https://user-images.githubusercontent.com/21290713/64907836-6e84e900-d715-11e9-85d0-8c8f3466f615.png)

Failed to load resource: net:: ERR_FILE_NOT_FOUND

**Comment by gorhill** [comment]
`ERR_FILE_NOT_FOUND` is normal, `vapi-cachestorage.js` is not part of the package in Chromium.

**Comment by uBlock-user** [comment]
So why does it get mentioned  everytime extension is loaded ? Can you remove the reference that looks for it ?

**Comment by gorhill** [comment]
That file is loaded in a declarative way from <https://github.com/gorhill/uMatrix/blob/master/src/background.html>, which is shared between Firefox and Chromium.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix/blob/master/src/background.html#L17

Is it needed in Firefox ?

**Comment by uBlock-user** [comment]
fyi, I'm now seeing the unchecked.runtime.lastError for uBO too today -- 

![image](https://user-images.githubusercontent.com/21290713/64918299-fe7c6e80-d7b9-11e9-8ea7-82ec5ad9ea65.png)

**Comment by gwarser** [comment]
Empty file can be added to Chrome platform.
