### ISSUE TITLE
Showing the requests in a given square of the matrix

### ISSUE THREAD

**Issue by PenelopeFudd** [uBlockOrigin/uMatrix-issues#117]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [X] I used the logger to rule out that the issue is caused by my ruleset

#### Feature Request: When I have loaded a page, and have the matrix of requests open, I sometimes wonder 'what in the world is that XHR request?', or 'what are the requests in the "other" column?'.  

* It would be awesome if I could right-click on one of the squares of the matrix and get the developer console network log entries for just those requests.  Otherwise, it's extremely tedious and frustrating trying to track those one or two requests among the dozens-to-hundreds of network requests made by a typical page.

* For bonus points, it would be cool to specify a regular expression for allowed/disallowed requests in that square.  There's a way to do that now (I think?), but if you right-click on the square, it could pre-fill all or most of the regular expression for you!

**BTW**: If the user fills in the square brackets in this issue template with an X (e.g. [X]), they're pre-checked, and they don't have to check the boxes after submitting the issue.

**BTW^2**: Is there a way to have two issue templates; one for bugs and one for feature requests?

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Ruleset

N/A

### Supporting evidence

N/A

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Chrome  72.0.3626.109 (Official Build) (64-bit)
* Operating System and version: MacOS Sierra 10.12.6

**Comment by uBlock-user** [comment]
> * Otherwise, it's extremely tedious and frustrating trying to track those one or two requests among the dozens-to-hundreds of network requests made by a typical page.

Have you tried using uMatrix's logger ?

**Comment by gorhill** [comment]
Declined, I have no time to fix most issues, let alone adding features (which themselves will lead to more issues piling up).

**Comment by gcb** [comment]
I've been using a local patch since 2018 to do this:

![umatrixtooltip](https://user-images.githubusercontent.com/56283/75381820-4e458280-588e-11ea-9463-62232ac10f4f.png)

The data is already available on rendering the UI and it was quick to add as a hack. if there's interest   (mostly gorhil :sweat_smile:) i can clean up and add a on/off setting. The only drawback i've found those years is that sometimes the list doesn't fit, but that's very minor and hopefully won't generate many tickets here :)

**Comment by PenelopeFudd** [comment]
I was mainly curious in the 'other' column, because I've got no idea what kind of requests are classified as 'other'.

And there have been the occasional page I've tried to get to work, eventually enabling everything, but it still doesn't work until I disable uMatrix for that page.  Or pages where the toolbar icon says there's one item blocked, but the matrix shows everything is enabled.  Weird.

**Comment by PenelopeFudd** [comment]
Ok, I've finally looked at the logger (shoulda done this months ago), and I can see the 'type' column with some requests having the type of 'other'.  On this page for instance, one of the 'other's is https://github.com/manifest.json , I'm guessing that the original url is called 'doc', and the rest are classified according to their filename extension, with those that aren't matched called 'other'.  Guess I could have read the source to figure that out.  :-/

Minor request: could the log output have headers on the columns?  Clicking on the blank third column (which could use an icon or something) apparently pops up the matrix elements that matched that rule, but what's the final column, which shows '3p' or blank?

**Comment by PenelopeFudd** [comment]
Oh, wait, are those third-party urls?
