### ISSUE TITLE
Image is identified as xhr

### ISSUE THREAD

**Issue by tastytea** [uBlockOrigin/uMatrix-issues#119]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

My profile image on https://schlomp.space/tastytea is identified as xhr by uMatrix. The relevant HTML snippet is:
```HTML
<span class="image">
    <img src="https://avatar.tastytea.de/avatar/9fa92bdc50493aa8d3cdcde9f56d3125?d=identicon&amp;s=290" title="tastytea"/>
</span>
```

I have this issue since 1 or 2 days (as far as I remember), it worked fine before. When I force-refresh (ctrl+F5), the image appears, when I refresh normally or open the page in a new tab after that, the image is gone again.

I have tried to reproduce the issue in a simpler HTML document but I didn't succeed, the snippet below works fine.

```HTML
<!DOCTYPE html>
<html>
<body>
<span class="image">
    <img src="https://avatar.tastytea.de/avatar/9fa92bdc50493aa8d3cdcde9f56d3125?d=identicon&amp;s=290" title="tastytea"/>
</span>
</body>
</html>
```

### A specific URL where the issue occurs

https://schlomp.space/tastytea

### Steps to Reproduce

1. Visit <https://schlomp.space/tastytea/>, the image is there
2. Refresh page, the image is gone
3. Force-refresh (ctrl+F5), the image is there again
4. Refresh normally, the image is gone again

### Ruleset

I tested with a fresh install, I did nor modify any rule.

### Supporting evidence

Logger, filtered for "avatar": 
![screenshot_2019-03-03t14 41 06](https://user-images.githubusercontent.com/3681516/53695970-75c05700-3dc2-11e9-94ce-333fc47cd135.png)

Logger, unfiltered: 
![screenshot_2019-03-03t14 41 28](https://user-images.githubusercontent.com/3681516/53695976-7c4ece80-3dc2-11e9-881d-f886c4d48eee.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox Quantum 65.0.2 (64-Bit)
* Operating System and version: Gentoo Linux

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/71b480bf9b503f84f65144c3fe8b73fb.png)

Cannot reproduce on Nightly, bug specific to stable release of Firefox?

**Comment by gwarser** [comment]
It's service worker - image is cached by service worker. @uBlock-user close page and open again - sw should then kick in.

**Comment by uBlock-user** [comment]
> close page and open again - sw should then kick in.

Not happening on my end, image is not getting cached, despite service worker running both in Chromium and Firefox.

**Comment by tastytea** [comment]
I can reproduce it in nightly (firefox-67.0a1.en-US.linux-x86_64).

**Comment by uBlock-user** [comment]
@gwarser Were you able to reproduce ?

**Comment by gwarser** [comment]
Yes, avatar is 3p xhr, so it's blocked.

**Comment by gorhill** [comment]
If it's reported as `xhr`, then the browser is telling uMatrix the network request is `xhr`.
