### ISSUE TITLE
Change default rule and recipe behaviour to block 1st-party xhr

### ISSUE THREAD

**Issue by migueldemoura** [uBlockOrigin/uMatrix-issues#12]
### Prerequisites

* [X] Did you perform a cursory search of the issue tracker?
* Can you reproduce the problem when...
    * [X] uMatrix is the only extension? **N/A**
    * [X] uMatrix with default lists/settings? **N/A**
    * [X] using a new, unmodified browser profile? **N/A**
* [X] Are you running the latest version?
* [X] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description 

According to https://github.com/gorhill/uMatrix/wiki/Ruleset-recipes, recipes should target the following strict rules:

```
* * * block
* * script block
* * frame block
* first-party * allow
* first-party frame allow
```

I can confirm the current built-in recipes obey this rule. However, I believe these aren't strict enough. In my opinion, XHR's should be blocked by default as well (and recipes should take this into account).

The purpose of recipes is to, and I quote, `un-break a specific web site or behavior`. Usually, one only needs to allow a couple scripts to get proper display of elements. XHR's aren't needed in most cases, and should only be enabled when needed.

### Proposed change

Adding `* * xhr block` to the default list.

I'm available to contribute with adjusting the current recipes so they work with this change (only a few would require adding `_ 1st-party xhr`).

### Your environment

* uMatrix version: 1.3.8
* Browser Name and version: Chromium 66.0.3359.139 64-bit
* Operating System and version: buntu 18.04

**Comment by TriMoon** [comment]
@migueldemoura  Doesn't ```* 1st-party * allow``` already include **xhr**?

**Comment by gorhill** [comment]
I am declining this, I disagree that 1st-party xhr should be blacklisted by default.

**Comment by migueldemoura** [comment]
@TriMoon, @uBlock-user in that case, `* first-party * allow` does not include xhr and recipes that whitelist scripts will also whitelist xhr.
