### ISSUE TITLE
Blocked Frames have no Placeholder nor display <noframes>

### ISSUE THREAD

**Issue by girst** [uBlockOrigin/uMatrix-issues#120]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Blocked iframes get replaced with a placeholder, but blocked frames (in a frameset) just display a white page. The ([obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noframes)) `<noframes>` element is not displayed either, even if 1st-party-frames are blocked too.

### A specific URL where the issue occurs

http://spth.de/

### Steps to Reproduce

1. make sure some frames are blocked
2. navigate to a website that uses frames, e.g. http://spth.de (uses 3rd party frame)
3. instead of a placeholder, nothing is displayed

### Ruleset

default ruleset
```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
```

### Supporting evidence

https://imgur.com/6ekhiRG.png

### Your environment

* uMatrix version: **1.3.16**
* Browser Name and version: **`firefox-65.0.2-1.fc29.x86_64`**
* Operating System and version: `PRETTY_NAME="Fedora 29 (Twenty Nine)"`

**Comment by uBlock-user** [comment]
I believe this always has been the case with Firefox, Chromium does display a placeholder of its own.

**Comment by girst** [comment]
There sure is no rush, but it'd be great if this could be addressed 
sometimes, because it is quite distracting if you don't know why you're 
getting a white screen (javascript req'd? network error? page broken?)

Showing the umatrix-iframe-placeholder would probably be the best way 
forward, since there may be other frames that have loaded (so 
`<noframes>` won't make sense), and you can easily open the frame in a 
new window then.  also, I don't know how often a `<noframes>` tag is 
used.
