### ISSUE TITLE
Bookmark icon no work after block all images

### ISSUE THREAD

**Issue by goranv2** [uBlockOrigin/uMatrix-issues#121]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

When i block all image and open link from bookmark icon, icon no more work in most links. This has also happened in the previous version of Chrome and uMatrix. I suggest adding in uMatrix settings one checkbox fox except favicon.ico.

### A specific URL where the issue occurs

https://1337x.to
https://xatab-repack.net/

### Steps to Reproduce

1. block all image in some or all sites
2. open link from bookmark, icon in no more work

### Ruleset

https-strict: * true
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: google.com true
matrix-off: google.si true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block

### Supporting evidence

http://shrani.si/f/43/9a/3LD0CAeg/fgsnfnd.jpg

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version:  Chrome x64 73.0.3683.75
* Operating System and version: Windows 10 x64 17134.648

**Comment by uBlock-user** [comment]
By design. If you block images, favicons can't be downloaded as well as they're categorised as images as well, so it will appear broken.
