### ISSUE TITLE
uMatrix breaks youtube functions in watch2gether.

### ISSUE THREAD

**Issue by Ryonez** [uBlockOrigin/uMatrix-issues#123]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When trying to add a youtube video url to watch2gether room or try to search for a youtube video in a room, no results are returned for you to play.

The only way to get it to work so far is to uninstall uMatrix, disabling the extension it will **not** work.

This is consistently replicable.

### A specific URL where the issue occurs

Any room at:
https://www.watch2gether.com

Then try to add a youtube url or search a video here:
![image](https://user-images.githubusercontent.com/16157130/54879512-a9ad0a80-4e9e-11e9-9459-a9c22d861ce5.png)

### Steps to Reproduce

1. Go to any room at https://www.watch2gether.com
2. Then try to add a youtube url or search a video here:
![image](https://user-images.githubusercontent.com/16157130/54879512-a9ad0a80-4e9e-11e9-9459-a9c22d861ce5.png)

### Ruleset

Non default rules:
```
watch2gether.com googlevideo.com * allow
watch2gether.com suggestqueries.google.com script allow
watch2gether.com www.googleapis.com xhr allow
watch2gether.com youtube.com * allow
watch2gether.com youtube.com frame allow
watch2gether.com ytimg.com * allow
```
### Supporting evidence

https://www.youtube.com/watch?v=xA4aaSzqT9s
Chrome Console output (SUCCESSFUL load)
![image](https://user-images.githubusercontent.com/16157130/54877323-bb33e980-4e81-11e9-9f01-88156d2a4264.png)

Firefox console output (FAILED)
![image](https://user-images.githubusercontent.com/16157130/54879582-80d94500-4e9f-11e9-8617-3fdf6d288c71.png)

Firefox uMatrix logger output:
![image](https://user-images.githubusercontent.com/16157130/54879606-b120e380-4e9f-11e9-9717-2128f55cf7b2.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.1 (64-bit) and Firefox Developer Edition 67.0b4 (64-bit)
* Operating System and version: Windows 10 version 1809

**Comment by uBlock-user** [comment]
> Do not post issues regarding broken sites. 

> uMatrix is a browser firewall, you're expected to be able to unbreak any breakage caused by the ruleset.

uMatrix is a browser firewall, you're expected to be able to unbreak any breakage caused by the ruleset.

**Comment by Ryonez** [comment]
@uBlock-user 

Umm, sorry?

Please re-read the submitted info. I spend 4 hours trying things such as:

 - Allowing everything, *globally*
 - Disabling the extension, **At which point it shouldn't be blocking anything. It did anyway.**
 - Trying another browser (Chrome), with the *exact same* rule sets. **It worked.**
 - And then when I came here, I took the time to go through your checklist, trying only the extension by itself, and with a clean profile.
 - The only *only* way to get the site to function without impedance was by **removing the extension completely.**

So before closing shit and pissing off, read the submitted info. Even a casual look will show you that uMatrix itself isn't logging that it's blocking anything. And the fact that the ruleset works on chrome.

As such, this is submitted as a problem with uMatrix itself, not the ruleset or the site.

**Comment by gorhill** [comment]
> Disabling the extension

How did you accomplish this?

**Comment by Ryonez** [comment]
> How did you accomplish this?

In the about:addons page, each extension has a button to disable it, and to remove it. uMatrix also supports the options button, so that's enabled as well:
![image](https://user-images.githubusercontent.com/16157130/54881105-4082c280-4eb1-11e9-8169-f4324eb681d5.png)

> Also, did you read About "the page is still broken after I created all necessary rules"?

Yup, that linked stood out to me on the documentation page. The only thing I couldn't account for from the list was regarding "behind-the-scene scope". However that was because I couldn't find were those settings where. Overall though, I hadn't made any changes to it and it sounds like the default is it's disabled.

**Comment by gorhill** [comment]
If you disable uMatrix from `about:addons`, then this means the issue is not with uMatrix. Check that Firefox's own content blocker is not interfering.

**Comment by Ryonez** [comment]
> If you disable uMatrix from about:addons, then this means the issue is not with uMatrix. Check that Firefox's own content blocker is not interfering.

The issue goes away though when uMatrix is uninstalled.

I've just checked on the dev firefox after removing uMatrix. With no changes to the default content blocker settings, the youtube functions work.

Something about uMatrix is triggering the issue.

I'd like to piont out again that disabling uMatrix doesn't fix it, only removing it does.

Another interesting note, after installing uMatrix, it takes a minute or two before the youtube function breaks again.

**Comment by gorhill** [comment]
I had no problem make it works -- but I simply needed to disable "Referrer spoofing" for that site for the Youtube search to work.

**Comment by Ryonez** [comment]
> I had no problem make it works -- but I simply needed to disable "Referrer spoofing" for that site (along with a few obvious allow rules) for the Youtube search to work.

That appears to have done it, though why I don't know why.

That setting is enabled on Chrome. And it shouldn't matter when the extension is disabled, none of the rules should be being applied.

I will thank you, you got it.
How did you figure that out? Did I miss something?

**Comment by gorhill** [comment]
> Did I miss something?

We pointed at you twice for help on how to figure such breakage:
[About "the page is still broken after I created all necessary rules"](https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22):

> Did you verify that one or more per-scope switches are also interfering?

The logger was telling you that REFERER header was modified -- though you posted a truncated version of it.

> extension is disabled, none of the rules should be being applied.

And that is the case. Again, in the link above, it says:

> Did you try to bypass the browser cache when you forced a reload of the page?

I do prominently warn that uMatrix is for advanced users.

**Comment by Ryonez** [comment]
> I do prominently warn that uMatrix is for advanced users.

Yeah, but it's not rocket science and it is behaving inconstantly.

> The logger was telling you that REFERER header was modified -- though you posted a truncated version of it.

I've told it to spoof the referrer again, and seeing no errors or warnings complaining about this.

> The browser cache is outside of uMatrix control, even more so after you disable completely uMatrix.

Yup, that was what was interfering still even after disabling it.

Now, I'm not going to say I didn't fuck up. I clearly need to bypass the cache more when using this tool. But can you please point out where "The logger was telling you that REFERER header was modified -- though you posted a truncated version of it." is please? I'm staring at it the screenshot and the fresh logs, and I can't see it.

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/54882447-e5ad8480-4e38-11e9-9600-48a92605018a.png)

**Comment by uBlock-user** [comment]
> That setting is enabled on Chrome.

Websites behave differently on a specific browser and may serve different pages, so there's no point in making a comparision with Chrome.

**Comment by Ryonez** [comment]
> Websites behave differently on a specific browser and may serve different pages, so there's no point in making a comparison with Chrome.

Kinda fair enough, though it worked and I couldn't see why it shouldn't in firefox.

> I linked you enough documentation which you obviously didn't read before posting otherwise you could have figured it out on your own instead.

That is frankly insulting, especially as I went through all of that as part of the *prerequisites*:
![image](https://user-images.githubusercontent.com/16157130/54885259-0d572800-4edf-11e9-95ba-85c2e536e193.png)

A combination of no logger errors (Which after being shown it by @gorhill I have managed to find) as well as *why I didn't when I was looking at the logger* along with missing the bypass cache when toggling that setting is why I didn't narrow it down myself
Maybe you should document the "behind-the-scene scope" because that's not in there.
I took the time to test, and missed one thing along with the logger not displaying the error at the time. It happens, and insulting me mistakes that aren't really obvious is bloody rude.

Now with the missing error with the logger, it only shows on the initial tab load. Not even a refresh bypassing the cache will trigger it again:

This is the initial tab load: 
![image](https://user-images.githubusercontent.com/16157130/54885508-b56df080-4ee1-11e9-8594-166c9c8041b5.png)

This is what happens with a refresh that bypasses the cache: 
![image](https://user-images.githubusercontent.com/16157130/54885520-e4846200-4ee1-11e9-972b-c618003e8bdb.png)

Even with the referrer-spoof enabled, that error does not show up again.

Now on the otherhand, I get it. It was a site issue in the end. But from a user standpoint after spending hours of searching and testing, only to end up here, then to spend more time going through the checklist and not being able to find it at the time, having something you spent so much time putting together just to have it closed is frustrating, especially when you just link all the stuff I went through before.

Thank you @gorhill for your patience. I do understand while I was frustrated, you guys probably were as well at the "noob". Thank you for going though and having a look from your side, I now have an additional check if things go weird again.

**Comment by uBlock-user** [comment]
> That is frankly insulting, especially as I went through all of that as part of the prerequisites:

> I took the time to test, and missed one thing along with the logger not displaying the error at the time. It happens, and insulting me mistakes that aren't really obvious is bloody rude.

NO, not insulting, but rather letting you know that you didn't go through the entire wiki at least once or so you wouldn't have missed it. No need to get angry or feel insulted. 

I closed it because we don't deal with broken sites here, but gorhill still helped you out, even though there's no reason to help as uMatrix is only for advanced users who are willing to fix site breakage on their own, this is understood when you and all other users install this extension. 

This isn't a customer care support system for everyone to post their site breakage issues, just because they missed something or didn't the read the entire wiki at least as expected, but people still post sometimes so they're closed and left for people to figure for themselves or ask for help on [reddit](https://www.reddit.com/r/uMatrix/). Next time you experience site breakage, ask for help on reddit, that's is what it's true purpose is anyway. We have gone off topic enough, so closing this for good.
