### ISSUE TITLE
uMatrix not working on FireFox 66.0.1 32bit

### ISSUE THREAD

**Issue by WalSel** [uBlockOrigin/uMatrix-issues#124]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

After FF Start uMatrix Icon is grey and all Settings are unchecked.
The Icon stays grey while browsing to any page and no matrix content is displayed.

Deactivating the uMatrix add-on and activating it starts uMatrix correctly till next FF Start.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: FF 66.0.1 32bit
* Operating System and version: Win 7 all updates

**Comment by uBlock-user** [comment]
Post Steps to Reproduce for further investigation...

**Comment by WalSel** [comment]
After FF Start and browsing to any page uMatrix window is empty:

---------------------------------------------------------------------------
![nMatrixFF](https://user-images.githubusercontent.com/48985480/55069347-19c8b580-5084-11e9-9780-045782067434.png)

---------------------------------------------------------------------------

This is new after last FF update.

I deleted uMatrix and added ist to FF again but this didn't solve the problem.

**Comment by WalSel** [comment]
With uMatrix newly added to FF with no modification to uMatrix settings and rules the umatrix window stays empty until deacticate an activate uMatrix add-on.

**Comment by WalSel** [comment]
After FF Start:
----------------------------------------------------------------------------
![nMatrixFFconsole](https://user-images.githubusercontent.com/48985480/55071162-1fc09580-5088-11e9-95c2-a4eeaf90a2b0.png)
----------------------------------------------------------------------------

**Comment by WalSel** [comment]
Looks like:

https://github.com/uBlockOrigin/uMatrix-issues/issues/101

**Comment by uBlock-user** [comment]
@gorhill Can you reproduce ?

**Comment by gorhill** [comment]
I can not reproduce.

**Comment by gorhill** [comment]
The console output is useless, it's truncated and possibly the useful output is out of view.

**Comment by gorhill** [comment]
The next steps is for OP to check the other checkboxes in the template, likely there is something wrong in his profile.

**Comment by WalSel** [comment]
FF V66.0.2 and gone!

Thank You for your time.
