### ISSUE TITLE
Different schemes for first load and reload of local file result in non-blocking on first load.

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uMatrix-issues#125]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When opening a local file 3rd-party images are loaded when rules block all 3rd-party.

### A specific URL where the issue occurs

In the STR below.

### Steps to Reproduce

1. Have the following html saved as `test.html` (but use a real URL to existing image).

```
<!DOCTYPE html>
<html>
    <body>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Yunsup_Lee_holding_RISC_V_prototype_chip.jpg/330px-Yunsup_Lee_holding_RISC_V_prototype_chip.jpg" />
    </body>
</html>
```

2. Start browser (all cache cleaned)
3. Open the `test.html`

#### Expected:

The image should not show because it is a 3rd-party resource.

#### Actual:

The image shows up.

4. Hit 'F5' to refresh the page

The image disappears.

### Ruleset

```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
```

### Supporting evidence

The log shows that the initial load and the refresh are in a different scheme:

```
21:35:08	file-scheme	--	image	https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Yunsup_Lee_holding_RISC_V_prototype_chip.jpg/330px-Yunsup_Lee_holding_RISC_V_prototype_chip.jpg	3p
21:34:54	newtab.chrome-scheme		image	https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Yunsup_Lee_holding_RISC_V_prototype_chip.jpg/330px-Yunsup_Lee_holding_RISC_V_prototype_chip.jpg	3p
```

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Chromium 72.0.3626.122 (64-bit)
* Operating System and version: openSUSE Leap 15.0

**Comment by uBlock-user** [comment]
> The log shows that the initial load and the refresh are in a different scheme:

By-design browser limitation. If the requests initiated are from _newtab.chrome-scheme_, then they will not be blocked by uMatrix because extensions are not allowed to work on chrome://urls.

**Comment by emanruse** [comment]
Thanks for explaining. I wasn't aware of that.

As a workaround: Is it possible to have "matrix-on" for `newtab.chrome-scheme` while having it off for `chrome-scheme`? Also: where can I read more about why matrix is off by default for the various schemes listed above?

**Comment by uBlock-user** [comment]
> Is it possible to have "matrix-on" for newtab.chrome-scheme while having it off for chrome-scheme

it will not work because `newtab.chrome-scheme` = `chrome://newtab` which is part of `chrome-urls://`

**Comment by uBlock-user** [comment]
> where can I read more about why matrix is off by default for the various schemes listed above?

https://github.com/gorhill/uMatrix/wiki/Default-ruleset-at-installation

**Comment by gorhill** [comment]
> Is it possible to have "matrix-on" for `newtab.chrome-scheme` while having it off for `chrome-scheme`?

Yes: `matrix-off: newtab.chrome-scheme false`

**Comment by emanruse** [comment]
> https://github.com/gorhill/uMatrix/wiki/Default-ruleset-at-installation

That simply lists the default rules. It doesn't explain why matrix is off for certain schemes, so for example I don't know what would be the consequences of having the matrix on for some or all of them. Any more complete documentation?

> Yes: `matrix-off: newtab.chrome-scheme false`

Thanks!
Considering the browser limitation leading to this "non-bug" would it make sense to have that in the default rules too?

**Comment by gorhill** [comment]
You may remove all the default `matrix-off` rules if you wish, but I won't remove these. For new users, it's easier to remove these rules then add them since they require knowledge of how uMatrix derives fake hostnames from schemes.

**Comment by emanruse** [comment]
I am not asking you to remove anything. I am asking two other things:

1. More info about the different schemes (documentation)
2. Given the browser limitation to have (add) `matrix-off: newtab.chrome-scheme false` to default rules.
