### ISSUE TITLE
This page is outdated - "Default ruleset at installation"

### ISSUE THREAD

**Issue by ReporterX** [uBlockOrigin/uMatrix-issues#127]
This page is outdated and contains wrong info.
https://github.com/gorhill/uMatrix/wiki/Default-ruleset-at-installation

The default ruleset has been updated. It is: 
```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
```

**Comment by uBlock-user** [comment]
@gwarser can you edit the wiki? I don't see the button.

**Comment by gwarser** [comment]
No.

I can try cloning uMatrix wiki to uMatrix-issues, and then edit here.

**Comment by uBlock-user** [comment]
Sure, do that.

**Comment by gwarser** [comment]
Cloned.

**Comment by uBlock-user** [comment]
same thing with cloning, now I can only edit -- https://github.com/gorhill/uMatrix/wiki/, individual pages still not accessible just like with uBO wiki, you will have to edit this somehow like you do.

**Comment by gwarser** [comment]
You need to select page from sidebar, because links from "Home" are absolute, and load original repo.

**Comment by uBlock-user** [comment]
Updated ruleset - https://github.com/uBlockOrigin/uMatrix-issues/wiki/Default-ruleset-at-installation

**Comment by uBlock-user** [comment]
@ReporterX The wiki isn't outdated, please don't add that msg on the top. It just requires new submissions to be made on https://github.com/uBlockOrigin/uMatrix-issues/wiki/Default-ruleset-at-installation and then wait for @gorhill to update on https://github.com/gorhill/uMatrix/wiki/Default-ruleset-at-installation

**Comment by ReporterX** [comment]
@uBlock-user OK, but it probably causes confusion for people since there are two wikis with the same structure. I guess it would be better if there is a description to explain about it. You may change the description instead of deleting all though.

**Comment by gwarser** [comment]
Looks like relative links in Markdown are supported, but in edit mode they are relative to `wiki/Home` instead of just `wiki/`.

I have changed them in Home page.
