### ISSUE TITLE
Unable to have the rules applied to some pages

### ISSUE THREAD

**Issue by Dupond** [uBlockOrigin/uMatrix-issues#13]
First of all, I'd like to apologize for my bad english.

### Prerequisites

- I've performed some searches for several hours, including the wiki and the old issue tracker, and trying many rulesets.
- I've tried with uMatrix as the only extension, and in an unmodified browser profile.

### Description

With the default extension rules, the addons.mozilla.org pages are fully displayed (I mean with all the images, scripts, XHR, etc.) and my researches haven't shown me a way to restrict these pages (for example, I'd like to disable third-parties if they exist, and to disable XHR...). The same seems to occur with some pages displayed in Firefox reader mode : sometimes even if I hide the images in the normal view, they are displayed in the reader mode.

### A specific URL where the issue occurs

For example, simply going to the "uMatrix" search page of addons.mozilla.org shows the page with scripts, XHR, etc. working : https://addons.mozilla.org/en-US/firefox/search/?q=umatrix&platform=Linux&appver=60.0.1

### Your environment

* uMatrix version: 1.3.8
* Browser Name and version: Firefox 60.0.1
* Operating System and version: by the way, I use Arch !

**Comment by uBlock-user** [comment]
`addons.mozilla.org` and `chrome.google.com/webstore/category/extensions` are considered privileged pages by the respective browser makers, so filters and rules cannot be applied there.

> Firefox reader mode

AFAIK, Firefox bypasses uBO in reader mode.

**Comment by Dupond** [comment]
Oh OK ! I haven't seen it notified in the wiki, though. What would be the best way for me to suggest to add this information to the wiki ? Or should I dare and edit it now ?

> related to this - gorhill/uBlock#2754 (comment)

If I understand correctly, I should install uBlock origin for this, am I right ?

**Comment by uBlock-user** [comment]
Is your issue with the wiki information or the fact that rules cannot be applied to those those pages via the extension ?

**Comment by Dupond** [comment]
I was only talking about uMatrix, so by "hiding", I meant "blocking" in uMatrix. Sorry for the mistake.

My issue, as you can have read, was about applying my rules. Since I can't, it's directly related to not having found this information in the wiki, hence my question. It's not another issue ; I was asking for an information, that's all.

**Comment by uBlock-user** [comment]
You won't be blocking anything as uMatrix will not do  it job on those pages. 

> My issue, as you can have read, was about applying my rules. Since I can't, it's directly related to not having found this information in the wiki, hence my question.

I did read, but since you questioned wiki's info about it, so I had to ask as there was another issue where user wanted to the info to be added to the wiki rather.

**Comment by Dupond** [comment]
Just wanted to add a big thank you for the answers and the informations.

Let me know in case you think it would be interesting that I could suggest an addition to the wiki. I think my bad english would be an obstacle to edit it by myself, though :(

**Comment by Dupond** [comment]
Oops ! I hadn't seen your addition. Thank you very much for it ! It seems that we have written nearly at the same moment.

**Comment by gwarser** [comment]
Firefox list is bit longer:

```
accounts-static.cdn.mozilla.net
accounts.firefox.com
addons.cdn.mozilla.net
addons.mozilla.org
api.accounts.firefox.com
content.cdn.mozilla.net
content.cdn.mozilla.net
discovery.addons.mozilla.org
input.mozilla.org
install.mozilla.org
oauth.accounts.firefox.com
profile.accounts.firefox.com
support.mozilla.org
sync.services.mozilla.com
testpilot.firefox.com
```
Can be found in `about:config` `extensions.webextensions.restrictedDomains`

**Comment by uBlock-user** [comment]
@gwarser Would you mid adding those then ?

**Comment by uBlock-user** [comment]
@gwarser Would you mind adding those then ?

**Comment by gwarser** [comment]
@uBlock-user take a look https://github.com/gorhill/uMatrix/wiki/Privileged-Pages I thing it needs rephrasing, because both Chrome and Firefox use domains.

**Comment by uBlock-user** [comment]
`chrome.google.com` will redirect you to - `https://www.google.com/chrome/ ` where extensions will work normally, that's why I added `/webstore/`, you should revert that back. I don't see any other issue.

**Comment by gwarser** [comment]
If they ever create `/not-webstore/` page, extensions will not work here. Maybe  "chrome.google.com (mainly https://chrome.google.com/webstore/)"?

**Comment by Dupond** [comment]
By the way, I forgot to mention it, but the default ruleset mentioned in the wiki is not the one I had when I re-installed uMatrix. Unfortunately, since I've applied my ruleset, I don't know exactly what the differences are.

**Comment by gwarser** [comment]
Fixed https://github.com/gorhill/uMatrix/wiki/Default-ruleset-at-installation

**Comment by gwarser** [comment]
Firefox bug is finally open to read https://bugzilla.mozilla.org/show_bug.cgi?id=1415644
