### ISSUE TITLE
No 3rd party requests are shown

### ISSUE THREAD

**Issue by Lyberta** [uBlockOrigin/uMatrix-issues#132]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

uMatrix doesn't show any 3rd party requests. This can be tested on heavy sites such as GitHub.

This happens even if uMatrix is the only extension but doesn't happen with a blank profile.

### Steps to Reproduce

1. Go to any site heavy with 3rd party requests.
2. Open uMatrix dashboard and it shows only 1st party domain.

### Ruleset

I'm also having #129 so I'm running with default ruleset.

### Supporting evidence

![uMatrix](https://user-images.githubusercontent.com/10873185/56061439-187cd580-5d72-11e9-8443-58bb41df3f99.png)
### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 60.6.1esr (64-bit)
* Operating System and version: Debian Testing amd64

**Comment by gorhill** [comment]
Did you try to force a cache-bypass?

**Comment by Lyberta** [comment]
How do I do that?

**Comment by gorhill** [comment]
Press Shift while clicking the reload button.

**Comment by Lyberta** [comment]
Didn't help.

**Comment by uBlock-user** [comment]
> but doesn't happen with a blank profile

Did you modify any `about:config` entries ?

**Comment by Lyberta** [comment]
I have 505 entries in `prefs.js`.

**Comment by gorhill** [comment]
With such a modified browser config, you are best placed to investigate and identify such issue which is not reproduced by others.

**Comment by Lyberta** [comment]
Are you sure? What kind of config can produce this? I have no idea.

**Comment by uBlock-user** [comment]
It's not a uMatrix issue, which is backed up by the fact that it doesn't happen on a new profile, so whatever changes you made to `about:config`, broke uMatrix.

**Comment by Lyberta** [comment]
This was not an `about:config` issue. It was in indexedDB issue. I deleted `storage/default/moz-extension+++95519255-adbf-41c8-bee1-4f68be8ad0b7` directory and got it working.
