### ISSUE TITLE
Can we have a 'Go there anyway' option ?

### ISSUE THREAD

**Issue by heronils** [uBlockOrigin/uMatrix-issues#133]
_I am using uMatrix version 1.3.16 in the Iridium webbrowser, version 2018.11 (Official Build) (64-Bit). My operating system is Windows 7._

Thank you for uMatrix and that you allow people to freely use it. It is a very useful addon.

Sometimes uMatrix prevents me from visiting a website, showing a template indicating that it did so. But sometimes i want to go there anyway, with uMatrix temporarily disabled, because i have reasons to do so. I am using the Iridium web browser which is a variant of chrome, with some unwanted google features, like the auto updater or the software reporter stripped away. But the price is that addons can not be disabled temporarily in Iridium. I need to uninstall uMatrix whenever i want to visit a blocked website. Disabling uMatrix from the Control panel will still prevent me from visiting this website.

So, may i ask for a link: _go there anyway with uMatrix disabled (uMatrix will NOT protect you)_ in that template, if this does not steal too much from your valuable time?

Thank you for your attention and keep up the good work.

Regards, Nils.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uMatrix-issues/wiki/How-to-get-past-%22uMatrix-has-prevented-the-following-page-from-loading%22

**Comment by heronils** [comment]
Thanks a lot. I did not see that because the message is in german here.
