### ISSUE TITLE
Keep comments in the rules at least in the header when saving them

### ISSUE THREAD

**Issue by farblos** [uBlockOrigin/uMatrix-issues#135]
This is an enhancement request.

### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Keep comments in the rules at least in the header when saving them.

I keep my rules in a version control system and like to have the version of the current rules available somehow.  Currently I resort to a dummy rule

  https-strict: 000.work.um.rules.1.8 true

but that is a crude hack and requires manual update before check-in.

I guess that it is hard-to-impossible to keep comments in the rules in general (seems they are sorted when saved), but probably somehow at least the header comments could be kept.  Unsorted.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Ruleset

N/A

### Supporting evidence

N/A

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 60.6.1esr (64-bit)
* Operating System and version: Oracle Linux Server 6.10

**Comment by gorhill** [comment]
Rules are completely under the management of uMatrix, the UI is merely a view of uMatrix 's internals. When you create/change/remove rules using point-and-click, uMatrix must have full liberty of changing the ruleset without having to worry about guessing whether comments should be removed or worst restored.

Declined.

**Comment by egor-duda** [comment]
Would it be acceptable to extend the UI functionality to allow adding comments for any specific rule?

For instance, right clicking on the rule's area in the UI would open an input field for entering the comment. Rules with comments would have a visual sign (for instance, an asterisk in upper right corner), which shows that this rule has some comment attached to it. Hovering over that sign would show the comment.

If user removes the rule which has a comment, then that comment is going to be lost, obviously.
