### ISSUE TITLE
uMatrix needs an option to consider *.cloudfront.net subdomains of cloudfront.net.

### ISSUE THREAD

**Issue by GrayFace** [uBlockOrigin/uMatrix-issues#136]
### Prerequisites

- [ x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

The rationale explained in previous bug reports states that Public Suffix List is used and in it *.cloudfront.net are considered domains. However, that's only an implementation detail. In practice for all intents and purposes for site scope having them as subdomains is the right way, because these pseudo-domains tend to change their names. (At least I've seen them change name on some site) As a result, now the only way to target them is to use an "All" rule for the site that uses them. There are also manual rules, but that's way too cumbersome to do on multiple sites when "All" rule is so much easier, albeit not as secure.
Sure, it should probably be an option that power users would turn on. It would also make sense for this option to only show such domains as subdomains in various site scopes, but not global scope, because someone enabling *cloudfront.net everywhere is undesirable.

### A specific URL where the issue occurs

https://loudwire.com/slipknot-chris-fehn-shows-percussive-skills-in-latest-teaser-video/

### Steps to Reproduce

1. Open the URL above.
2. See <something>.cloudfront.net, but not cloudfront.net in the uMatrix list.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Cent Browser Version 3.9.2.45 (Official Build) (32-bit) (portable) (Chromium 72.0.3626.121)
* Operating System and version: Windows 7 x64

**Comment by gorhill** [comment]
> these pseudo-domains tend to change their names

This is highly doubtful. Even though, as I said already, I won't second guess the PSL, it rules how based domains are determine -- no exception.

Declined.
