### ISSUE TITLE
Option to change cell colour

### ISSUE THREAD

**Issue by shakee77** [uBlockOrigin/uMatrix-issues#139]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Hello,

I would like to give you an idea for a new feature: Changing the colour theme of the cell.
I am colour blind, exactly i have deuteranopia, which makes it for me impossible to use this wonderful tool because i can not see a difference between red and green (especially the dark tones).

Around 12 % of men (0.5 % of woman) have problems with colours. It would be a very useful feature to be able to change the colour theme e.g. to blue and yellow, or pink and orange.

Sorry for this absolutly "newbie" issue request, i have no experience with github. I just want to draw attention to this misery.

Greetings,
Daniel.
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> I am colour blind, exactly i have deuteranopia, which makes it for me impossible to use this wonderful tool because i can not see a difference between red and green (especially the dark tones).

Around 12 % of men (0.5 % of woman) have problems with colours. It would be a very useful feature to be able to change the colour theme e.g. to blue and yellow, or pink and orange.

Already supported with Colour Blind Friendly mode in Dashboard > Settings >  Color-blind friendly

**Comment by gorhill** [comment]
> to blue and yellow, or pink and orange.

Are there cases of color-blindness where blue/yellow does not work?

**Comment by shakee77** [comment]
> 
> 
> > to blue and yellow, or pink and orange.
> 
> Are there cases of color-blindness where blue/yellow does not work?

Yes, very rare but people with blue/yellow have no problems with red/green, so thats not a problem.

Sorry for my bad, i will have fun now using uMatrix.
