### ISSUE TITLE
uMatrix deleting cookies with cookie deletion settings unchecked

### ISSUE THREAD

**Issue by living180** [uBlockOrigin/uMatrix-issues#140]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When logging in to the financial site https://investor.wealthscape.com/, multiple requests are made to `login.mystreetscape.com` which set third-party cookies.  Even though neither of uBlock's cookie-deletion options are checked (see first screenshot below), uMatrix always deletes six of the thirteen `mystreetscape.com` cookies after the last xhr request (second screenshot).  It is always the same ones, and I haven't been able to determine a characteristic which differentiates between the deleted ones and the preserved ones).

### A specific URL where the issue occurs

https://investor.wealthscape.com/access/investor-index.html?login

### Steps to Reproduce

The specific issue above cannot be reproduced without login information.  However, to reproduce a similar issue:

1. Open the uMatrix logger.
2. Visit https://addons.mozilla.org/en-US/firefox/.
3. Wait a few seconds.
4. Observe that the `_gat` cookie for `mozilla.org` gets deleted even though the delete cookies options are unchecked (see the third screenshot below).

### Ruleset

    https-strict: behind-the-scene false
    matrix-off: about-scheme true
    matrix-off: behind-the-scene true
    matrix-off: chrome-extension-scheme true
    matrix-off: chrome-scheme true
    matrix-off: moz-extension-scheme true
    matrix-off: opera-scheme true
    matrix-off: vivaldi-scheme true
    matrix-off: wyciwyg-scheme true
    noscript-spoof: * true
    referrer-spoof: * true
    referrer-spoof: behind-the-scene false
    * * * block
    * * css allow
    * * frame block
    * * image allow
    * 1st-party * allow
    * 1st-party frame allow
    wealthscape.com mystreetscape.com cookie allow
    wealthscape.com mystreetscape.com script allow
    wealthscape.com mystreetscape.com xhr allow

### Supporting evidence

![image](https://user-images.githubusercontent.com/425650/56918251-306c8d00-6ac6-11e9-83ce-d5c576ff2057.png)

![image](https://user-images.githubusercontent.com/425650/56918767-90affe80-6ac7-11e9-8485-92eb38653386.png)

![image](https://user-images.githubusercontent.com/425650/56919833-4714e300-6aca-11e9-9374-f9c558427972.png)

### Your environment

* uMatrix version:  1.3.16
* Browser Name and version:  Firefox 66.0.3
* Operating System and version:  Gentoo Linux

**Comment by uBlock-user** [comment]
> Wait a few seconds.

I waited 10 minutes on a stopwatch timer and nothing. 

You have _Clear browser cache every x minutes activated_. Remove that.

**Comment by gwarser** [comment]
When uMatrix removes cookies log entries are red with uppercase "COOKIE". These blue entries are just logging what happened with cookies. They may be just expired  somehow (session) or deleted by something else.

**Comment by living180** [comment]
Thanks @gwarser - I was able to confirm via other means that with uMatrix disabled the cookies still get removed at the same point.  I was just confused because I didn't realize it was logging cookie actions initiated by code other than itself.  Apologies for the noise.
