### ISSUE TITLE
Update assets doesn't work

### ISSUE THREAD

**Issue by beerisgood** [uBlockOrigin/uMatrix-issues#142]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Updating the assets and/ or own rulesets doesn't work and say every asset+ruleset is outdated

### A specific URL where the issue occurs

moz-extension://bfa9408d-3dc6-4c0d-875b-00a92bc87bbd/dashboard.html#hosts-files

### Steps to Reproduce

1. Go to 
moz-extension://bfa9408d-3dc6-4c0d-875b-00a92bc87bbd/dashboard.html#hosts-files
2. click on update button
3. see that every asset/ ruleset display a yellow icon with "outdated" text

### Ruleset

hpHosts’ Ad and tracking servers
Malware Domain List
Malware domains
MVPS HOSTS
​​​​​​​​​Peter Lowe’s Ad and tracking server list
Ruleset recipes for English websites
​​​​​https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.3 64Bit
* Operating System and version: Windows 10 1809

**Comment by gorhill** [comment]
Please go through the steps you did not check.

**Comment by uBlock-user** [comment]
@beerisgood Also post your ruleset and screenshot of the logger alongwith.

**Comment by beerisgood** [comment]
@gorhill updated my post

**Comment by gorhill** [comment]
The logger shows you the issue, you have a block rule causing this.

**Comment by beerisgood** [comment]
Yes but why i can open the sites in Firefox itself? In the same Firefox profile, without any changes?
Only uMatrix can't open the domains

**Comment by uBlock-user** [comment]
Add `moz-extension-scheme * xhr allow` and report back if it works for you.

**Comment by gorhill** [comment]
What does the logger say when you open in Firefox itself? The logger shows you why, it woill show you the origin is different, hence that yield to the answer: you probably removed the [built-in rule here](https://github.com/gorhill/uMatrix/blob/9494da719540214c9695c715ce2e3dd23f5b0861/src/js/httpsb.js#L34).

**Comment by beerisgood** [comment]
> 
> 
> Add `moz-extension-scheme * xhr allow` and report back if it works for you.

Thanks that works!

@gorhill i never change that and don't know how to do that

But problem is now solved.
Thanks!

**Comment by gorhill** [comment]
> i never change that and don't know how to do that

You may have changed it inadvertently through the popup panel while on a uMatrix's dashboard page:

![a](https://user-images.githubusercontent.com/585534/57153209-ad885280-6da3-11e9-9adb-fd62e7f545a6.png)

**Comment by beerisgood** [comment]
Ah. Yes i do block all stuff on external sites and allow only CSS+images on 1st party.
I don't know this affect uMatrix itself too. Maybe exclude it so the addon doesn't break - like for me?

**Comment by uBlock-user** [comment]
> Maybe exclude it so the addon doesn't break - like for me?

It's already excluded as per https://github.com/uBlockOrigin/uMatrix-issues/issues/142#issuecomment-489161592
