### ISSUE TITLE
Binance Captcha not solvable with uMatrix installed

### ISSUE THREAD

**Issue by flatpocket** [uBlockOrigin/uMatrix-issues#143]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Its not possible to solve the puzzle captcha on binance.com with uMatrix installed. Even If I deactivate all uMatrix rules and delete my cache, I cant solve the puzzle captcha when Im trying to log in. I tried this with Firefox and Opera, same problem with both browsers. I also installed a win 10 VM with a fresh firefox and uMatrix and I still cant solve it.

After I turn off uMatrix in the extensions tab in Firefox the puzzle captcha works fine.

### A specific URL where the issue occurs

https://www.binance.com/login.html

### Steps to Reproduce

1. create a binance account
2. try to log in

### Your environment

* uMatrix version: 1.3.16 (firefox) 1.3.0 (Opera)
* Browser Name and version: Firefox 66.03 and Opera 
* Operating System and version: win10 1809 x64

**Comment by gwarser** [comment]
>Even If I deactivate all uMatrix rules and delete my cache

Even [Per-scope-switches](https://github.com/uBlockOrigin/uMatrix-issues/wiki/Per-scope-switches)?

**Comment by gorhill** [comment]
Here is for proven issue. Support is <https://www.reddit.com/r/uMatrix/>.
