### ISSUE TITLE
uMatrix disabled on FF because of certificate expiration?

### ISSUE THREAD

**Issue by kortschak** [uBlockOrigin/uMatrix-issues#144]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

It appears that Firefox have changed a policy that allows uMatrix and uBlockOrigin to run. On FF66.0.3 uMatrix, uBlockOrigin and a number of other plugins are now disabled.

![firefox-drops-uBlock_uMatrix](https://user-images.githubusercontent.com/275221/57180111-a311aa00-6ec4-11e9-9919-38139447845c.png)

### A specific URL where the issue occurs

This is not URL-specific.

### Steps to Reproduce

This appears to be a certificate problem since setting `xpinstall.signatures.required` to `false` reverts it. This is not a long term solution though.

Edit: This is the problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

### Ruleset

N/A

### Supporting evidence

Screen shot above.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: FF66.0.3
* Operating System and version: Ubuntu 16.04

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/558

**Comment by uBlock-user** [comment]
Firefox update fix -- https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/
