### ISSUE TITLE
Installing add-on complains that "it appears to be corrupt"

### ISSUE THREAD

**Issue by dead10ck** [uBlockOrigin/uMatrix-issues#145]
The add-on recently stopped working for me on Firefox for Android; the add-on page said something about the signature being invalid, although I can't get the exact error message any more. I tried reinstalling the add-on, but when I go to install it fresh, after clicking the install button, a dialog pops up that says that it appears to be corrupt.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/144>.
