### ISSUE TITLE
[feature] Binding multiple domain as 1st-party

### ISSUE THREAD

**Issue by chrisyue** [uBlockOrigin/uMatrix-issues#15]
### Prerequisites

* [x] Did you perform a cursory search of the issue tracker?
* Can you reproduce the problem when...
    * [ ] uMatrix is the only extension?
    * [ ] uMatrix with default lists/settings?
    * [ ] using a new, unmodified browser profile?
* [x] Are you running the latest version?
* [x] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

Great addon! More easy use and UI-friendly than NoScript.

I'd like to request a new feature: Binding multiple domains as "1st-party", as many company owning multiple sites, those sites may request each other as CDN, or fetching logged user info. So we could binding them together and benefit from the "1st-party" rule.

before

taobao.com aliyun.com * *
taobao.com alicdn.com * *
taobao.com alibaba.com * *
aliyun.com taobao.com * *
alibaba.com taobao.com * *
...

after

bind: taobao.com alicdn.com aliyun.com alibaba.com

### Your environment

**Comment by gorhill** [comment]
That sort of issue is best taken care of with ruleset recipes.

**Comment by chrisyue** [comment]
@gorhill thanks for the reply, and sorry for the sooooo late reply...

After trying the ruleset recipes, I think it's different thing:

recipes aim to community-contribution, my idea aim to shorten the rules for some special sites.

for alibaba as example. it owns many sites like alibaba.com, aliyun.com, taobao.com, these sites always share some resources so I have to write rulesets like these:

```
taobao.com aliyun.com * allow
taobao.com alibaba.com * allow
aliyun.com taobao.com * allow
aliyun.com alibaba.com * allow
alibaba.com taobao.com * allow
alibaba.com aliyun.com * allow
```

as you can see will write n! rules if a corp has n sites which share resources (in my country there's a lot of sites like this: 126.com/127.net/163.com, weibo.com/sina.com/sina.com.cn ...)

or, for convenience:

```
* aliyun.com * allow
* taobao.com * allow
* alibaba.com * allow
```

however the second rulesets is not ideal for the other sites not owned by alibaba, it also sells ads in other sites, and I don't want these ads to be loaded too

so I think it's better has some simple rule formats which could describe the situation that: `alibaba.com = aliyun.com = taobao.com`
