### ISSUE TITLE
uMatrix doesn't show https://thepersistenceofchaos.com/ correctly

### ISSUE THREAD

**Issue by RedirectCleaner** [uBlockOrigin/uMatrix-issues#152]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
Opening the URL https://thepersistenceofchaos.com/ inside the browser with uMatrix enabled shows no video at all

### A specific URL where the issue occurs
https://thepersistenceofchaos.com/

### Steps to Reproduce

1. enable uMatrix with default settings
2. open URL https://thepersistenceofchaos.com/
3. Disable uMatrix for the URL 

### Ruleset
default ruleset, with uMatrix disabled (for the current page)
Spoof referer header - disabled
Spoof noscript tags - disabled

### Fix
disabling he uMatrix addon and reloading the site shows the video

### Supporting evidence
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://client-event-reporter.twitch.tv/v1/stats. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://usher.ttvnw.net/api/channel/hls/persistencechaos.m3u8?allow_source=true&baking_bread=true&baking_brownies=true&baking_brownies_timeout=1050&fast_bread=true&p=6859160&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&rtqos=control&sig=1f570b87b7ff9b514598677e82fab9e220aafa35&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22persistencechaos%22%2C%22channel_id%22%3A432317355%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1557965160%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22_%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22server_ads%22%3Afalse%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3Anull%2C%22user_ip%22%3A%2262.178.200.226%22%2C%22version%22%3A2%7D&preferred_codecs=avc1&cdm=wv. (Reason: CORS request did not succeed).[Learn More]
HTTP Response Error: TypeError TypeError: NetworkError when attempting to fetch resource.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.5
* Operating System and version: Linux

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uMatrix-issues/wiki/Per-scope-switches

You didn't disable _Forbid Web Workers_ switch.

**Comment by uBlock-user** [comment]
Also https://github.com/gorhill/uMatrix#regarding-broken-sites
