### ISSUE TITLE
Consider classifying "filter: url()" as css

### ISSUE THREAD

**Issue by girst** [uBlockOrigin/uMatrix-issues#153]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

CSS supports externally loaded SVG filters; uMatrix currently classifies those requests as "other" in Firefox and "image" in chromium. 

Problem is, they have a peculiar failiure mode in Firefox: If the URL fails to load (e.g. is blocked by uMatrix), the element is not displayed at all. ([Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1105145))

**I propose to reclassify them as "css", like fonts already are**, for both Firefox and Chromium. Classifying these as "image" (as is current behaviour in chromium) doesn't seem right to me either, because it's a filter, not an image.

### A specific URL where the issue occurs

https://web.archive.org/web/20190505102743/http://n-gate.com/

### Steps to Reproduce

1. use Firefox
2. disable "other" for web.archive.org
3. navigate to [the URL given](https://web.archive.org/web/20190505102743/http://n-gate.com/)
4. notice that the whole page (the filter is applied to `<body>`) is blank.

### Ruleset

```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
archive.org web.archive.org other block
```

### Supporting evidence

Firefox: https://imgur.com/yuyJnrC.png

Chromium: https://imgur.com/qod7WzT.png

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: firefox-66.0.4-1.fc28
* Operating System and version: Fedora 28 (an ephemeral VM)

**Comment by gwarser** [comment]
>I propose to reclassify them as "css", like fonts already are

But how? This is xml file and Firefox says "other".

![image](https://user-images.githubusercontent.com/886325/57895442-dd2b6600-784b-11e9-93d0-ba696bbfe9ec.png)

**Comment by girst** [comment]
Hmm, I may have not thought this through completely. Thought process was 
that since umatrix already lumps together some types of requests, 
pulling this one out of other should be easy.

**Comment by gorhill** [comment]
Firefox tells uMatrix the resource is `other`. Event then, I wouldn't categorize `svg` resources as `css`.
