### ISSUE TITLE
No "Edit" button on "My rules" tab in "Temporary rules".

### ISSUE THREAD

**Issue by hawran** [uBlockOrigin/uMatrix-issues#154]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
I've wanted to edit (insert new actually) rules.
However, there is no "Edit" button on "My rules" tab in "Temporary rules".

_What am I missing?_

### A specific URL where the issue occurs
It does not depend on a URL.

### Steps to Reproduce
1. Go to uMatrix's settings.
2. Go to "My rules" tab.
3. No "Edit" button.

Additionally, there are a couple of sites mentioning 'Edit" button on internet:
https://github.com/gorhill/uMatrix/wiki/Examples-of-useful-rulesets
https://github.com/kristerkari/umatrix-recipes#how-to-whitelist-a-website
https://www.dedoimedo.com/computers/umatrix-guide.html
https://www.ghacks.net/2017/11/28/a-umatrix-guide-for-firefox/#comment-4295386

### Ruleset
It does not depend on rulesets.

### Supporting evidence
![Screenshot_2019-05-19_17-53-38](https://user-images.githubusercontent.com/25924718/57985084-06720f00-7a63-11e9-8362-8449f0588f20.png)

### Your environment
* uMatrix version:
```
Extensions
----------
Name: uMatrix
Version: 1.3.16
Enabled: true
ID: uMatrix@raymondhill.net
```
* Browser Name and version:
```
Application Basics
------------------
Name: Firefox
Version: 66.0.5
Build ID: 20190508090509
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
```
* Operating System and version:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by uBlock-user** [comment]
> I've wanted to edit (insert new actually) rules.
However, there is no "Edit" button on "My rules" tab in "Temporary rules".

What am I missing?

Simply click anywhere inside "Temporary rules" and you will be able to edit/remove/add rules.

**Comment by uBlock-user** [comment]
> Additionally, there are a couple of sites mentioning 'Edit" button on internet:

Will rectify that in the wiki.

**Comment by hawran** [comment]
> > I've wanted to edit (insert new actually) rules.
> > However, there is no "Edit" button on "My rules" tab in "Temporary rules".
> > What am I missing?
> 
> Simply click anywhere inside "Temporary rules" and you will be able to edit/remove/add rules.

Oh, I see.
OK, thank you.
