### ISSUE TITLE
Block CSS Exfil attack

### ISSUE THREAD

**Issue by chiraag-nataraj** [uBlockOrigin/uMatrix-issues#157]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

It would be nice to defend against the class of attacks detailed here: https://www.mike-gualtieri.com/posts/stealing-data-with-css-attack-and-defense

### A specific URL where the issue occurs

https://www.mike-gualtieri.com/css-exfil-vulnerability-tester

### Steps to Reproduce

1. Enable 1st party CSS globally, script on www.mike-gualtieri.com (needed for the tester) (in my ruleset below, I disabled everything globally and only allowed 1st-party CSS in the scope of the website, but the result is very much the same).
2. Note that tests 1 and 3 fail (2 and 4 should succeed since css from goeris.com is blocked).

Note that this _could_ be foiled by simply blocking all CSS by default, but it would be nice not to have to do that.

### Ruleset

```
https-strict: * true
https-strict: behind-the-scene true
matrix-off: about-scheme false
matrix-off: behind-the-scene false
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: wyciwyg-scheme true
no-workers: * true
noscript-spoof: * true
* * * block
www.mike-gualtieri.com 1st-party css allow
www.mike-gualtieri.com www.mike-gualtieri.com script allow
```

### Supporting evidence

![2019-05-22-093803_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/58164465-6cce7b80-7c75-11e9-9977-fbb9b783a5c2.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.5
* Operating System and version: Debian sid/experimental

**Comment by gorhill** [comment]
Declined, because there is nothing to do beside blocking CSS from untrusted sources, which you can already do with uMatrix.

**Comment by chiraag-nataraj** [comment]
@gorhill So I suppose CSS sanitation (as suggested by the page I linked to) is out of the question for uMatrix, even as an optional toggle? Fair enough.

**Comment by gorhill** [comment]
What that extension does is too far from uMatrix's core purpose, it's a DOM-only code which does a whole lot of work, including fetching CSS resources remotely, etc. I consider this feature creep, and best is that you just use that extension if you think it helps you -- there is no point for me to embark on yet another feature for uMatrix which I barely have the time to work on at this point.
