### ISSUE TITLE
uMatrix does not block javascript using Opera web browser

### ISSUE THREAD

**Issue by Flow-chart** [uBlockOrigin/uMatrix-issues#158]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When following any link, the next page will not enforce the settings described in uMatrix.
A refresh of the page is required to properly enforce the uMatrix ruleset.
I noticed this when signing up for a website, and a google captcha loaded out of nowhere
without having been admitted in the settings yet.

This seems like a serious security issue.

### A specific URL where the issue occurs
https://www.google.com/search?q=do+i+have+javascript+enabled+test
https://www.google.com/search?q=do+i+have+javascript+enabled+test+geenee

The below links seem to work properly when accessed through this github page,
but when accessing these sites from google the javascript rules fail. 
https://geenee.com/eng/geenee-web-site/check-your-javascript/
https://www.whatismybrowser.com/detect/is-javascript-enabled

### Steps to Reproduce

1. Simply click the link and view your results.

It will show javascript as enabled unless you refresh the page.

### Ruleset

Javascripts disabled on every site, unless stated otherwise in the uMatrix rules.

### Supporting evidence
https://imgur.com/a/LQxK30q

### Your environment

* uMatrix version: 1.3.0
* Browser Name and version: Opera 58.0.3135.118
* Operating System and version: Windows 7 x64
* Tested on Firefox as well, where it works as it should.

**Comment by uBlock-user** [comment]
> but when accessing these sites from google the javascript rules fail.

https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/
