### ISSUE TITLE
Referrer header getting spoofed even after the switch is disabled since 1.3.17rc1

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uMatrix-issues#159]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Same as the title

### A specific URL where the issue occurs

`https://animehub.ac/watch/one-punch-man-season-2-sub.54747?ep=154986&s=oserver`

### Steps to Reproduce

Go to `https://animehub.ac/watch/one-punch-man-season-2-sub.54747?ep=154986&s=oserver`

Click play and be met with **This video file cannot be played. (Error Code: 232011)**

_Disable Spoof Referrer_ switch and refresh the page again. Click play again and be met with that same error, only this time the switch is disabled and still the video won't play.

### Ruleset

```
https-strict: * true
no-workers: * true
noscript-spoof: * true
referrer-spoof: * true
* * * block
* * css allow
* * image allow
* 1st-party * allow
animehub.ac cdn.jwplayer.com script allow
animehub.ac embed.streamx.live frame allow
animehub.ac embed.streamx.live script allow
animehub.ac embed.streamx.live xhr allow
animehub.ac ssl.p.jwpcdn.com script allow
animehub.ac static.animecdn.xyz script allow
* openstream.io media allow
* openstream.io xhr allow
```

### Supporting evidence

![](https://i.gyazo.com/b7f6bf97dbd65fe4c6bb6ccf61b1c353.png)

### Your environment

* uMatrix version: 1.3.17.102
* Browser Name and version: Chromium 76
* Operating System and version: Win 10

**I cannot reproduce this issue on [1.3.17rc0](https://github.com/gorhill/uMatrix/releases/tag/1.3.17rc0)**

**Comment by gorhill** [comment]
I copied your ruleset and the site is kind of broken on my side, I have only a player area with a spinning wheel in it, so surely I am missing some other rules?

**Comment by gwarser** [comment]
I can reproduce in Version 74.0.3729.169 (Official Build) (64-bit)
And it works after adding: `referrer-spoof: embed.streamx.live false`

>the site is kind of broken on my side, I have only a player area with a spinning wheel

Sometimes see this too. Reloading helps.

**Comment by gorhill** [comment]
> Sometimes see this too.

Actually it was my mistake, I pasted the ruleset to completely replace mine, but I sleep-walked into disabling `no-worker` switch as I thought it was my own rule. I can reproduce now.

**Comment by uBlock-user** [comment]
> And it works after adding: referrer-spoof: embed.streamx.live false (iframe)

good catch, but I don't need to add that rule if I downgrde back to `1.3.17rc0` so I think that commit has made uMatrix to consider `embed.streamx.live` the parent frame instead of `animehub.ac`
