### ISSUE TITLE
Minor code cleaning

### ISSUE THREAD

**Issue by rhendric** [uBlockOrigin/uMatrix-issues#16]
I've been hacking on uMatrix for my own purposes, and in the process I've found some bits of code that I'm 99% sure are useless. I'd like to submit a PR to remove them, but you seem to have forbidden that, which... well, your loss, I guess? But just in case you would find this particular contribution valuable, here's a link to my cleaning commits if you want to merge these yourself: https://github.com/gorhill/uMatrix/compare/master...rhendric:cleaning

**Comment by rhendric** [comment]
Oh, and there's one commit in there that I think is a bug fix, too: you used `normalURL` in a place where I think you meant `pageUrl`, although I haven't gone to all the trouble of finding a way to exercise that code path and observe the practical difference.

**Comment by uBlock-user** [comment]
> but you seem to have forbidden that

It's only available to those contributed in the past. 

@gorhill

**Comment by uBlock-user** [comment]
Closing this in favour of the mergable link posted by the OP. Gorhill let me know if you want it to be kept opened.

**Comment by gorhill** [comment]
@rhendric I opened the repo in so that you can submit a PR with your changes -- which I just reviewed. Thank you for contributing and sorry for the delay.

**Comment by rhendric** [comment]
@gorhill, I'm still unable to create a PR. Instead of a button, I see, ‘An owner of this repository has limited the ability to open a pull request to users that have contributed to this repository in the past.’.

**Comment by uBlock-user** [comment]
That was opened at that time, it's been 17 hours now since, must have got locked again as you responded now.

**Comment by gorhill** [comment]
Ok, it's opened again.
