### ISSUE TITLE
My rules are not possible

### ISSUE THREAD

**Issue by Saadi1988** [uBlockOrigin/uMatrix-issues#163]
i have a blog in www.blog.ir . i want to allow all scripts in https://blog.ir/panel/... from both (blog.ir/...... .js) and (subdomain.othersites.com/...... js) scripts.

but i want block scripts in all subdomains {*.blog.ir} blogs . both scripts of (blog.ir/...... .js) and (subdomain.othersites.com/...... js)

i have tested many commands. but it doesn't work true. what codes i should enter in "My Rules"? Plz help me. thanks.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 68beta
* Operating System and version: Windows 10 Pro 1903 x64

**Comment by uBlock-user** [comment]
Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/).

**Comment by Saadi1988** [comment]
Hi,
I want something like this:
![Untitled-1](https://user-images.githubusercontent.com/42292489/72461837-0807f880-37e5-11ea-814b-70a18476964a.gif)

**Comment by Saadi1988** [comment]
Why did I apply for such a ability? Because I manage a blog in a blog service and log into its control panel every day. But I don't want when i go to the blogs of others (or even my own blog) scripts run.

**Comment by gorhill** [comment]
What you are requesting would be a duplicate of <https://github.com/gorhill/uMatrix/issues/584>. I will reopen the original issue.
