### ISSUE TITLE
Make it possible to block prefetch, prerender, preconnect, dns-prefetch, icon

### ISSUE THREAD

**Issue by FlorianSteenbuck** [uBlockOrigin/uMatrix-issues#166]
### Prerequisites
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
This is a feature request. Make it possible to block/allow:
```html
<link rel="prefetch"/>
<link rel="prerender"/>
<link rel="preconnect"/>
<link rel="dns-prefetch"/>
<link rel="icon"/>
```

### A specific URL where the issue occurs

Irrelevant to the issue.

### Steps to Reproduce

Irrelevant to the issue.

### Ruleset

Irrelevant to the issue.

### Supporting evidence

Irrelevant to the issue.

**Comment by gwarser** [comment]
This is already blocked by default, as much as API allows.

**Comment by uBlock-user** [comment]
Chromium -  https://bugs.chromium.org/p/chromium/issues/detail?id=786038

**Comment by identicalsnowflake** [comment]
@gwarser 

It's not just blocked by default, it's blocked entirely, and changing the browser settings to enable prefetching doesn't work as this extension overwrites the setting. I can't find anything in the uMatrix settings to make it stop doing this.

I think it would make sense to expose prefetching settings in the uMatrix preferences, as enabling prefetching dramatically reduces the time it takes the browser to navigate around pages.

**Comment by gorhill** [comment]
> dramatically reduces

Only actual profiling results are considered.
