### ISSUE TITLE
[feature request] Block autplay

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uMatrix-issues#167]
Please consider if possible (either in uMatrix or uBO) adding efficient blocking of autoplay as explained in this article:

https://pineight.com/cssdemos/autoplay-methods/

**Comment by gorhill** [comment]
Declined.

**Comment by gwarser** [comment]
Firefox 69:

![image](https://user-images.githubusercontent.com/886325/60093052-b7e21f80-9748-11e9-8853-b22060af6d99.png)

**Comment by emanruse** [comment]
> Declined.

For what reason please?

**Comment by emanruse** [comment]
> Firefox 69:
> 
> ![image](https://user-images.githubusercontent.com/886325/60093052-b7e21f80-9748-11e9-8853-b22060af6d99.png)

Have you tested this with all the examples given on the link I shared?

**Comment by uBlock-user** [comment]
Wait for gorhill to deploy Feature-Policy after which you will be able to block autoplay via https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay

**Comment by emanruse** [comment]
> Wait for gorhill to deploy Feature-Policy after which you will be able to block autoplay via https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay

I am the one who requested that a year ago :)
But I am not sure if it will be able to block all examples of autoplay.

**Comment by uBlock-user** [comment]
> if it will be able to block all examples of autoplay

> The autoplay attribute on <audio> and <video> elements will be ignored

It's like CSP, so it will work.

**Comment by gwarser** [comment]
> Have you tested this with all the examples given on the link I shared?

By clicking "Start" and "Next" all examples do not autoplay on my setup. Videos blocked by Firefox, GIF by uBO no-large-media, "CSS steps" does not work at all, others by no-scripting.

**Comment by uBlock-user** [comment]
The only case where Firefox's setting doesn't work is where autoplay is enabled via Feature-Policy inside an iframe like this --

`<iframe allow="autoplay,fullscreen,encrypted-media"</iframe>`

**Comment by emanruse** [comment]
In (ungoogled-)chromium:

- with JS blocked (in browser as well as in uMatrix and uBO)
- chrome://flags/#autoplay-policy set to "Document user activation is required"
- everything in chrome://settings/content set to Blocked

most of the examples do auto-play.

**Comment by uBlock-user** [comment]
Another set of tests - https://videojs.github.io/autoplay-tests/
