### ISSUE TITLE
The page establishes connections that should be blocked.

### ISSUE THREAD

**Issue by Hifexar** [uBlockOrigin/uMatrix-issues#168]
### Prerequisites

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Chrome performs requests that should be blocked by Umatrix 1.3.17.104

How to reproduce the bug:
1. Go to the page https://www.dns-shop.ru/product/74532eb045c73120/mys-provodnaa-logitech-b100-cernyj/#faq
2. Umatrix screenshots 
1) https://gyazo.com/3b8548149b982840c68bbd18b54988ae
2) https://gyazo.com/215a851e6fafc0f8fcaef16e563e871e
3. From filters umatrix "hpHosts’ Ad and tracking servers​​​​​"https://gyazo.com/fbdcc65596bfa13aaed231340e368129
4. Refresh the page and see what requests Chrome sends to the network: https://gyazo.com/c2b1500b02689970c46257da6fe06fd3
5. And we see that there are requests for: bh.contextweb.com - It does not exist in the screenshots of their paragraph 2
6. eu-sonar.sociomantic.com 5922505.fls.doubleclick.net top-fwz1.mail.ru These should be banned!!!
7. And the last look firewall https://gyazo.com/f7b49a547681d21ad71f4692f76d854a Here you can see that there were connections to ip addresses eu-sonar.sociomantic.com and bh.contextweb.com

Subtotal:
1. bh.contextweb.com it IS NOT SHOWN in umatrix gui on the page, it is blocked in "hpHosts’ Ad and tracking servers", but connections to this node still occur!!! And it does not appear in the umatrix gui on the page.
2. For example, eu-sonar.sociomantic.com is in umatrix gui on the page, in it is blocked "hpHosts’ Ad and tracking servers", but connections to this node still occur!!!

### A specific URL where the issue occurs

https://www.dns-shop.ru/product/74532eb045c73120/mys-provodnaa-logitech-b100-cernyj/#faq
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

1. Go to the page https://www.dns-shop.ru/product/74532eb045c73120/mys-provodnaa-logitech-b100-cernyj/#faq
2. Umatrix screenshots 
1) https://gyazo.com/3b8548149b982840c68bbd18b54988ae
2) https://gyazo.com/215a851e6fafc0f8fcaef16e563e871e
3. From filters umatrix "hpHosts’ Ad and tracking servers​​​​​"https://gyazo.com/fbdcc65596bfa13aaed231340e368129
4. Refresh the page and see what requests Chrome sends to the network: https://gyazo.com/c2b1500b02689970c46257da6fe06fd3
5. And we see that there are requests for: bh.contextweb.com - It does not exist in the screenshots of their paragraph 2
6. eu-sonar.sociomantic.com 5922505.fls.doubleclick.net top-fwz1.mail.ru These should be banned!!!
7. And the last look firewall https://gyazo.com/f7b49a547681d21ad71f4692f76d854a Here you can see that there were connections to ip addresses eu-sonar.sociomantic.com and bh.contextweb.com

### Ruleset

On screenshots.

### Your environment

* uMatrix version: 1.3.17.104
* Browser Name and version:  Chrome 58.0.3029.96 (64-bit)
* Operating System and version: Win7 pro sp1

**Comment by Hifexar** [comment]
+ I try in Iridium 2019.04 64bit   all the same

**Comment by Hifexar** [comment]
chat.dns-shop.ru   - also does not appear in umatrix gui on the page
Only:
dns-shop.ru
as.dns-shop.ru
c.dns-shop.ru 
www.dns-shop.ru

**Comment by Hifexar** [comment]
To detect the connection I used Proxifier SE v3.42 logs and logs Windows Firewall Control 4.9.6.0(GUI for the firewall of Winodws)

I would do and give with Wireshark, but connections go to VPN and it does not see them.

**Comment by gwarser** [comment]
First of all - what uMatrix logger shows? What you see in browser console?

**Comment by Hifexar** [comment]
1. uMatrix logger shows for example:
https://gyazo.com/4f8e418487fee1adf5d59a14747d829b
bh.contextweb.com in the logs umatrix no

Don't know how you got accepted long logs lay out


2. Proxifier logs:
https://gyazo.com/5202502ed24baf0ef0196d68ac8bb01e

3. browser console:
https://gyazo.com/df70686d3046c8f1f923350ec67467a0

net::ERR_BLOCKED_BY_CLIENT but connections to servers are still established!!!

**Comment by gwarser** [comment]
I see lot of prefetch and preconnect in the source - there is no way to block most of these in Chrome.

**Comment by gorhill** [comment]
> connections to servers are still established

That's what Chrome and Chromium-based browsers do -- they disregard the disabling of pre-connecting/pre-fetching if the site asks to through using `link` with `rel` set to `preconnect` or `preload`.

**Comment by Hifexar** [comment]
I did not really understand why then connections are not established, for example, with? 
GET https://media.flixsyndication.net/minisite/ssl/js/loader.js net::ERR_BLOCKED_BY_CLIENT
GET https://js-agent.newrelic.com/nr-1044.min.js net::ERR_BLOCKED_BY_CLIENT

And why the connection is established with bh.contextweb.com, but in the browser console and umatrix logs this is not?

there is no way to block most of these in Chrome.  - Very bad(((

**Comment by gorhill** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=786038

**Comment by gwarser** [comment]
Note from uBO wiki about "Disable pre-fetching" option:

>IMPORTANT NOTE:

>On Chromium 51 and above (including browsers based on Chromium 51 and above), this setting is completely unreliable, as it does not cause DNS lookups, preconnections and prefetches to be reliably blocked, because Chromium allows web pages to override that user setting. For details, see:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#important-note

**Comment by Hifexar** [comment]
gorhill, gwarser - thanks!

Only today I noticed that chrome establishes many connections with servers, even if they are blocked in umatrix settings. Very upset(((

**Comment by gorhill** [comment]
> there is no way to block most of these in Chrome

In the big picture, Chromium (on which Google Chrome is based) is what Google decides it will be, and the business model of Google is incompatible with being uncompromisingly pro-users. So this sort of issues is not unexpected.

**Comment by Hifexar** [comment]
And where does the connection to the bh.contextweb.com ?

**Comment by gorhill** [comment]
I don't understand your question. Navigate to `view-source:https://www.dns-shop.ru/product/74532eb045c73120/mys-provodnaa-logitech-b100-cernyj/#faq`, then search for `preconnect`, `preload`.

**Comment by gwarser** [comment]
Preconnected but never used?

**Comment by Hifexar** [comment]
I mean, when the page reloads, the connection is made to bh.contextweb.com.
But neither in umatrix logs, nor in the console of the browser it is not present. 

As such a connection, hiding from the logs?

**Comment by gorhill** [comment]
uMatrix is not notified that these preconnections are made, this happens inside the browser without going through extensions API.

**Comment by Hifexar** [comment]
"then search for preconnect, preload."

Please tell me where to watch it? I didn't understand.

**Comment by gwarser** [comment]
Right click on page, select "view page source", ctrl+f and search for `bh.c`, you wuill find: `<link href="//bh.contextweb.com/bh/" rel="preconnect">`

Probably connection happens on TCP level, but nothing is send by HTTP.

**Comment by Hifexar** [comment]
gwarser, ок, thanks!

"but nothing is send by HTTP"
But most likely on the server IP from which there was a connection is logged or there are counters of attendance.

**Comment by Hifexar** [comment]
Are there any ways to spoil all the words of "preconnect" when loading doc? For example, substitute for "prcnt"?

**Comment by gorhill** [comment]
I suggest you just use Firefox, disabling pre-fetching works as expected.

**Comment by Hifexar** [comment]
gorhill, thank you, but the firebox is not suitable, the usability is lower for me unfortunately. I have already tried several times to switch to it, but could not stand it ((( So the only option so far for me is any chromium with cut call home.
