### ISSUE TITLE
Issue with subtiltes on Crunchyroll 

### ISSUE THREAD

**Issue by rollthecixe** [uBlockOrigin/uMatrix-issues#173]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When Umatrix is used in Crunchyroll the subtiles wont appear on the video. 
The subtitle won't appear even if Umatrix is turned off for the site. 
Also, the logger states the Subtiles are being loaded in, but it never shows up.  
"
08:52:46 | static.crunchyroll.com |   | xhr | https://static.crunchyroll.com/vilos/libass/both/subtitles-octopus-worker.js.mem |  
-- | -- | -- | -- | -- | --
08:52:46 | static.crunchyroll.com |   | xhr | https://static.crunchyroll.com/vilos/libass/both/subtitles-octopus-worker.wasm |  
08:52:46 | static.crunchyroll.com |   | xhr | https://static.crunchyroll.com/vilos/libass/both/subtitles-octopus-worker.data |  
08:52:46 | www.crunchyroll.com |   | script | https://static.crunchyroll.com/vilos/libass/both/subtitles-octopus-worker.js |  
08:52:46 | www.crunchyroll.com |   | worker | https://static.crunchyroll.com/vilos/libass/both/subtitles-octopus-worker.js
"

### A specific URL where the issue occurs

https://www.crunchyroll.com/
{random anime}
https://www.crunchyroll.com/to-the-abandoned-sacred-beasts/episode-1-untitled-786826
### Steps to Reproduce

1. Go to Crunchyroll.com  
2. Select any anime to stream 
3. Bam! no subtitles. 

### Ruleset

noscript-spoof: www.crunchyroll.com false
referrer-spoof: www.crunchyroll.com false
https-strict: www.crunchyroll.com false

www.crunchyroll.com akamaized.net * allow
www.crunchyroll.com akamaized.net frame allow
www.crunchyroll.com drmtoday.com * allow
www.crunchyroll.com drmtoday.com frame allow
www.crunchyroll.com etp-prod.com * allow
www.crunchyroll.com etp-prod.com frame allow
www.crunchyroll.com static.crunchyroll.com * allow
www.crunchyroll.com static.crunchyroll.com xhr allow
www.crunchyroll.com vrv.co * allow
www.crunchyroll.com vrv.co frame allow

### Supporting evidence

the evidence is just watching an anime, you will see what i am talking about
### Your environment

* uMatrix version: 1.3.17rc4
* Browser Name and version: FireFox (67.0.4) 64 bit
* Operating System and version: Manjaro Linux (Stable Branch) Up-to-date as of (07/13/2019)
* Extensions: Umatrix and MAL-Sync 
![Screenshot_2019-07-13_09-10-06](https://user-images.githubusercontent.com/52857269/61172104-09aee600-a54e-11e9-8b4d-47fc7c737e45.png)

**Comment by uBlock-user** [comment]
> https://www.crunchyroll.com/to-the-abandoned-sacred-beasts/episode-1-untitled-786826

Redirects to home page. Provide a specific link.

**Comment by uBlock-user** [comment]
> The subtitle won't appear even if Umatrix is turned off for the site.

Turned off how ? Disabled via browser ?

**Comment by gorhill** [comment]
Unable to reproduce, all worked fine with:

    crunchyroll.com akamaized.net * allow
    crunchyroll.com drmtoday.com * allow
    crunchyroll.com etp-prod.com * allow
    crunchyroll.com vrv.co * allow

> I used the logger to rule out that the issue is caused by my ruleset

The logger shows why it didn't work, `dl.v.vrv.co` is needed in the context of `static.crunchyroll.com`, so there was no ground to report an issue here.

Seriously, such invalid and time-wasting reports are really getting tiresome, to the point where I am actually entertaining archiving the project for good.

**Comment by uBlock-user** [comment]
@gorhill I can reproduce. Network inspector shows they're loaded fine, uMatrix is not blocking subtitles XHRs either, but as long as uMatrix is enabled, the subtiles won't appear.

**Comment by uBlock-user** [comment]
> The logger shows why it didn't work, dl.v.vrv.co is needed in the context of static.crunchyroll.com, so there was no ground to report an issue here.

So even after disabling uMatrix on crunchyroll won't work ?

**Comment by gorhill** [comment]
> So even after disabling uMatrix on crunchyroll won't work ?

I didn't make the statement that it does not work when uMatrix is "disabled", OP did, and it's also wrong.

**Comment by uBlock-user** [comment]
It doesn't work when I disable uMatrix with `www.crunchyroll.com` as the scope level instead of `crunchyroll.com`. I suppose that's by-design.

**Comment by gorhill** [comment]
Right, I had disabled in the `crunchyroll.com` context. So this was just the same issue, creating rules in the wrong context and blaming uMatrix.
