### ISSUE TITLE
Firefox Sync settings

### ISSUE THREAD

**Issue by TriMoon** [uBlockOrigin/uMatrix-issues#177]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Please make the settings save/restore using Firefox Sync.

### A specific URL where the issue occurs

Fresh installs

### Steps to Reproduce

1. Have Firefox Sync enabled.
2. Fresh install of uMatrix.
3. Change some setting(s) of uMatix, fe. enable "Enable cloud storage support".
4. Select "Sync now" in the Firefox Sync section.
5. Start a fresh Firefox Profile.
6. Login to Firefox Sync.
5. The uMatrix settings should be restored together with uMatrix.
The settings currently do **NOT** get restored...

### Ruleset

This is not about rule sets...

### Supporting evidence

Default behaviour of most extensions.

### Your environment

* uMatrix version: **1.3.16**
* Browser Name and version:
  - **Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 ID:20190729213839**
* Operating System and version: **Linux (Kubuntu 19.04)**

**Comment by uBlock-user** [comment]
> The uMatrix settings should be restored together with uMatrix.
The settings currently do NOT get restored...

By-design -- Open my Rules and do it manually.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/467

**Comment by TriMoon** [comment]
@uBlock-user WTF?
I **know** it is not supported at moment thats why i post this **REQUEST FOR IMPROVEMENT**

**Comment by uBlock-user** [comment]
It's about automation, which has been denied before. If you want to sync, do it manually.

**Comment by TriMoon** [comment]
> It's about automation, which has been denied before. If you want to sync, do it manually by clicking the export button in My Rules.. Cloud storage sync settings too but it's kept manually on purpose. So there's nothing to improve.

Again this issue is **not** about the rules using the cloud, but it is about the extension's general settings.
You can leave the rules auto-sync to manual that is something completely different from this issue...

**Comment by TriMoon** [comment]
So **re-open** this issue as it is **NOT related to rules**...

**Comment by uBlock-user** [comment]
> but it is about the extension's general settings.

I said it already, click on the Export button which will export ALL extension settings.

**Comment by TriMoon** [comment]
> > but it is about the extension's general settings.
> 
> I said it already, click on the Export button which will export ALL extension settings.

As i posted in OP, i want that data to be synced with Firefox Sync.

**Comment by TriMoon** [comment]
@uBlock-user can you: (as you are supposed to have doing from start)
1. Re-open this issue
2. Add the label "enhancement"
3. Remove the label "duplicate"

Thanks...

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/66

Unfortunately there's no documentation on Cloud Storage and according to that bug gorhill only implemented syncing for My Rules.

**Comment by TriMoon** [comment]
That issue is from 2015... that is 4 years ago, things have changed...

**Comment by uBlock-user** [comment]
> can you: (as you are supposed to have doing from start)

Re-open this issue
Add the label "enhancement"
Remove the label "duplicate"

This FR request has already been made twice, see https://github.com/gorhill/uMatrix/issues/236 which is became another duplcate of  https://github.com/gorhill/uMatrix/issues/66 along with yours.

**Comment by TriMoon** [comment]
@uBlock-user thank you for hiding stuff and making it more difficult for the developer to follow issues of interest, because of your personal fault of interpreting the issues...
You quoted nicely what was asked but did **NONE** of them bravo you are **fired**... :hear_no_evil:

**Comment by uBlock-user** [comment]
> thank you for hiding stuff and making it more difficult for the developer to follow issues of interest, because of your personal fault of interpreting the issues...

Everybody's expected to search for duplicates before opening them here. It's your fault that you didn't bother to search for duplicates and waste my time entertaining this issue.

**Comment by gorhill** [comment]
The reason auto-syncing is not supported is the same one spelled out in [uBO's documentation](https://github.com/gorhill/uBlock/wiki/Cloud-storage):

> Your uBlock Origin settings are precious, and in order to prevent any automated browser's syncing task to cause precious local data (or cloud data) to be mistakenly overwritten, the chosen solution in uBlock Origin is to _never ever_ export to/import from cloud storage without **the user expressly asking uBlock Origin to do so**.
