### ISSUE TITLE
webperformance.it blocked by default

### ISSUE THREAD

**Issue by carlocarradori** [uBlockOrigin/uMatrix-issues#182]
Hi there, today an umatrix user reported that our company website www.webperformance.it gets blocked by umatrix default list.

Is it possible to remove the url from the blocked sites? It is a corporate website, nothing spammy.

Thanks

Carlo 

### Prerequisites

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
Blocked by `hpHosts - Ad and Tracking servers` only, contact them.

**Comment by gwarser** [comment]
https://github.com/gorhill/uMatrix#warnings

> Regarding broken sites
> 
> uMatrix does not guarantee that sites will work fine: it is for advanced users who can figure how to un-break sites, because essentially uMatrix is a firewall which works in relaxed block-all/allow-exceptionally mode out of the box: it is not unexpected that sites will break.
> 
> So this means do not file issues to report broken sites when the sites are broken because uMatrix does its job as expected. I will close any such issue without further comment.
