### ISSUE TITLE
skype download page problem and possibly others

### ISSUE THREAD

**Issue by boistordu** [uBlockOrigin/uMatrix-issues#184]
### Prerequisites

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

no blue button to choose the version present on that page: https://www.skype.com/en/get-skype/ unless umatrix is completly disabled. So there are a script or something that is not showing up in the list of umatrix, or it could be the interaction with another webextension.

### A specific URL where the issue occurs

https://www.skype.com/en/get-skype/

### Supporting evidence

![skypeproblemumatrix](https://user-images.githubusercontent.com/9523075/63247347-5d4ed680-c254-11e9-8aa6-3736383f4866.jpg)
![skypeproblemumatrix2](https://user-images.githubusercontent.com/9523075/63247364-663fa800-c254-11e9-871e-e9775789c2ce.jpg)
![skypeproblemumatrix3](https://user-images.githubusercontent.com/9523075/63248047-08ac5b00-c256-11e9-9241-5f1c07a709ed.jpg)
![skypeproblemumatrix4](https://user-images.githubusercontent.com/9523075/63248060-11049600-c256-11e9-9fe1-0caa2400cf95.jpg)

### Your environment

* uMatrix version:1.3.16
* Browser Name and version: firefox68.0.2
* Operating System and version: windows 10 1903 pro

**Comment by gwarser** [comment]
I only need to allow scripts from skypeassets domain.

**Comment by boistordu** [comment]
Yes and I can't find the one that's the problem. Could it be the settings in firefox from privacytools?

**Comment by gorhill** [comment]
> Could it be

That's why you are asked to try uMatrix without other extensions and try uMatrix in a new profile. Please go through these steps, you can create a new profile easily from `about:profiles`.

**Comment by gorhill** [comment]
According to your error messages in console, it seems to be simply a case of reading through ["About "the page is still broken after I created all necessary rules""](https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22).

From now on, such issues will be closed as invalid immediately when submitter does not check **all** the boxes.

**Comment by boistordu** [comment]
sorry for that then. Thanks for the appointed ressources and the advices.
