### ISSUE TITLE
Unable to load up images on website

### ISSUE THREAD

**Issue by teamjin** [uBlockOrigin/uMatrix-issues#185]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

The URL below contains a page which should include a picture. uMatrix will not load up the picture. Allowing "all" for the scope still does not resolve this issue. Disabling uMatrix via uMatrix menu does not resolve this issue. Only disabling uMatrix via about:addons within firefox resolves this issue. This issue is small but it has bothered me for the longest time.
### A specific URL where the issue occurs
https://dbz.space/cards/1014971-goku-frieza-final-form-angel-miraculous-outcome

### Steps to Reproduce

1. Install uMatrix and enable
2. Go to above URL
3. Disable uMatrix via the uMatrix menu or allow "all".

### Ruleset

N/A
### Supporting evidence

<img width="1767" alt="1 of 2" src="https://user-images.githubusercontent.com/45741495/64133873-33a7ba80-cdd1-11e9-8e97-cf799399f30e.png">
<img width="1759" alt="2 of 2" src="https://user-images.githubusercontent.com/45741495/64133877-35717e00-cdd1-11e9-984b-7f36be095d17.png">

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox Quantum 68.0.2 (64-bit)
* Operating System and version: Mac Mojave 10.14.6

**Comment by gorhill** [comment]
>  I checked the documentation to understand that the issue I report is not a normal behavior

I will close as invalid until you go through all the steps -- these steps are to prevent spurious issues from being opened.
