### ISSUE TITLE
Can't get video to play in Google Photos

### ISSUE THREAD

**Issue by antgel** [uBlockOrigin/uMatrix-issues#188]
### Prerequisites

- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [X] I used the logger to rule out that the issue is caused by my ruleset

### Description

I have a problem getting *videos* in Google Photos (photos.google.com to work).

### A specific URL where the issue occurs

https://photos.app.goo.gl/TgL9yz4ooizWpXURA

### Steps to Reproduce

Browse to above URL. Despite the fact that relevant parts of both googleusercontent.com and gstatic.com are green (for *), for some reason the video doesn't load. Looking at the rulesets, all should be covered. I have read the docs, but either I missed something or there's a bug.

### Ruleset

First photos.google.com:
![image](https://user-images.githubusercontent.com/295571/65889961-c7f24680-e3aa-11e9-9888-bf11f09ca013.png)

Everything is green apart from the googleusercontent.com and gstatic.com domains, which are handled by * scope (read on).

Now *:
![image](https://user-images.githubusercontent.com/295571/65889974-ce80be00-e3aa-11e9-88b3-7e9b97e6eb85.png)

```
* googleusercontent.com cookie allow
* googleusercontent.com media allow
* googleusercontent.com xhr allow
* googlevideo.com media allow
* googlevideo.com xhr allow
* ssl.gstatic.com script allow
* www.gstatic.com script allow
```

### Supporting evidence

![image](https://user-images.githubusercontent.com/295571/65889666-4ef2ef00-e3aa-11e9-87b2-81fa0ac5fcc8.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Google Chrome 77.0.3865.90
* Operating System and version: Ubuntu Linux Bionic (18.04)

**Comment by gorhill** [comment]
> I used the logger to rule out that the issue is caused by my ruleset

I had to use the logger to set rules, some tabless network requests show as blocked.

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/65892736-d02f8f00-e374-11e9-840c-26777f8266d8.png)

    photos.google.com googleusercontent.com * allow
    photos.google.com s.ytimg.com * allow
    photos.google.com youtube.googleapis.com * allow
    photos.google.com youtube.googleapis.com frame allow

**Comment by antgel** [comment]
@gorhill Thanks a lot, I learnt a lot from this e.g. how it's so much more efficient to use the "My rules" settings page than the graphical matrix (my opinion, the search is really nice, I could easily pull up duplicates, unnecessary rules, and rules that should have applied to `*`). Also the `--` in the logger - it's too late now, but I really didn't see those calls. Is the `--' special somehow e.g. shows "hidden" calls?

**Comment by gorhill** [comment]
Tabless requests are denoted by small "curtains" in the 3rd cell from right; `--` means "blocked".

I have this project to import code from uBO's logger to improve uMatrix's logger but I just can't find the time to do this.

**Comment by gorhill** [comment]
Also just in case, you can click on the 3rd cell in the logger to bring up a mini widget to quickly create rules from the logger -- this is how I created the rules I posted above.
