### ISSUE TITLE
Prevent Selection/Keyboard Disablers

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uMatrix-issues#192]
There are many sites now that annoying disable mouse/selection/keyboards in order to prevent selecting or copying text.

I am not sure if there already is a feature to do that or not but if there isn't, can one be added?

**Comment by uBlock-user** [comment]
I doubt this would be suitable for uMatrix given the nature.

**Comment by gorhill** [comment]
Declined. Scriptlets are beyond the scope of uMatrix.
