### ISSUE TITLE
Firefox with Sandboxie environment, umatrix not working anymore 

### ISSUE THREAD

**Issue by miru299** [uBlockOrigin/uMatrix-issues#194]
### Prerequisites

- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile

- [X ] I am running the latest version of uMatrix

- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description
Firefox running on Sandboxie with umatrix extension installed, web tabs are not loading pages anymore, until disabling the umatrix, 
  FYI- On regular firefox environment, it works fine, but on sandboxie, its not working from yesterday. I updated my assets
 

### A specific URL where the issue occurs
Any URL seems to be affected

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version:  1.4.0
* Browser Name and version: Firefox 70.0
* Operating System and version:  windows 10 10.0.18362 Build 18362

**Comment by gorhill** [comment]
Extensions have no dependencies on the OS, only on the browser APIs. Any issues caused by something out of view of extensions such as sandboxie should not be filed as an issue with the extension itself.
