### ISSUE TITLE
Container Specific Settings

### ISSUE THREAD

**Issue by dnut** [uBlockOrigin/uMatrix-issues#195]
It would be really useful to be able to whitelist certain domains only in their respective containers where they are sandboxed. It should be easy to implement this like Cookie AutoDelete: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/470d00048c20e69ec4bf37074a25e9507c482d92/src/redux/Actions.ts#L219-L256

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/741

**Comment by dnut** [comment]
Why is this declined? Resources or it's not a feature you want?

**Comment by gwarser** [comment]
>Containers are just separate cookie stores. The APIs used by uBO to block network requests are not cookie store-aware, so it's not possible. Even if it was possible, this would require adding a whole lot of complexity to uBO (or in other word, turning uBO into an unworkable, unmaintainable mess) and I rather not go there.

https://www.reddit.com/r/uBlockOrigin/comments/dmkv45/ublock_firefox_containers_integration/f55a5ts/
