### ISSUE TITLE
Chrome web store doesn't auto update uMatrix.

### ISSUE THREAD

**Issue by cnleo** [uBlockOrigin/uMatrix-issues#198]
### Prerequisites

- I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    -  I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - uMatrix is the only extension
    - uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

I have used uMatrix from chrome web store (1.3.16) without the knowledge that version 1.4 is already released and the release 1.4 is months ago.
An other bug report pointed out for me.

### A specific URL where the issue occurs

https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf

### Steps to Reproduce

1. You have an old version of uMatrix and it was installed from chrome web store.
2. It should updated after a reboot and start of your browser or 48h.(https://stackoverflow.com/questions/24100507/how-often-do-chrome-extensions-automatically-update)
3. But it doesn't.

I have still 2 version (chrome and chromium browser with uMatrix 1.3.16) for suggestions or hints how it works out of the box without manual uninstall and install again, please let me know and I will try it.

### Your environment

* uMatrix version: 1.3.16 / 1.4
* Browser Name and version: Chrome Version 78.0.3904.87 (Offizieller Build) (64-Bit) / Vivaldi 2.8.1664.44 (Stable channel) (32-bit) / Chromium Version 69.0.3442.0 (Entwickler-Build) (64-Bit)
* Operating System and version: Windows 7 Pro 64Bit

**Comment by gorhill** [comment]
Sorry about this, I had it set to update for 25% of users and completely forgot about this. It's now set to update for all users, however it's pending review and I have no control over how long this may take.

**Comment by cnleo** [comment]
Now it has been automatically updated in Chrome. (Sunday ~18:30 UTC+0)
Still waiting for Chromium, but I am sure it will happen.
