### ISSUE TITLE
How to delete all rules in firefox?

### ISSUE THREAD

**Issue by LArctic** [uBlockOrigin/uMatrix-issues#199]
Sorry, I posted this post using the translation tool, please forgive me for not using the predetermined format.

The default rules cause some sites to not display properly, so I (delete/cancel) all settings. But this seems to cause a bigger disaster, and almost all web pages have problems.
I want to know how to set uMatrix to be blank? Nothing happens, nothing is done unless I add new rules.

https://i.loli.net/2019/11/04/VtpUiTBujvFM4PL.png
https://i.loli.net/2019/11/04/IfcpEgsNo3LuUdC.png
https://i.loli.net/2019/11/04/BDftAmxL6yM9Gko.png

### Prerequisites

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uMatrix.

**Comment by gorhill** [comment]
> I want to know how to set uMatrix to be blank? Nothing happens, nothing is done unless I add new rules.

So if you want uMatrix to block nothnig by default, add only this one rule: `* * * allow`.
