### ISSUE TITLE
Collapse placeholder of blocked elements

### ISSUE THREAD

**Issue by svnpenn** [uBlockOrigin/uMatrix-issues#2]
Using Firefox 55, I tried with uMatrix 1.0.0 and 1.0.1rc1

However the option "Collapse placeholder of blocked elements" appears to be
ignored. Regardless if you check or uncheck it, the placeholders of blocked
elements are not collapsed, so you are left with blank placeholders littering
the page.

Note that uBlock Origin has the same option, but uBlock Origin correctly
collapses the blocked elements. Example page http://reddit.com

http://superuser.com/q/1248923

**Comment by svnpenn** [comment]
@gorhill anything?

**Comment by gorhill** [comment]
There is no cosmetic filtering in uMatrix. uMatrix will collapse the DOM elements which match blocked resources. The blank area on Reddit is a `div`, there is no such thing as a secondary resource matching a `div`.
