### ISSUE TITLE
uMatrix Popup Redesign

### ISSUE THREAD

**Issue by lentil01** [uBlockOrigin/uMatrix-issues#201]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

This is a proposal for a design refresh of uMatrix, affecting both aesthetics and usability. I feel that the design can be simplified / spruced up in certain areas. I've attached images of the current uMatrix popup on a sample site and a redesigned version to compare. Changes I made were as follows:

- Removed ‘flags’ for global rulesets in site-specific rulesets
- Switched to IBM Plex Sans + IBM Plex Sans Condensed for more flexibility with font weights
- grouped all, first-party, and 3rd-party sections to more easily distinguish between them
- moved number of requests block below site visited and added percentage
- added favicon (unsure how difficult this is to pull)
- cleaned up icons + spacing
- added preferences icon to top toolbar
- updated blocklisted hostname icon for improved contrast and clarity
- added dark green and dark red colors for text on colored background
- tweaked colors to be a bit less harsh
- removed dividers between blocks. when hovering you’ll see a color change that highlights the block you’re on anyways, so this removes visual clutter
- 1st-party is no longer an actionable item. this was redundant as you can achieve the same desired effect by interacting with the 1st-party domain (in this case technologyreview.com)
- removed top header with umatrix name and version number. figured this should be hidden in preferences as it’s not something most users are paying attention to or trying to access
- updated global ruleset icon to a globe from an asterisk
- removed bolding of subdomains for simplification

![uMatrix-popup-redesign](https://user-images.githubusercontent.com/21363432/68091916-907d2b00-fe7d-11e9-863b-687ffa4f3b8e.png)

<img width="570" alt="Screen Shot 2019-11-03 at 11 41 24 AM" src="https://user-images.githubusercontent.com/21363432/68091925-a854af00-fe7d-11e9-9300-eeef2fd3e8a5.png">

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Not an issue per se it's a proposal.

### Supporting evidence

Provided evidence is the comparison images.

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: FF 70.0.1
* Operating System and version: macOS Catalina 10.15.1

**Comment by WarpShift** [comment]
The new style seems to really look more visual. Perhaps it will be more convenient for new users.

**Comment by lentil01** [comment]
That was my thinking. uMatrix is really powerful but could be more user-friendly. Also thinking the preferences UI could be improved. Happy to help with further / expanded iterations @gorhill

**Comment by edjroot** [comment]
Nice redesign!

While we're at it, wouldn't it be a good idea to let users apply (and sync) their own CSS?

**Comment by Havokdan** [comment]
Its nice

**Comment by gorhill** [comment]
Declined.

**Comment by ArchangeGabriel** [comment]
@gorhill Just to be sure, did you decline because an enhancement like the one in recent uBlock versions is already planned, or because you are not interested at all?
