### ISSUE TITLE
Application of one configuration file in multiple profiles / Symlinks to the config file

### ISSUE THREAD

**Issue by Uberi-puzo** [uBlockOrigin/uMatrix-issues#208]
First things first, I saw these requests:

https://github.com/gorhill/uMatrix/issues/63
https://github.com/gorhill/uMatrix/issues/66
https://github.com/uBlockOrigin/uMatrix-issues/issues/193
https://github.com/gorhill/uMatrix/issues/433

My question is the following. I have several profiles (FF of the latest version at the moment) on one computer.

I want the same rules to work in multiple browsers. **"C:\uMatrix@raymondhill.net\storage.js"** already contains my rules.

I created symlinks

`mklink "C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\111\browser-extension-data\uMatrix@raymondhill.net\storage.js" "C:\uMatrix@raymondhill.net\storage.js"`

`mklink "C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\222\browser-extension-data\uMatrix@raymondhill.net\storage.js" "C:\uMatrix@raymondhill.net\storage.js"`

I expected the extension to see my rules. But it does not see them, along the path **moz-extension://.../dashboard.html#user-rules** there are absolutely no rules of mine. Neither in the first browser, nor in the second. Why?

**Comment by gwarser** [comment]
1. Storage files on disk are managed by browser.
1. Prefs in folder `browser-extension-data` are not used by Firefox for about half year. Moved to `storage/default/moz-extension+++per installation ID`.
1. Ask on some Firefox support forum?
1. Use "Cloud Storage" to sync uMatrix settings.

**Comment by uBlock-user** [comment]
Create a backup via `Backup to file` and restorevia `Restore from file` on any machine with all your settings intact.

**Comment by Uberi-puzo** [comment]
>     2\. Prefs in folder `browser-extension-data` are not used by Firefox for about half year. Moved to `storage/default/moz-extension+++per installation ID`.

So, that’s all what my mistake was and what I needed to know)) Thx.

Below is the instruction:

Find two folders with extension settings, for example:

`C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\111\storage\default\moz-extension+++654654y5-65gg-43ff-22qq-42323423r33e`

and

`C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\111\storage\default\moz-extension+++654654y5-65gg-43ff-22qq-42323423r33e^userContextId=7833621628`

You can rename them, I renamed. Not all names are accepted, if you specify the wrong name, the extension will not work in the browser. You can create the same name that I created. **userContextId** - something like a computer ID, it is the same in different profiles, and occurs many times in the registry in different places. Do not change it.

Now, move the folders to another place and create symlinks

`mklink /d "C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\111\storage\default\moz-extension+++00000000-0000-0000-0000-000000000000" "C:\moz-extension+++00000000-0000-0000-0000-000000000000"`

`mklink /d "C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\111\storage\default\moz-extension+++00000000-0000-0000-0000-000000000000^userContextId=7833621628" "C:\moz-extension+++00000000-0000-0000-0000-000000000000^userContextId=7833621628"`

You need to fix the **prefs.js** file in the profile folder. Open it with a text editor and find the **extensions.webextensions.uuids** parameter. Find the value **\"uMatrix@raymondhill.net\":\"654654y5-65gg-43ff-22qq-42323423r33e\** and correct it with **\"uMatrix@raymondhill.net\":\"00000000-0000-0000-0000-000000000000\"** (in my case). Save.

Lastly, launch the browser with the necessary profile, go to the **about:addons** tab and turn it off and then turn on the **uMatrix** extension. That's all, I checked in two profiles launched at the same time that there were no conflicts when creating rules, saving, closing the browser, then opening and loading the rules. But I can not guarantee that there will be no problems later))
