### ISSUE TITLE
Are rule cleaning functions desired?

### ISSUE THREAD

**Issue by gqqnbig** [uBlockOrigin/uMatrix-issues#210]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

I use block all allow exceptionally scheme. I have many rules allowing the specific site to access https://code.jquery.com/jquery-3.4.1.min.js. I would like to generalize it to `* code.jquery.com script allow`. I have many rules allowing the specific site to embed Youtube. I would like to generalize it to `* youtube.com frame allow`.

[I have written such function in C# in the past.](https://github.com/gqqnbig/uMatrixCleaner) I'm looking at my code again, and wondering if these kinds of rule merging/cleaning function in scope of the plugin. If yes, I may be able to port my code to JavaScript so that the plugin can come with the cleaning rule function.

These are the cleaning functions I have.

1. Merge with threshold. If the threshold is 3,

```
google.com facebook.com * block
google.com youtube.com * block
google.com twitter.com * block
```

can be merged to 

```
google.com * * block
```

If the threshold is 2,

```
google.com www.facebook.com script block
google.com login.facebook.com script block
```

can be merged to 
```
google.com facebook.com script block
```

2. Random delete rules.

**Comment by gorhill** [comment]
If you enter `code.jquery.com script allow` or `youtube.com frame allow` in the filter field, you should be able to quickly remove all instances of `[...] code.jquery.com script allow` and replace them with a single `* code.jquery.com script`.

**Comment by gqqnbig** [comment]
Yes, I'm talking about automating the whole process.

**Comment by gorhill** [comment]
> while my C# code already implemented this.

Copy paste your rules in a file, run your script, then paste back your rules.

I am going to expressly decline this: I just do not have the time/energy to constantly throw code at uMatrix which I have to create + maintain forever + deal with the inevitable subsequent feature requests arising from such new features.

**Comment by gqqnbig** [comment]
It's understandable. Thanks.
