### ISSUE TITLE
uMatrix 1.4.1b3, "Fetch" column name displays incorrectly in latest Firefox.

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uMatrix-issues#213]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Incorrect column name in the popup panel with latest Firefox (at least) - "получит" instead of "fetch". **Reproduceable only in browsers with RU locale** (for example, https://portableapps.com/redirect/?a=FirefoxPortable&s=s&p=&n=Mozilla%20Firefox,%20Portable%20Edition&d=sfpa&f=FirefoxPortable_71.0_Russian.paf.exe), may be seen in clean portable FF 71 with uMatrix 1.4.1b3 as the only extension.

### A specific URL where the issue occurs

Any actual website.

### Steps to Reproduce

1. Install clean portable RU Firefox.
2. Install uMatrix 1.4.1b3 from its Github page.
3. Click uMatrix icon and see "получит" to the right from "script" column.

### Ruleset

Default

### Supporting evidence
![Clipboard 1](https://user-images.githubusercontent.com/16985985/71579722-e9301380-2b0e-11ea-8987-fdb383321d88.jpg)

### Your environment

* uMatrix version: 1.4.1b3
* Browser Name and version: Firefox 72.0b11 x64, also Firefox 71 x64
* Operating System and version: Win7 x64 Pro

**Comment by gorhill** [comment]
The translators are responsible to make it so that the column header fits -- there is an explicit warning in the description: `"HAS TO FIT IN MATRIX HEADER!"`. If the new term does not fit, I suggest to revert to the old term, and this sort of feedback has to be provided at <https://crowdin.com/project/umatrix>.

**Comment by zummuz** [comment]
@TheFinalCut83 I apologize, my fault
I think it's better not to translate that header after all, because it's vague and a bit confusing in russian, and also, evidently, breaks general style. I reverted it back to english. Sorry again.

**Comment by TheFinalCut83** [comment]
@zummuz 
Thanks! It's okay, no one is safe from mistakes. I, too, for the option to leave the untranslated version. I hope in future betas this translation will be replaced. I think, issue can now be closed.
