### ISSUE TITLE
I can't access techcrunch.com when uMatrix is on

### ISSUE THREAD

**Issue by daveloyall** [uBlockOrigin/uMatrix-issues#216]
Your bug report template is hostile to users.  You could ask for all that information without insulting our intelligence.  Try it!

### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### A specific URL where the issue occurs

https://www.techcrunch.com

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Supporting evidence

`moz-extension://8d41c6e5-f832-4374-b60b-10211f5c4121/main-blocked.html?details=eyJ1cmwiOiJodHRwczovL2d1Y2UuYWR2ZXJ0aXNpbmcuY29tL2NvbGxlY3RJZGVudGlmaWVycz9zZXNzaW9uSWQ9MV9jYy1zZXNzaW9uXzgwNTFlMDU2LWQ1YjItNDE1Mi05ZDAzLTk0M2M1MDRhYjU2NyIsImhuIjoiZ3VjZS5hZHZlcnRpc2luZy5jb20iLCJ0eXBlIjoiZG9jIiwid2h5IjoiPyJ9`

### Your environment

* uMatrix version: 1.3.17 rc4
* Browser Name and version: Firefox 74.0a1 (2020-01-15) (64-bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix#warnings
