### ISSUE TITLE
Allow rules to be defined with full URLs instead of just hostnames (e.g. to allow loading of Google reCaptcha but block all other Google traffic)

### ISSUE THREAD

**Issue by diamondavocado** [uBlockOrigin/uMatrix-issues#217]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

There are some cases where you may wish to block or allow only certain resources on a domain. For example Google reCaptcha is used on millions of websites where it is required for the submission of web forms. 

Currently the only solution to make a website with reCaptcha work properly is to either manually allow `google.com` and other related domains on a first-party or global level. This is undesirable because it then opens up the door to other tracking scripts etc. from the domain. 

It would be far better if we could define a rule using a URL pattern instead of at the domain level. For example you could allow `google.com/recaptcha/*` or similar which would only allow reCaptcha resources to be loaded but continue to block all other traffic from that domain.

**Comment by uBlock-user** [comment]
> It would be far better if we could define a rule using a URL pattern instead of at the domain level. For example you could allow google.com/recaptcha/* or similar which would only allow reCaptcha resources to be loaded but continue to block all other traffic from that domain.

Use uBlock Origin for that. uMatrix is a matrix based filtering firewall.

**Comment by allhavebrainimplantsandmore** [comment]
> > It would be far better if we could define a rule using a URL pattern instead of at the domain level. For example you could allow google.com/recaptcha/* or similar which would only allow reCaptcha resources to be loaded but continue to block all other traffic from that domain.
> 
> Use uBlock Origin for that. uMatrix is a matrix based filtering firewall.

And why can a matrix based filtering firewall filter URL patterns, at least the first level folder, where most service forking occurs?

**Comment by uBlock-user** [comment]
> And why can a matrix based filtering firewall not filter URL patterns

It used to as [HTTPSwitchBoard](https://github.com/gorhill/httpswitchboard#http-switchboard-for-chromium), then the project got split up into two extensions uMatrix and uBlock.
