### ISSUE TITLE
uMatrix not save hosts lists update in private browsing mode.

### ISSUE THREAD

**Issue by MetalAlch** [uBlockOrigin/uMatrix-issues#219]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
When Firefox work in privatebrowsing mode uMatrix not have access to "indexedDB" and accordingly does not have the ability to save hosts files updates. Only can save settings change.

### A specific URL where the issue occurs

none

### Steps to Reproduce

1: Open Firefox browser.
2: Enter uMatrix settings and make sure all hosts up-to-date.
3: Open about:config.
4: Change pref **browser.privatebrowsing.autostart** from **false** to **true**.
5: Close browser and then open.
6: Enter uMatrix settings and you should see that the all hosts files need updating.
7: Update them.
8: Close browser and open again.
9: Enter uMatrix settings and you should see again that the all hosts files need updating.
### Ruleset

standard

### Supporting evidence

This is all due to the fact that at the end of 2017 uMatrix lost possibility save hosts updates in "browser.storage.local" and use only "indexedDB". From Firefox 72.0 **dom.indexedDB.enable** lock permanently  with **true** but when Firefox work in private browsing mode indexedDB disabled for privacy and security reasons.

Same problem. Only with uBlock Origin (FIXED):
https://github.com/uBlockOrigin/uBlock-issues/issues/409
Your solution to the problem:
https://github.com/gorhill/uBlock/commit/0d369cda21bbce23a7376e0f7b2847a3c7a6d3d8
### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 72.0.2
* Operating System and version: Windows 10 x64 (1607,1809), Debian 10.

**Comment by uBlock-user** [comment]
Can you reproduce via the dev build ?

**Comment by MetalAlch** [comment]
NO. Version 1.4.1b5 not have THIS problem. All updates are saved in "browser.storage.local" in privacy mode. But have bug with popup visibility (just find). May I hope that in the next stable release my issue will be solved?

**Comment by uBlock-user** [comment]
> But have bug with popup visibility (just found)

File another issue for that.

> May I hope that in the next stable release my issue will be solved?

It's fixed in the dev build, so wait for the stable release or use dev build in the mean time.
