### ISSUE TITLE
Forbid Web Workers switch doesn't display detected web worker on a specific webpage

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uMatrix-issues#22]
### Prerequisites

* [x] Did you perform a cursory search of the issue tracker?
  
* Can you reproduce the problem when...
    * [x] uMatrix is the only extension?
    * [x] uMatrix with default lists/settings?
    * [ ] using a new, unmodified browser profile?
* [x] Are you running the latest version?
* [x] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

On this web workers [test page](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_webworker), the _Forbid Web Workers_ switch doesn't display detected web worker when pressed `Start Worker` from the aformentioned javascript test page, although it successfully blocks any creation of Web Workers as per dev tools in Chromium.

### A specific URL where the issue occurs

https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_webworker

### Steps to Reproduce

1. Have `no-workers: * true` in My Rules.
2. Browse to https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_webworker and click `Start Worker`.
3. Click on the uMatrix icon and notice that's it doesn't display **white dotted** icon for the Forbid Web Workers switch even though Web Workers were detected and blocked as per dev tools.

### Supporting evidence

https://i.gyazo.com/61c9f88bb48c73788065ada49eb8480a.png

### Your environment

* uMatrix version: 1.3.9.1
* Browser Name and version: Chromium 69
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Can be reproduced on Chromium 67(current stable) too.

**Comment by gwarser** [comment]
Firefox says:

>Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.

**Comment by uBlock-user** [comment]
That's normal, Firefox expects a URL instead of `about:blank`. Also this issue is specific to Chromium, so don't remove the Chromium lable.

**Comment by grenzor** [comment]
I don't think it's a Chromium specific issue. I could never see the white dotted icon on Firefox.

**Comment by uBlock-user** [comment]
The white dot does appear for me on Firefox Nightly - https://i.gyazo.com/5b9fc6b531dcc71e1fc6db25c23da306.png

**Comment by grenzor** [comment]
Odd because it doesn't show for me in v61 latest Firefox beta screenshot taken while the counter is running: https://i.imgur.com/mfsiN99.jpg

I've tried to get the white dotted icon to appear in the past when it was added as a feature but I have never seen the dot even on other websites using web workers so I assumed it didn't show because of something with my Firefox setup. But the above image is in a pretty clean profile so unless it was recently fixed in Nightly I don't know. 

Anyone else on stable/beta Firefox that can check if the white dotted icon shows for them?

**Comment by gorhill** [comment]
> I could never see the white dotted icon on Firefox.

You need to toggle `security.csp.enable_violation_events` to `true`. I confirm the issue does not affect Firefox.

**Comment by grenzor** [comment]
Thanks gorhill, now I can see it. I'm guessing the config value is turned on by default in Nightly then.

**Comment by uBlock-user** [comment]
@gorhill https://bugs.chromium.org/p/chromium/issues/detail?id=996659 ?

is that relevant to bug ?

**Comment by uBlock-user** [comment]
@gorhill Regression in v1.4.1b0 on Firefox, it doesn't display white dotted icon for the Forbid Web Workers switch, neither a blocked entry is seen in the logger, the web-worker CSP is blocked unconditionally too.
