### ISSUE TITLE
Custom Hosts-files Import Description

### ISSUE THREAD

**Issue by rusty-snake** [uBlockOrigin/uMatrix-issues#221]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Sure?

![screenshot](https://user-images.githubusercontent.com/41237666/73596101-1eb58b80-4517-11ea-92dc-8569408148e9.png)

### Steps to Reproduce

1. Open the Dashboard
2. Go to Assets
3. Hosts
4. Import

### Your environment

* uMatrix version: 1.4.0 / Latest on AMO
* Browser Name and version: Firefox 72 for Fedora | Nightly
* Operating System and version: Fedora 31

**Comment by gorhill** [comment]
This needs to be reported/fixed at Crowdin -- the English translation does not use quotes.

See <https://crowdin.com/translate/umatrix/18/en-de>.
