### ISSUE TITLE
Assets remain outdated updating

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uMatrix-issues#227]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

The assets remain outdated after purging all caches and updating.

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

1. Go to "Assets"
2. "Purge all caches"
3. "Update now" and wait for all icons to show completion (also the log of uMatrix shows correctly completed XHRs for each asset URL)
4. Click on some asset (say "Dan Pollock's host file") and see (paste):

```
# Last updated: Mon, 29 Jul 2019 at 04:52:50 GMT
```
5. Compare with the result from the actual url (https://someonewhocares.org/hosts/hosts):

```
# Last updated: Sun, 23 Feb 2020 at 11:02:11 GMT
```

The same seems to be the case with the other lists.
I notice this issue only in Tor browser. (in Chromium everything works fine)

### Ruleset

Default

### Supporting evidence

Above.

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Tor browser 9.0.5 (based on Mozilla Firefox 68.5.0esr) (64-bit)
* Operating System and version: openSUSE Leap 15.1

**Comment by gwarser** [comment]
I can reproduce.

Is not this caused by disabled IndexedDB in TorBrowser?

**Comment by uBlock-user** [comment]
> Is not this caused by disabled IndexedDB in TorBrowser?

uBO has `cacheStorageAPI` setting with fallback option where if the one API is not available, it would fallback to the other, that should be implemented here too.

**Comment by gorhill** [comment]
> it would fallback to the other, that should be implemented here too.

I imported uBO's code en-bloc[1] expecting there will be a lot of breakage all over the place -- and I did spent a lot of time over weeks to try to fix everything -- this could be one of those breakage which I didn't catch.

**Comment by gorhill** [comment]
Hum, actually I realize this is uMatrix 1.4.0, so the fix is probably in the dev build here, this should be tested.

**Comment by uBlock-user** [comment]
> I imported uBO's code en-bloc[1]

Without the advanced setting to set between local storage API and indexedDB like we have in uBO ?

**Comment by gorhill** [comment]
@gwarser 

I finally got around to try to reproduce and I could not reproduce. My Tor browser security standard is set to "Standard", which I believe is the default.

**Comment by emanruse** [comment]
> My Tor browser security standard is set to "Standard", which I believe is the default.

Mine is set to "Safest".

**Comment by uBlock-user** [comment]
@emanruse shouldn't be an issue anymore, you can try the latest dev build.

**Comment by gwarser** [comment]
Did you mixed 1.4.0 and dev builds in the same TOR Browser instance? It will _magically_ work in dev. I cannot even bisect, because it just work. But if done this way then it does not:

- freshly extracted `tor-browser-linux64-9.0.5_en-US.tar.xz`
- go to addons.mozilla.org, search for uMatrix and install
- toolbar button -> Dashboard
- click on "Dan Pollock’s hosts file" in Assets
- it's old file: # Last updated: Mon, 29 Jul 2019 at 04:52:50 GMT
- click Update now and wait for everything to update
- click again "Dan Pollock’s hosts file"
- still old file
- xhr's in browser console shows all assets are correctly downloaded, only "Request to access cookie or storage on XXX was blocked..." warning
- no update-related errors in console, only this on addon startup:

	cookies is undefined cookies.js:103
	Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. vapi-background.js:594
	Unknown localization message http i18n.js:158
	Unknown localization message assetsinlinerecipeshint i18n.js:165

**Comment by gwarser** [comment]
Dev build from GitHub works, so ¯\\\_(ツ)\_/¯

**Comment by emanruse** [comment]
> Dev build from GitHub works, so ¯\\\_(ツ)\_/¯

Is this pre-release 1.4.1b6 from 24.Feb?

If not - could you please explain (or provide a link to info) how to try that dev build?

**Comment by uBlock-user** [comment]
Yes.

**Comment by emanruse** [comment]
Thank you.
I confirm that in 1.4.1b6 this works as expected.
