### ISSUE TITLE
uMatrix and uBlock occasionally stop working and appear empty/blank in Firefox

### ISSUE THREAD

**Issue by diamondavocado** [uBlockOrigin/uMatrix-issues#231]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

This is a tricky one because I can't reliably reproduce it, but occasionally (maybe once a week) uMatrix and uBlock will simply stop working completely. Their interfaces (the toolbar popups) appear totally empty.

There doesn't seem to be a trigger for this like Firefox crashing or anything. It just happens, and I can't get them to work normally until I restart Firefox completely.

### Steps to Reproduce

Can't reproduce reliably.

### Supporting evidence

![Screenshot](https://i.imgur.com/sAGwKjB.png)

![Screenshot](https://i.imgur.com/3DVLjtM.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 73
* Operating System and version: Windows 7 64bit

**Comment by uBlock-user** [comment]
Sounds like storage corruption issue in Firefox upon the crash.

**Comment by diamondavocado** [comment]
> Browse to https://firefox-storage-test.glitch.me/ and post the results.

Everything's good there (once I give the site the required permissions in uMatrix), but I've since restarted Firefox so the issue has solved itself. 

Next time this happens I'll go there before I restart Firefox and post the results.

**Comment by uBlock-user** [comment]
> Next time this happens I'll go there before I restart Firefox and post the results.

You may want to test it out in a new profile and see if you can reproduce there.

**Comment by gorhill** [comment]
Please go through the steps you did not check -- it appears the browser's extension framework is failing, this would affect all extensions, not just uBO/uMatrix.

**Comment by diamondavocado** [comment]
> 
> 
> Please go through the steps you did not check, especially _"using a new, unmodified browser profile"_ -- it appears the browser's extension framework is failing, this would affect all extensions, not just uBO/uMatrix.

That probably is the case but unfortunately because this happens so infrequently it isn't really practical to use an unmodified profile as I'd have to use it for potentially weeks. I appreciate that makes it almost impossible to properly diagnose. 

However if you have suspicions about the cause (e.g. Firefox storage corruption) is there anything you or I can do to help test those suspicions further? 

One big concern I have as a result of this is the discovery that Firefox extensions can suffer catastrophic failure without affecting the rest of the browser (and indeed without any error messages). 

Presumably this means if you're using uBlock, uMatrix, or some other extension for "protection" of your privacy, that protection could be compromised at any time and you wouldn't know about it until it was "too late" - kind of like a firewall suffering a leak.

Is there any way you can detect such a failure and do something like stop all traffic exiting the browser, or at least warn the user?

**Comment by diamondavocado** [comment]
Will do, the next time this happens I'll report back. Thanks.

**Comment by gorhill** [comment]
Also, a badly behaving extension could cause also these symptoms since all extensions execute in the same process. Since you did not check _"uMatrix is the only extension"_, what other extensions do you have installed?

**Comment by Thorin-Oakenpants** [comment]
FYI: [1355239](https://bugzilla.mozilla.org/show_bug.cgi?id=1355239) - leads to other bugzillas such as
- [1592310](https://bugzilla.mozilla.org/show_bug.cgi?id=1592310) extensions suddenly stops working (including uBO) -> see the attached [pic](https://i.imgur.com/BPP1vyj.png) which matches OP's experience i.e blankness

**Comment by diamondavocado** [comment]
@gorhill This error finally happened again and I was able to capture some of the errors which appeared in the console.

Not sure if these are helpful at all, and I know they're probably not related to uBlock or uMatrix specifically given what @Thorin-Oakenpants said, but I'm posting them here because I said I would:

```
services.settings: Signature verified failed for main/normandy-recipes-capabilities. Retry from scratch 2 RemoteSettingsClient.jsm:561
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:112
    onBeforeRequest moz-extension://[removed GUID]/js/webrequest.js:112
Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. 2 vapi-background.js:600
    remove moz-extension://[removed GUID]/js/vapi-background.js:600
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:112
    onBeforeRequest moz-extension://[removed GUID]/js/webrequest.js:112
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:112
    onBeforeRequest moz-extension://[removed GUID]/js/webrequest.js:112
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 webrequest.js:112
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 webrequest.js:112
Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. 2 vapi-background.js:600
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:112
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:112
    onBeforeRequest moz-extension://[removed GUID]/js/webrequest.js:112
XUL box for button element contained an inline _moz_generated_content_after child, forcing all its children to be wrapped in a block. 8 search-one-offs.js:555:19
TypeError: this.messageManager is null
MessageChannel.jsm:208:5
No matching message handler for the given recipient. MessageChannel.jsm:964
Warning: unrecognized command line flag -profile
BrowserContentHandler.jsm:1001
 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. fingerprinting.js:331
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:462
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
No matching message handler for the given recipient. MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. fingerprinting.js:331
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
No matching message handler for the given recipient. MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 common.js:5
No matching message handler for the given recipient. 5 MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:462
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 6 common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 5 common.js:5
No matching message handler for the given recipient. MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. fingerprinting.js:331
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
No matching message handler for the given recipient. 3 MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. socialwidgets.js:462
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
    sendMessage moz-extension://[removed GUID]/rea/common.js:5
No matching message handler for the given recipient. MessageChannel.jsm:964
    _handleMessage resource://gre/modules/MessageChannel.jsm:964
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 10 common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
    sendMessage moz-extension://[removed GUID]/rea/common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
    sendMessage moz-extension://[removed GUID]/rea/common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
    sendMessage moz-extension://[removed GUID]/rea/common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
    sendMessage moz-extension://[removed GUID]/rea/common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:5
```

I have many extensions installed, some small/obscure ones but the main "big" ones are:

DuckDuckGo Privacy Essentials
HTTPS Everywhere
Privacy Badger
Reddit Enhancement Suite
Stylus
Tampermonkey
uBlock Origin
uMatrix
