### ISSUE TITLE
uMatrix does not see disqus.map.fastlylb.net requests while uBO does

### ISSUE THREAD

**Issue by ThurahT** [uBlockOrigin/uMatrix-issues#233]
### Prerequisites

- [✓] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [✓] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [✓] I am running the latest version of uMatrix
- [✓] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [✓] I used the logger to rule out that the issue is caused by my ruleset

### Description

uMatrix does not see disqus.map.fastlylb.net requests while uBO does. The uMa logger shows no fastly requests at all. If I block fastly in uBO disqus will not load. In uBO logger I can see a lot of fastly requests. It loads scripts from https://prod.disqus.map.fastlylb.net for example.

### A specific URL where the issue occurs

https://samnytt.se/uppgifter-turkisk-militar-smugglar-migranter-till-grekland/ <-- scroll down to load disqus comments

### Steps to Reproduce

1. Scroll down to activate disqus
2. Look in dashboard
3. Notice missing fastlylb domain request

### Supporting evidence
Sorry for the big screenshots since this was on mobile. The screenshots were taken after the page with disqus was fully loaded and browser was finished loading any content.

[uBO](https://i.imgur.com/9ftISkb.png)
[uMa](https://i.imgur.com/agrvBCb.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Mozilla Firefox 68.5.0esr
* Operating System and version: Android 10

**Comment by gorhill** [comment]
No version of uMatrix has been released announcing support for uncloaking canonical names.

The feature is in the development build of uMatrix, see <https://github.com/gorhill/uMatrix/releases>.

**Comment by ThurahT** [comment]
Ah, okay I see. I didn't know how they differed in this aspect. Good thing to know. Thanks for clarification.
