### ISSUE TITLE
uMatrix 1.4.1bx not work when dom Intersection Observer API disabled.

### ISSUE THREAD

**Issue by Gilgamesh83** [uBlockOrigin/uMatrix-issues#235]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
Hi.

I disable dom Intersection Observer API for many years. For privacy and security reason of course. I have never had a problem with this. Until now. As it turned out, if the api is disabled uMatrix 1.4.1b**x** does not work either.

### Steps to Reproduce
1. Fresh install Firefox browser (any version).
2. Install any dev version uMatrix 1.4.1
3. Open about:config
4. Find string "dom.IntersectionObserver.enabled"
5. Change from **true** to **false**.
6. Restart browser.
7. Try open popup on uMatrix badge

### Ruleset
Default ruleset. Nothing has changed.

### Supporting evidence
![uMatrix](https://user-images.githubusercontent.com/61933147/76161163-73f14800-6128-11ea-97bd-f54f3cd44617.png)
uMatrix 1.4.0 and lower not have this issue. I think this is somehow connected with **DOMRect**. But I'm not sure.

### Your environment

* uMatrix version: 1.4.1b**x**
* Browser Name and version: Firefox 73.0.1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix/blob/9b292304d33a44465922200efa5f8b378d0f9604/src/js/popup.js#L80

You're disabling an API that uMatrix makes use of, hence the breakage, not an issue.

**Comment by Gilgamesh83** [comment]
uMatrix worked fine without this API before. What change? Enabling Intersection Observer makes users even more vulnerable to ClientRects Fingerprinting. Many trackers use this technique to determine the users. This huge mistake to use this API in the extension.

**Comment by uBlock-user** [comment]
> uMatrix worked fine without this API before. What change? Enabling Intersection Observer makes users even more vulnerable to ClientRects Fingerprinting. Many trackers use this technique to determine the users. This huge mistake to use this API in the extension.

uMatrix's development doesn't depend on what APIs can be abused or what APIs users decide to disable, that's just illogical to think.

Disabling any dom.* APIs in Firefox will result in breakage of not only in extensions but everywhere.

**Comment by Gilgamesh83** [comment]
Many advanced users disable dom api(s) for privacy and security. uMatrix not designed for ordinary users. I live perfectly with a lot of disabled DOM. Fewer opportunities to attack.

**Comment by uBlock-user** [comment]
> Many advanced users disable dom api(s) for privacy and security.

Those advanced users are also accepting the evitable "breakage" that comes with it.

**Comment by Gilgamesh83** [comment]
I have never seen when dom Intersection Observer API disabled breaking ANY sites or etc. Why for many years I had problems with dependency only with uMatrix. THREE YEARS could not make uMatrix work fine in privacy browsing mode. But when you fixed it at last, you created a new dependency problem with Intersection Observer API. It was not me who broke the extension. You did it. Bye.

**Comment by gwarser** [comment]
This looks like optimization of cosmetic fix. Errors should already be handled:

    if ( xobserver !== null ) { return; }

It's something to fix.

**Comment by gorhill** [comment]
@uBlock-user such issues in uMatrix's own code should not be dismissed before the exact cause is known.

**Comment by uBlock-user** [comment]
Are you going to remove the IntersectionObserver API from uMatrix, otherwise the cosmetic fix here will not fix the breakage ?

**Comment by gorhill** [comment]
> Are you going to remove the IntersectionObserver API from uMatrix

I don't know, I need to investigate first. If not using intersection observer breaks uMatrix, I won't change the code and the issue either lies with the browser (which maybe shouldn't disable API for extensions), or the user will have to accept that disabling API breaks stuff.

**Comment by uBlock-user** [comment]
uBO doesn't make use of this API, can that scenario be brought here ? I think that will an ideal fix.

**Comment by gorhill** [comment]
> Enabling Intersection Observer makes users even more vulnerable to ClientRects Fingerprinting.

I fail to see how so. Intersection observer just sends notifications when a specific area in the DOM become visible. The client rects information can be extracted regardless of the intersection observer.

**Comment by gorhill** [comment]
Side note: Given that the IntersectionObserver API is present by default in all Chromium-based browser v51+, Firefox 55+ (including the Tor browser), making it unavailable will make someone stands out more.

Anyway, the fix was trivial enough but I will not address further breakage as a result of disabling a standard DOM API.
