### ISSUE TITLE
Slack icons are broken until UMatrix is disabled in that context

### ISSUE THREAD

**Issue by PenelopeFudd** [uBlockOrigin/uMatrix-issues#237]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

The web version of Slack shows broken image icons instead of emojis, even after enabling all slack-related resources.  Only by disabling UMatrix in this scope do they appear.  The UMatrix log doesn't show anything being blocked, but the Chrome devtools network log shows some are blocked.

### A specific URL where the issue occurs
* https://app.slack.com/client/T024T1K11/11H03E21X  # 
* https://slack-imgs.com/?c=1&o1=gu&url=https%3A%2F%2Fa.slack-edge.com%2Fproduction-standard-emoji-assets%2F10.2%2Fapple-small%2F1f50d.png

### Steps to Reproduce

1. Go to a slack channel where there are emojis (e.g. "Working From Home")
2. Observe the broken image icons
3. Enable everything

### Ruleset

slack.com a.slack-edge.com script allow
slack.com accounts.google.com * allow
slack.com downloads.slack-edge.com frame allow
slack.com google.com * allow
slack.com slack-edge.com * allow
slack.com slackb.com other allow
### Supporting evidence

<img width="1089" alt="Screen Shot 2020-03-16 at 3 07 52 PM" src="https://user-images.githubusercontent.com/1606480/76803935-3def3c00-6798-11ea-99b4-d6849ca1ed47.png">

![Screen Shot 2020-03-16 at 2 59 35 PM](https://user-images.githubusercontent.com/1606480/76803661-940faf80-6797-11ea-935b-0016f643afa1.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Chrome  80.0.3987.132 (Official Build) (64-bit)
* Operating System and version: MacOS Catalina 10.15.3

**Comment by PenelopeFudd** [comment]
The domain slack-imgs.com doesn't appear in the UMatrix log nor the matrix itself.  I'm wondering if the little gear icon indicates requests handled by a service worker?

**Comment by gwarser** [comment]
Did you tried turning off "Spoof referer header" in per-scope switches? https://github.com/uBlockOrigin/uMatrix-issues/wiki/Per-scope-switches#spoof-referer-header

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix#regarding-broken-sites

**Comment by PenelopeFudd** [comment]
From the link given above:
"Using uMatrix logger is key to un-break sites: the logger will show you all that uMatrix does internally."

See the screenshot above.

There were *no* blocked urls shown in the uMatrix logger, yet the site was still broken.

The Google DevTools console log revealed the url that was being blocked, but that domain did not appear in the log or the matrix.

Sorry, but this is actually a bug in uMatrix.

**Comment by uBlock-user** [comment]
> There were no blocked urls shown in the uMatrix logger, yet the site was still broken.

> The Google DevTools console log revealed the url that was being blocked, but that domain did not appear in the log or the matrix.

Logger is forward-looking, so refresh the page after opening the logger, which will record all network requests.

**Comment by uBlock-user** [comment]
Also as per supporting evidence you posted, you have two per-site switches enabled which are blocking some network requests, so you should also look into that.

**Comment by gorhill** [comment]
> There were no blocked urls shown in the uMatrix logger

Try the dev build of uMatrix, there was an issue where the `Referer` header modification was reported only the first time a page was loaded and no longer reported in subsequent reload of the page.
