### ISSUE TITLE
Cached Images are blocked for XHR; XHR column shows no blocked entries

### ISSUE THREAD

**Issue by VADemon** [uBlockOrigin/uMatrix-issues#239]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

At first I thought this was related to "hard default-deny" mode, but the issue is deeper:
Upon inspecting the logger, it turns out the images are getting blocked on grounds of "XHR", although the GUI shows no blocked elements in XHR column.

If you open the website for the first time, icon images will load from wiki.factorio.com.
If you (re-open?) F5 the page, icon images will NO LONGER load.
If you CTRL+F5 the page, icon images will LOAD NORMALLY.

PS: Apparently, disabling all possible cache settings in `about:config` 'patched' the difference in CTRL+F5 ←→ F5, as the images now load with a mere F5. But I too managed to break that browser profile in the process. :)

I likely uncovered the mystery of #119: Firefox API bug or a quirk?

PPS: Imho two issues at hand:

1. uMatrix shows no entries in XHR
2. Firefox showing these image requests as XHR to the addon.

### A specific URL where the issue occurs

`https://factoriocheatsheet.com/#science`

### Steps to Reproduce

1. New install of uMatrix.
2. Don't change any settings.
3. Open site to verify it's 100% correct.
4. F5 to verify icons no longer load.
5. CTRL+F5 to verify icons load normally.

### Supporting evidence

![fx-xhr-cached-image](https://user-images.githubusercontent.com/1168140/77220291-00473600-6b3f-11ea-8615-1492dbef53fa.png)

### Your environment

* uMatrix version: 1.4.0 (Mozilla Addons)
* Browser Name and version: Firefox Beta 75b6
* Operating System and version: Win7

**Comment by uBlock-user** [comment]
> Firefox showing these image requests as XHR to the addon.

Because there's a service worker present and it will seen as that once you disable forbid web workers switch.

**Comment by VADemon** [comment]
I tried to: select Global `*` scope and "Forbid webworkers" in the drop down menu, no change. This appears to be browser-related, not sure how webworkers are supposed to be an issue.

**Comment by uBlock-user** [comment]
> how webworkers are supposed to be an issue

Once a web-worker is loaded, images will be pulled as XHRs/fetch requests and the logger will  reflect the same.

**Comment by uBlock-user** [comment]
Try with the dev build and see if you can reproduce there.

**Comment by VADemon** [comment]
Yes, reproducable. I tried to "Forbid web workers" without an effect.

I recorded a video so you can confirm I'm doing everything right (3min, can up speed) https://www.youtube.com/watch?v=b_4q10e-W7s

**Comment by uBlock-user** [comment]
>  I tried to "Forbid web workers" (again) without an effect.

You didn't un-register the service worker after you enabled Forbid web-workers switch via `about:debugging#/runtime/this-firefox.`

**Comment by uBlock-user** [comment]
As for "XHR column shows no blocked entries" those requests are tabless because they're fetch events performed by the service-workers, tabless requests don't appear in the popup panel of uMatrix/uBO.
