### ISSUE TITLE
hosts-file.net is dead

### ISSUE THREAD

**Issue by ewhac** [uBlockOrigin/uMatrix-issues#245]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

hpHosts’ Ad and tracking server (hosts-file.net) is dead.  The domain responds with a 301 error (moved permanently), redirecting to Malwarebytes, and no longer furnishes a list of disreputable host names.  As such, it can no longer be used as a blacklist asset.

Apparently first noticed about a week ago:

https://www.reddit.com/r/pihole/comments/fsg11e/hostsfilenet/

### A specific URL where the issue occurs

https://hosts-file.net

### Supporting evidence

```
bash$ curl https://hosts-file.net
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.malwarebytes.com/browserguard">here</a>.</p>
</body></html>
```

**Comment by gwarser** [comment]
Yes, it was removed already, but this caused issues: https://www.reddit.com/r/uMatrix/comments/ftebgz/no_pages_load_on_firefox_unless_i_disable_umatrix/

Was handled here: https://github.com/uBlockOrigin/uMatrix-issues/issues/223
