### ISSUE TITLE
Firefox XPI

### ISSUE THREAD

**Issue by SairesArt** [uBlockOrigin/uMatrix-issues#25]
Hi,

I'm a big fan of uMatrix use alternative firefox releases on Windows, making recent uMatrix version unobtainable.
Last time a .XPI of uMatrix was released is 1.1.4, which is still the version I'm running.
Would it be possible to get .xpi releases back or somehow compile it one's self?

**Comment by uBlock-user** [comment]
Not sure what you mean, .xpi builds never stopped - https://github.com/gorhill/uMatrix/releases/tag/1.3.11b0
