### ISSUE TITLE
Importing Rules File Extensions Allowed Changed Only shows ".bib"

### ISSUE THREAD

**Issue by OnlinePlayer865** [uBlockOrigin/uMatrix-issues#251]
### Prerequisites

- [Yes ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [Yes ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [Yes] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [Yes ] uMatrix with default lists/settings
    - [Yes ] using a new, unmodified browser profile
- [Yes ] I am running the latest version of uMatrix
- [Yes ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

I installed Firefox Nightly freshly due to an unrelated issue. So it's a fresh install. Version; 77.0a1 (2020-04-24) (64-bit)
When I went into uMatrix > My Rules > Import From File, I noticed that the only extension I can import is ".bib". I went to Firefox Stable and when I went through the same steps I got as extensions I can import ".bib", ".txt".
### A specific URL where the issue occurs
N/A

### Steps to Reproduce

1. Install Firefox Nightly
2. Either Sign into your Firefox account to sync extensions or download uMatrix manually.
3. Go into uMatrix Settings.
4. Go into "My Rules".
5. Click "Import from File".
6. Observe the file extensions that you can import.
7. For me it only says ".bib" and not ".txt"

### Ruleset
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow

### Supporting evidence
This is the "File Import" dialog box on Firefox
Image from Firefox Nightly: https://puu.sh/FC1ET.png
Image from Firefox Stable: https://puu.sh/FC1FO.png

### Your environment

* uMatrix version: uMatrix 1.4.0
* Browser Name and version: Firefox Nightly 77.0a1 (2020-04-24) (64-bit)
* Operating System and version: Windows 10 1909 (OS Build: 18363.778)

**Comment by uBlock-user** [comment]
That's a Windows dialog which uMatrix has no control over. Are you using some bibliography software which you also use to edit text files on your Windows device ?

**Comment by gorhill** [comment]
There is no `bib` anywhere in uMatrix code.

If you set `accept` to `text/plain` in the demo at <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file>, what do you get when you click "Browse..."?

**Comment by OnlinePlayer865** [comment]
> text/plain

I get as the file extension format that I can open "BibTeX File (*.bib)". 
I do not have this issue on my laptop running the latest Nightly. So I will poke around my windows settings. But I do not have this issue on the stable version of Firefox.

**Comment by OnlinePlayer865** [comment]
If it does matter, I am able to select the Dropdown menu to "All Files" and then import the text file from there. So that is an option for me that I can use until I figure it out.

**Comment by gorhill** [comment]
If you can reproduce this outside uBO, then the issue is not in uBO.
