### ISSUE TITLE
Chrome extension keyboard shortcuts

### ISSUE THREAD

**Issue by elig0n** [uBlockOrigin/uMatrix-issues#252]
Under Chrome extensions can have keyboard shortcuts designated in a specific chrome extensions keyboard page ( chrome://extensions/shortcuts )
Right now one can only assign a key to toggle the appearance of the popup, which is basically useless unless #197 or similar is merged.
Additional keybindings for disabling umatrix for the current scope, undoing or saving changes and so on will be very welcome as far as I am concerned.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/678 ?
