### ISSUE TITLE
'no-workers: 1st-party false' is not effective

### ISSUE THREAD

**Issue by theltalpha** [uBlockOrigin/uMatrix-issues#253]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

The setting 'no-workers: 1st-party false' in "My rules" does not show the expected behaviour.

### A specific URL where the issue occurs

https://vorarlberg.orf.at/stories/3046065/

### Steps to Reproduce

1. In "My rules" implement the rules 'no-workers: * true' to block workers globally and 'no-workers: 1st-party false' to relax the global rule and allow workers for first party domains.
2. Open the above mentioned webpage. At the end of the article there is a video.
3. In the switchboard in the 'orf.at' scope allow everything first party and additionally XHR for apasfiis.sf.apa.at in order to load the website correctly. Reload the page.
4. Open uMatrix logger and click on the play button of the video. In the logger you will notice one red entry. The invoking website's domain is vorarlberg.orf.at, its a worker and the blocked element is https://vorarlberg.orf.at/stories/3046065/.

Now, this is strange. The blocked element is first party in regard to the invoking website, but according to the rules this should be allowed. Even if I click on -- the rules are represented correctly in the switchboard:

![screenshot](https://user-images.githubusercontent.com/6757089/80431095-0c61a880-88e0-11ea-8c42-00e46de6c798.jpg)

But the video won't play. Only if I specifically add 'no-workers: orf.at false' as a rule it would play the video.

### Ruleset

As described above.

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox Quantum ESR 68.7.0 (64 Bit)
* Operating System and version: Debian GNU/Linux 10.3 (64 Bit)

**Comment by gorhill** [comment]
> The blocked element is first party in regard to the invoking website, but according to the rules this should be allowed.

The per-scope switches are independent from matrix filtering, they do not inherit their state from matrix filtering rules.

**Comment by uBlock-user** [comment]
That's not a valid rule either, you put `*` or `domain` there.

**Comment by gorhill** [comment]
I don't think it's invalid, the screenshot shows an issue: it shows an `allow` rule for `worker` type. The issue is that the logger is wrong, uMatrix does not support such rule for `worker`. This has [been fixed](https://github.com/uBlockOrigin/uMatrix-issues/issues/62#issuecomment-430251194) in dev build of uMatrix, this is what one get now when clicking on a row with `worker` resource:

![a](https://user-images.githubusercontent.com/585534/80481825-312a4000-8921-11ea-8dd3-44f145805ea2.png)

**Comment by uBlock-user** [comment]
> I don't think it's invalid,

So we can use `1st-party` instead of `*` or the `domain` itself ?

**Comment by gorhill** [comment]
No, not for per-scope switch. I didn't even realize the whole issue was about this.
