### ISSUE TITLE
Show Domains hierarchical to be able to detect dependences between scripts

### ISSUE THREAD

**Issue by Mannshoch** [uBlockOrigin/uMatrix-issues#257]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Many times Scripts are cascaded through several domains. Many time I have to allow a script and after reload a bunch of new scripts appear in uB then I have to allow another script and again a bunch of scripts appear. I do not like it to try unblocking ressources part be part.

### A specific URL where the issue occurs

On fanfiction.net/login.php you need to enable google recapcha.

### Steps to Reproduce

1. Unlock scripts for google.com 
2. Reload
3. Unlock scripts for gstatic.com
   If you try to login, scripts for gstatic.com create a frame to google.com
4. You have to unlock frames and XHR for google.com
5. Now you could log in

### Expected behavior:

- [ ] uMatrix knows that I google.com is addressed with a specific resource the domain gstatic will follow.
  - [ ] uMatrix shows below of google.com gstatic.com as a dependency option
  - [ ] uMatrix shows a mark which tell which resource lead to which domain
  - [ ] uMatrix save this dependency and show them directly on next visit
  - [ ] uMatrix shows learned dependency immediately after revisiting a website. This dependency shows in gray instead of red or green until they are actively requested.

Mockup
![grafik](https://user-images.githubusercontent.com/7795891/81145992-bba11e00-8f77-11ea-9b4a-c6d9f48609f6.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 75
* Operating System and version: Ubuntu 19.10

**Comment by gorhill** [comment]
This involves re-writing large parts of uMatrix, I prefer to decline, and additionally, I do not think it is desirable behavior.
