### ISSUE TITLE
hpHosts’ Ad and tracking servers

### ISSUE THREAD

**Issue by Optivan** [uBlockOrigin/uMatrix-issues#261]
Hi, it looks like this list is no longer maintained but it still present in the Assets tab.
why isnt this being removed or changed to a maintainded version?

Best Regrads

Optivan

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uMatrix-issues/issues/223

**Comment by Optivan** [comment]
> #223

So like i say its discontinued but why it can be picked in the asset tab?
If the is no workaround only to disable the list than remove it ...
