### ISSUE TITLE
Fetches to slack-imgs.com from app.slack.com appear in the logger, but not in the switcher

### ISSUE THREAD

**Issue by FiloSottile** [uBlockOrigin/uMatrix-issues#262]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Fetches to `slack-imgs.com` from `app.slack.com` appear in the logger, but not in the switcher.

This has been the case for as long as I can remember, and something similar only happens on Slack. I've done all sequences of reloading with/without the logger open.

This was reported in #237 but it doesn't look like a resolution was reached.

Adding a rule like the following fixes the site as expected. The issue is that the fetch doesn't appear anywhere in the switcher, whether blocked or not.

```
slack.com slack-imgs.com fetch allow
```

### A specific URL where the issue occurs

https://app.slack.com/client/T029RQSE6/CHQL7VCKU

### Steps to Reproduce

Log in to Slack with a strict ruleset. Access a channel with images.

### Ruleset

```
https-strict: * true
https-strict: behind-the-scene false
matrix-off: 127.0.0.1 true
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * cookie block
* * css allow
* * frame block
* * image allow
* * other block
* * script block
* 1st-party * allow
* 1st-party frame allow
slack.com * script inherit
slack.com 1st-party cookie allow
slack.com slack-edge.com * allow
slack.com slack-msgs.com fetch allow
```

### Supporting evidence

![image](https://user-images.githubusercontent.com/1225294/82862302-4c22ac80-9eed-11ea-8ca4-7da8eb78e1ce.png)

![image](https://user-images.githubusercontent.com/1225294/82862318-547ae780-9eed-11ea-8c4f-4f8f8a0328af.png)

### Your environment

* uMatrix version: 1.4.1b0
* Browser Name and version: Chrome 83
* Operating System and version: macOS 10.15.4

**Comment by uBlock-user** [comment]
_behind-the-scene/tabless_ requests will never appear in the popup panel, only in the logger.

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/82865247-ec0b2500-9f43-11ea-9c2b-ddaaccb24757.PNG)

**Comment by FiloSottile** [comment]
Any docs on what makes a request "behind-the-scene"? Searching the wiki doesn't yield anything.

**Comment by uBlock-user** [comment]
docs haven't been added as it's not actively maintained, but gorhill's explanation - https://github.com/uBlockOrigin/uMatrix-issues/issues/62#issuecomment-423931783

**Comment by gorhill** [comment]
This is a duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/92>.

**Comment by uBlock-user** [comment]
> #92

you mean #62 ?

**Comment by gorhill** [comment]
#92 is correct, morespecifically, [this comment](https://github.com/uBlockOrigin/uMatrix-issues/issues/92#issuecomment-457866811).
