### ISSUE TITLE
"Spoof <noscript> tags" works inverse

### ISSUE THREAD

**Issue by pauschuu** [uBlockOrigin/uMatrix-issues#272]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [/] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description
![umatrix_spoof-noscript-disabled_faz](https://user-images.githubusercontent.com/12713838/85449125-b33c8b00-b597-11ea-8621-599ad75f7cec.png)
![umatrix_spoof-noscript-enabled_faz](https://user-images.githubusercontent.com/12713838/85449128-b3d52180-b597-11ea-93d5-9b2eb3c71899.png)

Enabling the option `Spoof <noscript> tags` leads to a behaviour that one would expect when the option is disabled and vice versa.

### A specific URL where the issue occurs
https://www.faz.net/aktuell/
https://www.bild.de/
_Sorry for these poor examples of press but those are sites where the problem occurs._

### Steps to Reproduce

1. Disable at least `script`s for the example websites
2. **Enable** `Spoof <noscript> tags` for the example websites
3. The websites will show an overlay which is triggered by their noscript tag
4. **Disable** `Spoof <noscript> tags` for the example websites
5. The websites will show their normal contents

### Ruleset
**Basic rulesets:**
```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * cookie block
* 1st-party css allow
* 1st-party image allow
```

**Additional rulesets for testing:**
```
noscript-spoof: bild.de false
noscript-spoof: faz.net false
```

### Your environment

* uMatrix version:
`1.4.0`
* Browser Name and version:
`Google Chrome 83.0.4103.116 (Official Build) (64-bit) (But I remember that I had the same issue on Firefox too)`
* Operating System and version:
`Windows 10.0.19041 Build 19041 (The issue was present when using my Arch Linux too)`

**Comment by gorhill** [comment]
They are spoofed, the browser does not render them, it's uMatrix rendering them using `span` tags.

**Comment by pauschuu** [comment]
In other words blocking scripts using uMatrix does not trigger the typical noscript behavior a browser would normally show? Hence the option is to restore the original noscript behavior. 

So this is working as expected as I see it now. Closing the issue now.

Maybe link the "i" next to the `Spoof <noscript> tags` to a documentation that clarifies this instead of linking it to the more general Mozilla Developer page. Meant as a humble suggestion.
