### ISSUE TITLE
Where to send pull requests?

### ISSUE THREAD

**Issue by elig0n** [uBlockOrigin/uMatrix-issues#273]
When trying to send a pull requests [the old repo ](https://github.com/gorhill/uMatrix/)is showing `An owner of this repository has limited the ability to open a pull request to users that have contributed to this repository in the past.`  while in this repo one cannot send pull requests simply because the distribution's code does not exist in it.

**Comment by gwarser** [comment]
Crete issue here explaining what is your problem and how you want to resolve it.

**Comment by elig0n** [comment]
I woild like to suggest a pull request with vim keyboard feature from girst: https://github.com/girst/uMatrix/tree/pr-keyboardnav

 @gorhill
