### ISSUE TITLE
Access to localStorage blocked for in 3rd party context

### ISSUE THREAD

**Issue by Kein** [uBlockOrigin/uMatrix-issues#274]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Access to localStorage blocked for in 3rd party context

### A specific URL where the issue occurs

discord.com

### Steps to Reproduce

1. Run Discord in browser
2. Disable matrix for domain
3. Try to play any embed Twitch clip

### Ruleset

N/A, uMatrix disabled, web-workers allowed (rest of the setting max allowance)

### Supporting evidence

```js
player-main-a60a54700d8681907841.js:1 Failed to get log level override from local storage. {err: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this d…, key: "twilight.minConsoleLogLevel"}err: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (https://static.twitchcdn.net/assets/player-main-a60a54700d8681907841.js:1:203860)
    at Se (https://static.twitchcdn.net/assets/player-main-a60a54700d8681907841.js:1:201825)
    at Module.gg62 (https://static.twitchcdn.net/assets/player-main-a60a54700d8681907841.js:1:1467827)
    at m (https://player.twitch.tv/?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1:4294)
    at Object.246 (https://static.twitchcdn.net/assets/player-main-a60a54700d8681907841.js:1:154199)
    at m (https://player.twitch.tv/?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1:4294)
    at i (https://player.twitch.tv/?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1:4155)
    at Array.e [as push] (https://player.twitch.tv/?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1:4018)
    at https://static.twitchcdn.net/assets/player-main-a60a54700d8681907841.js:1:47key: "twilight.minConsoleLogLevel"__proto__: Object
e @ player-main-a60a54700d8681907841.js:1
Se @ player-main-a60a54700d8681907841.js:1
gg62 @ player-main-a60a54700d8681907841.js:1
m @ ?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1
246 @ player-main-a60a54700d8681907841.js:1
m @ ?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1
i @ ?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1
e @ ?channel=systemarcadia&player=facebook&autoplay=1&parent=meta.tag&auto_play=1:1
(anonymous) @ player-main-a60a54700d8681907841.js:1
04:16:57.240 player-main-a60a54700d8681907841.js:1 4:16:57 AM [ERROR] Uncaught error. DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

### Your environment

* uMatrix version: 1.4.1b6
* Browser Name and version: Chromium Ungoogled 83.0.4103.61 
* Operating System and version: Win7x64

**Comment by uBlock-user** [comment]
Blocking third-party cookies/storage causes this. Are you blocking third-party cookies/storage ?

**Comment by gorhill** [comment]
I don't see any errors in there that I can link to uMatrix.

Blocking 3rd-party cookies/data in the browser preferences will cause this.

**Comment by Kein** [comment]
No 3rd party cookies are blocked by browser, cookies are managed by uMatrix, I've assumed that disabling uMatrix for domain should disable cookie restrictions imposed by uMatrix as well? Is that not the case?

**Comment by uBlock-user** [comment]
Only outgoing cookies are blocked by uMatrix.

**Comment by Kein** [comment]
Okay? That does not explain why the error persist unless uMatrix is uninstalled though ¯\\\_(ツ)\_\/¯

**Comment by gorhill** [comment]
Your repro steps are problematic, they assume whoever is interested in trying to reproduce knows anything about Discord. I don't. I loaded `https://discord.com` in the browser, clicked _"Open Discord in your browser"_, and I don't see any embedded Twitch video.

**Comment by liamengland1** [comment]
> Your repro steps are problematic, they assume whoever is interested in trying to reproduce knows anything about Discord. I don't. I loaded `https://discord.com` in the browser, clicked _"Open Discord in your browser"_, and I don't see any embedded Twitch video.

I made a test server: `https://discord.gg/pp3fnhR`

**Comment by gorhill** [comment]
Thanks.

Starting from default ruleset, I create these rules and I could play the embedded Twitch video fine:

    discord.com d3gdm2urgmeunj.cloudfront.net * allow
    discord.com discord.gg * allow
    discord.com discord.media * allow
    discord.com twitch.map.fastly.net * allow
    discord.com twitch.map.fastly.net frame allow
    discord.com twitch.tv * allow
    discord.com twitch.tv frame allow
    discord.com twitchcdn.net * allow
    discord.com twitchsvc.net * allow

Using Firefox 77, set _"Enhanced Tracking Protection"_ set to _"Standard"_.

**Comment by uBlock-user** [comment]
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

> why the error persist unless uMatrix is uninstalled though

Can you reproduce this on Chrome/Chromium, if not, then it's a ungoogled chromium issue.
