### ISSUE TITLE
Dashboard fails to display proper blocked counter

### ISSUE THREAD

**Issue by Kein** [uBlockOrigin/uMatrix-issues#276]
I tried searching issues but could not find anything relevant for the common keywords I've used and I have no idea if a similar issue was submitted with some obscure keywords. Domain search also did not return any hits.

### Prerequisites
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix extension is wholly disabled or not installed
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

No dashboard counter data for requested resources.

### A specific URL where the issue occurs

https://mail.yandex.ru

### Steps to Reproduce

1. Reset all to defaults, make sure web-workers on.
2. Go to https://mail.yandex.ru
3. Enable first-party scripts, if not enabled
4. Reload and check dashboard - it does not indicate any `script` requests to https://yastatic.net
5. Check the logger and you can see there are requests made to https://yastatic.net/ which are blocked

### Ruleset
All default.

### Supporting evidence
![image](https://user-images.githubusercontent.com/623756/86417107-b3920000-bcd4-11ea-87dd-be71f247c04a.png)
![image](https://user-images.githubusercontent.com/623756/86417113-b68cf080-bcd4-11ea-9fad-0c6c4c378446.png)

### Your environment

* uMatrix version: 1.4.1b0-devel
* Browser Name and version: Vivaldi 3.1/Chromium 83.0
* Operating System and version: windows7x64

___________________________________________________________________

I **understand** that the issue technically could be solved by taking a look at the logger and adding necessay rules, but as I understood, using basic logic and common sense, uMatrix dashboard was developed to be able to make rules on the fly and to avoid going through few thousands log lines per day.

**Comment by gorhill** [comment]
I am unable to reproduce in Chromium 83/uMatrix 1.4.1b6.

**Comment by Kein** [comment]
Not sure what to say, I've managed to repro it just now in VM, clean Windows and clean Vivaldi 3.1 installation.
Haven't tried Chromium yet, will update.

**Comment by gorhill** [comment]
Can you try with 1.4.1b6? Vivaldi is not officially supported. If it works in Chromium and not Vivaldi, then this needs to be reported to Vivaldi devs.

**Comment by Kein** [comment]
1.4.1b6 detected it first try even on Vivaldi (not gonna test Chromium then), my bad, should have used latest devel, Chrome store one was b0.

**Comment by gorhill** [comment]
> Chrome store one was b0

Yes, I realized that with your issue. I pushed b6 to the Chrome store yesterday -- currently pending review, this may takes long before it's cleared.
