### ISSUE TITLE
Placeholder iframe not shown on particular site using Firefox

### ISSUE THREAD

**Issue by xofe** [uBlockOrigin/uMatrix-issues#28]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### A specific URL where the issue occurs

http://lyrics.wikia.com/wiki/Florence_%2B_The_Machine:Hunger

### Steps to Reproduce

1. Open Firefox 60 or later (using a clean profile) and install uMatrix 1.1.20 or later.
2. Add the rule `wikia.com nocookie.net * allow` to the 'My rules' section in the dashboard. (Without this rule, the site will appear broken)
3. Visit the URL above.
4. Notice that the usual iframe placeholder document for the YouTube video embed at the top right of the grey lyrics box (an iframe from `www.youtube-nocookie.com`, which is blocked) is not shown.

### Supporting evidence

This only affects Firefox 60 or later when used with uMatrix 1.1.20 or later. The issue isn't present when using Firefox 59 or older with the current version of uMatrix, or when using uMatrix 1.1.18 or older with the current version of Firefox. Because of this, I'm not certain whether this is a Firefox or uMatrix issue.

For Firefox, `moz-regression` gives [a regression range](https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=c842abb7cfbf39e0c1cfb9a1f3a1d6415cd10744&tochange=84ea422093dd615bd191a3e579ed299d96c802f1) that points to [Bug 1193394](https://bugzilla.mozilla.org/show_bug.cgi?id=1193394).

For uMatrix, `git bisect` says https://github.com/gorhill/uMatrix/commit/73c8da05b7592e8d26a2cfd3892c8598d9e70141 is the culprit.

Screenshot of last good revision (https://github.com/gorhill/uMatrix/commit/8615f3b8040c84cb21a5f9cec33d2691f7581334) on Firefox 60.0.2 :
![Screenshot whit placeholder shown](https://user-images.githubusercontent.com/22776566/42329519-5a9de67e-8060-11e8-9452-0ab46d6e0fb1.png)
Screenshot of first bad revision (https://github.com/gorhill/uMatrix/commit/73c8da05b7592e8d26a2cfd3892c8598d9e70141) on Firefox 60.0.2 :
![Screenshot whit placeholder missing](https://user-images.githubusercontent.com/22776566/42329530-6215ad56-8060-11e8-9883-2e56a60d38ed.png)

### Your environment

* uMatrix version: 1.3.10
* Browser Name and version: Firefox 60.0.2

**Comment by uBlock-user** [comment]
I can reproduce on Nightly.

**Comment by uBlock-user** [comment]
Make sure you have disabled _Collapse placeholder of blocked elements_ and _Collapse placeholder of blacklisted elements_ from the Settings menu.

**Comment by gorhill** [comment]
I can reproduce. Appears to be a timing issue, when I stepped into the javascript code, the placeholder appeared properly.

**Comment by xofe** [comment]
Confirmed fixed. Thanks!
