### ISSUE TITLE
Support Firefox for Android 79

### ISSUE THREAD

**Issue by davidovitch** [uBlockOrigin/uMatrix-issues#283]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix extension is wholly disabled or not installed
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

I've been happily running Firefox Android (68.11 wast the latest) with uMatrix for longer than a year. A few weeks ago I migrated to the redesigned Firefox for Android 79, some background info:
* https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs
* https://www.ghacks.net/2020/07/29/firefox-79-for-android-tweaks-and-tips/
* https://www.xda-developers.com/mozilla-firefox-79-for-android-preview-nightly-update-without-extensions-add-ons/

Due to this complete overhaul only very few extensions work with the new Firefox for Android at this moment, and unfortunately, uMatrix is not one of them. I have not been able to locate resources (yet) from Mozilla outlining what extensions should conform to in order to support Firefox for Android 79+.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. update/migrate to Firefox for Android 79
2. got to `settings > add-ons`
3. find uMatrix under the `Not yet available` category

### Ruleset

N/A

### Supporting evidence

N/A

### Your environment

* uMatrix version: 1.4.0
* Firefox 79.0.2
* FairPhone 2 running Android 7.1.2

**Comment by ghost** [comment]
Nothing we can do. Available extensions are chosen by Mozilla

- https://www.reddit.com/r/firefox/comments/hz3a7m/firefox_for_android_68110_is_the_final/
- https://blog.mozilla.org/addons/2020/07/07/new-extensions-in-firefox-for-android-nightly-previously-firefox-preview/
- https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

**Comment by michaelblyons** [comment]
Maybe pin this issue? I imagine there will be more and more people coming here to check on this as their phones update.

*__Edit:__ As a tentative workaround, I'm using uBlock Origin in [Hard Mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode).*

**Comment by nkeeer** [comment]
Hi all,
i really LOVE umatrix. Are there any plans that the umatrix community will work together with Mozilla on "enabling" umatrix again for the new Android Firefox release?
What are the requirements of Mozilla in order to get umatrix whitelisted for Android Firefox?

PLEASE have a look (sry I'm not a developer, therefore I'm not able to support on that case - i'm just a happy umatrix enduser).

Thanks in advance!
