### ISSUE TITLE
Top domain level rules overwriting domain level rules.

### ISSUE THREAD

**Issue by raelianer** [uBlockOrigin/uMatrix-issues#287]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix extension is wholly disabled or not installed
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [X] I used the logger to rule out that the issue is caused by my ruleset

### Description

On https://www.carbonbrief.org/explainer-nine-tipping-points-that-could-be-triggered-by-climate-change the picture https://tomprater.github.io/tipping-points/ai2html/tipping-points-retina-Artboard_1.png is blocked even though I allow tomprater.github.io and ajax.googleapis.com for the scope of carbonbrief.org. When I allow ajax.googleapis.com for the scope of .org it works as intended.

### A specific URL where the issue occurs

https://www.carbonbrief.org/explainer-nine-tipping-points-that-could-be-triggered-by-climate-change

### Steps to Reproduce

1. Allow tomprater.github.io and ajax.googleapis.com for the scope of carbonbrief.org-> does not work as intended
2. Allow ajax.googleapis.com for the scope of .org -> works

### Ruleset
	
	https-strict: behind-the-scene false
	matrix-off: about-scheme true
	matrix-off: behind-the-scene true
	matrix-off: chrome-extension-scheme true
	matrix-off: chrome-scheme true
	matrix-off: moz-extension-scheme true
	matrix-off: opera-scheme true
	noscript-spoof: * true
	referrer-spoof: * true
	referrer-spoof: behind-the-scene false
	referrer-spoof: facebook.com false
	* * * block
	* * frame block
	* 1st-party * allow
	* 1st-party css allow
	* 1st-party frame allow
	* 1st-party image allow
	carbonbrief.org tomprater.github.io * allow
	carbonbrief.org tomprater.github.io cookie block
	
	carbonbrief.org tomprater.github.io frame allow
	org ajax.googleapis.com * allow
	org ajax.googleapis.com cookie block

### Supporting evidence

This is working, although it should be enough to allow it on the specific domain:
![image](https://user-images.githubusercontent.com/836288/91156463-78a0bd00-e6c4-11ea-89cf-680fba722c82.png)
![image](https://user-images.githubusercontent.com/836288/91156553-90784100-e6c4-11ea-9116-d12b81585579.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Chrome 84.0.4147.135 (Offizieller Build) (64-Bit)
* Operating System and version: Windows 10 Home, Version 1903, Build: 18362.1016

**Comment by gorhill** [comment]
Allowing `ajax.googleapis.com` on `carbonbrief.org` worked fine for me.

I am going to close as invalid because the claim that `org ajax.googleapis.com` overrides `carbonbrief.org ajax.googleapis.com` is an extraordinary one, this can't happen. There is no other reports of such issue, the best explanation is elsewhere. No logger output is mentioned and not all checkboxes have been checked in the template.

**Comment by raelianer** [comment]
Works now with these settings. I don't know what changed.
