### ISSUE TITLE
uMatrix doesn't forbid mixed content.

### ISSUE THREAD

**Issue by isowhe** [uBlockOrigin/uMatrix-issues#3]
### Prerequisites

* [x] Did you perform a cursory search of the issue tracker?
    * Your issue may already be reported.
* Can you reproduce the problem when...
    * [x] uMatrix is the only extension?
    * [x] uMatrix with default lists/settings?
    * [x] using a new, unmodified browser profile?
* [x] Are you running the latest version?
* [x] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

Doesn't block mixed content.

### A specific URL where the issue occurs

    https://kg-portal.ru/

### Steps to Reproduce

1. Go the link.
2. Forbid mixed content.
3. Refresh.

### Expected behavior:

To block mixed content.

### Actual behavior:

Mixed content is loaded.

### Your environment

* uMatrix version: 1.3.6
* Browser Name and version: 59.0.2
* Operating System and version: Windows 10 1709

**Comment by uBlock-user** [comment]
Tested on these two cases with same results, uMatrix blocks all mixed content.

```
https://www.bennish.net/mixed-content.html
https://files.hackerific.net/test.html
```

**Comment by gorhill** [comment]
Also unable to reproduce:

![a](https://user-images.githubusercontent.com/585534/39094245-8eb0e042-45fa-11e8-8c5b-2002239b04e7.png)

This issue should be deemed invalid, @isowhe did not provide any supporting evidence (just @uBlock-user and me we did here,) there is zero details about how he came to the conclusion that mixed content was not blocked.

**Comment by isowhe** [comment]
@gorhill > there is zero details about how he came to the conclusion that mixed content was not blocked.
Sorry, browser showed me this and i didn't checked logger. https://a.pomf.cat/rfeqgp.png

**Comment by uBlock-user** [comment]
> https://a.pomf.cat/rfeqgp.png

That's independent of the extension and has nothing to do with uMatrix. Browser itself does detect and notify you but doesn't block, which doesn't imply that uMatrix is not doing its job at all.
