### ISSUE TITLE
Stripe + uMatrix

### ISSUE THREAD

**Issue by anelder-stripe** [uBlockOrigin/uMatrix-issues#32]
Hey,

While this issue relates indirectly to broken sites, I wanted to file in case you had any recommendations.  It seems that uMatrix blocks any requests made by Stripe's (https://stripe.com/) Javascript.

We're happy to work with you to make minor adjustments to the scripts in order to allow them to work out-of-the-box, if necessary; however, it's not obvious why they're breaking (or if it's just the nature of the uMatrix plugin).

http://fiddle.jshell.net/yn56Lebv/2/show/

Can you please clarify why this might be occurring and/or if it's expected?

Thank you very much!

**Comment by uBlock-user** [comment]
uMatrix doesn't have any filterlists like blacklist or whitelist, it's completely left to the users to create their own ruleset.

> or if it's just the nature of the uMatrix plugin

Yes exactly, it runs on default-deny out of the box. You will have to create ruleset to whitelist specific categories(script, XHR, frame) etc.

**Comment by ArchangeGabriel** [comment]
As a side-note, [rules can be proposed](https://github.com/uBlockOrigin/uAssets/blob/master/recipes/recipes_en.txt) (but still need to be activated by the final user). In my experience though Stripe resources requirements change from site to site. Here is a MWE for KS:
```
kickstarter.com api.stripe.com xhr allow
kickstarter.com js.stripe.com frame allow
kickstarter.com js.stripe.com script allow
```

**Comment by ArchangeGabriel** [comment]
(Note that Stripe tried to load other resources, including from `stripe.network`, which I’ve left blocked but did not affect the functionality)

**Comment by uBlock-user** [comment]
@ArchangeGabriel Rulesets are for unbreaking a particular website so newbies don't have to do it on their own. In this case, they want to add their domain to a whitelist in uMatrix, so uMatrix doesn't block it anywhere regardless of ruleset or scope, which is not the purpose of uMatrix in the first place.

**Comment by ArchangeGabriel** [comment]
I know they would want a default whitelisting and that this won’t happen, I’m just saying that if they want it to be easier to unbreak, a minimal working ruleset should be the way to go.

**Comment by anelder-stripe** [comment]
@uBlock-user + @ArchangeGabriel - I'm actually comfortable with the recipe approach and I've gone ahead and built one that I've tested on my own machine here.

I think the important thing is that we have something an average user can use to "just make it work" when they need.  I don't want to to whitelist us across the board and undermine the purpose of the software.  That's not our intention.  We just want to fix it on a site-by-site basis when the user expects to be able to use it.
