### ISSUE TITLE
Ruleset recipes dynamically incorporated into rules

### ISSUE THREAD

**Issue by siroccal** [uBlockOrigin/uMatrix-issues#33]
### Description

It would be nice for rules to be dynamically dependent on recipes. Instead of saving many rules per domain, only the enabled ruleset recipes would be saved. Changes in the ruleset recipes would propagate to the rules for the domain.
For example, on reddit.com and BBC.com one could enable/disable a (custom) ruleset recipe for YouTube.com to allow/block it. Changing the YouTube ruleset recipe would then also affect how YouTube loads on reddit and BBC.
I think this would make maintaining/changing rules easier and more manageable.

### Your environment

* uMatrix version: 1.3.12
* Browser Name and version: Firefox 61.0.1
* Operating System and version: Arch Linux 4.14.56-1-lts x64 (2018-07-20)

**Comment by gorhill** [comment]
Recipes are never automatically imported, I do not intend to change this.

**Comment by siroccal** [comment]
This would only apply to recipes that have been manually enabled per domain.
What do you mean exactly by "automatically imported"?

**Comment by gorhill** [comment]
Recipes are not "enabled", they are just collection of rules to be imported. Once the rules are imported, they are yours. It's all in [the documentation](https://github.com/gorhill/uMatrix/wiki/Ruleset-recipes):

> Recipes are never automatically imported, they always require that you explicitly import them -- and hopefully after you look at what rules the recipe contains. You may inspect all the rules by expanding the recipe.

**Comment by siroccal** [comment]
Yeah, but that wouldn't apply to the feature I'm proposing. In that feature, recipes can be enabled/disabled, not "imported". Rules would then depend (dynamically) on the recipes.
I realize I'm proposing a rather big change in how rules/recipes work (together), and that this feature would be quite a bit of work.
