### ISSUE TITLE
Update http://someonewhocares.org/hosts/hosts to use https

### ISSUE THREAD

**Issue by lightswitch05** [uBlockOrigin/uMatrix-issues#36]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Updated source list to use https instead of http. The http version just responds with a 302 redirect to the secure version. This removes the extra redirected request.

Pull request: https://github.com/gorhill/uMatrix/compare/master...lightswitch05:patch-1

**Comment by gorhill** [comment]
I [merged your changes](https://github.com/gorhill/uMatrix/pull/1003), thanks.

However for unknown reason the [commit history](https://github.com/gorhill/uMatrix/commits/master) does not show you as the author. Sorry about this, next time I will just temporarily open the repo to accept PRs.

**Comment by lightswitch05** [comment]
@gorhill thanks, just happy to have more sites supporting https 👍

**Comment by uBlock-user** [comment]
Same change needs to happen in [assets.json](https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L258) in uBO too.
