### ISSUE TITLE
Allow or deny rules within the popup panel without refreshing

### ISSUE THREAD

**Issue by zero77** [uBlockOrigin/uMatrix-issues#4]
Is it possible to allow or deny rules within the pop-up menu without having to refresh the page, If so can you please Implement this.
Thanks

**Comment by uBlock-user** [comment]
> Is it possible to allow or deny rules within the pop-up menu without having to refresh the page

No and this is not the way to post here, you completely bypassed the template which you were not supposed to do.

**Comment by gorhill** [comment]
@zero77 you have a history of disrespecting issue tracker, please respect the issue tracker here, or refrain from opening issue. What you ask here makes absolutely no sense, you did not make any effort to make yourself understood after you bypassed the template.
