### ISSUE TITLE
Firefox 56: uMatrix window cut off on the right side

### ISSUE THREAD

**Issue by namarrgon** [uBlockOrigin/uMatrix-issues#4]
The screenshot is from a clean firefox profile, only umatrix was added. The width isn't fixed, sometimes more is cut off, sometimes less. This happens on windows and linux.

![2017-10-05-143710_1164x1156_scrot](https://user-images.githubusercontent.com/3209906/31227675-07eb2e7a-a9db-11e7-880c-e935bcabc8dc.png)

**Comment by gorhill** [comment]
It's a side-effect of Photon. Use the webext version in the dev channel on AMO.
