### ISSUE TITLE
Cannot block scripts on web.telegram.org (offline web app?) after enabling them.

### ISSUE THREAD

**Issue by sourcejedi** [uBlockOrigin/uMatrix-issues#42]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

web.telegram.org retains <script> permission *permanently*.

### A specific URL where the issue occurs

https://web.telegram.org/#/login

### Steps to Reproduce

1. follow https://github.com/gorhill/uMatrix/wiki/How-to-block-1st-party-scripts-everywhere-by-default
2. visit https://web.telegram.org/#/login
3. temporarily allow, and refresh.  The login page loads, looking very javascripty.  Selecting a country will populate the country code field.
4. close browser
5. visit https://web.telegram.org/#/login.  The login page loads, looking very javascripty.  Selecting a country will populate the country code field.

### Supporting evidence

Really sorry, but printscreen button on my computer causes the popup panel to disappear.  So here are screenshots including the rules list instead.

![screenshot from 2018-08-10 17-52-07](https://user-images.githubusercontent.com/14057/43970689-4fc74588-9cc6-11e8-889f-044ae191f185.png)

### Your environment

* uMatrix version: 1.3.12
* Browser Name and version: Firefox 61.0.1
* Operating System and version: Fedora Workstation 28

**Comment by uBlock-user** [comment]
I'm seeing `behind-the-scene` network requests being performed.

![](https://i.gyazo.com/5b311490e433354a75ea729991827129.png)

**Comment by uBlock-user** [comment]
Remove any active service-worker registered in `chrome://serviceworker-internals/` and block `behind-the-scene` network requests that will do it.

**Comment by uBlock-user** [comment]
Same issue with uBO too, adding a filter like `||$csp=worker-src 'none',important` doesn't get applied and uBO can't seem to detect worker there either.

**Comment by gorhill** [comment]
> close browser
> visit https://web.telegram.org/#/login. The login page loads, looking very javascripty. Selecting a 
country will populate the country code field.

Extensions are not guaranteed to run before web page loads at browser launch time.

**Comment by gorhill** [comment]
Also, mind browser setting _"Continue running background apps when Chromium is closed"_.

**Comment by uBlock-user** [comment]
@gorhill uMatrix seems not be able to block `behind-the-scene` requests on this website.

![](https://i.gyazo.com/68e077a90e745831efefed817b45c4f4.png)

**Comment by gorhill** [comment]
These are not literally behind-the-scene as in "no tab, no origin". They do have a origin and are filtered according to this. I keep mentioning this, like [here](https://github.com/uBlockOrigin/uMatrix-issues/issues/39#issuecomment-410065260).

**Comment by uBlock-user** [comment]
I don't understand. If they're filtered and have origin, then why aren't they getting blocked ?

**Comment by gorhill** [comment]
> why aren't they getting blocked ?

Looks like a new thing (at least for me): the resources are loaded from "Application Cache". In such case, uMatrix's onHeadersReceived is not called, and hence uMatrix can't control inline javascript, workers, etc. You can see the content of the Application Cache in dev tools => Application => Application Cache. I tried to delete it through the Cookies UI, does not work. So I will have to educate myself about what is all this Application Cache thing which bypass uMatrix.

**Comment by uBlock-user** [comment]
> Application Cache thing which bypass uMatrix.

uBO also seems to be suffering from this, as I mentioned in my previous [uBO post](https://github.com/uBlockOrigin/uMatrix-issues/issues/42#issuecomment-412151399)

**Comment by uBlock-user** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) It's deprecated and removed from Web Standards, I suppose this is why Firefox is not affected by this.

The way it works is it seemingly creates resources(workers for example) offline, which is why I think, uBO and neither uMatrix are able to detect workers and the console also reports  as `Offline worker registered`.

**Comment by gwarser** [comment]
Despite they are `behind-the-scene`, their context is `web.telegram.org`

![image](https://user-images.githubusercontent.com/886325/43994964-13104d7a-9da6-11e8-8c4a-050a827fe74a.png)

Try `web.telegram.org * * block`

also `service_worker.js$domain=web.telegram.org` works fine.

**Comment by uBlock-user** [comment]
> Despite they are behind-the-scene, their context is web.telegram.org

Exactly, uBO/uMatrix sees it as `behind-the-scene`  but they're not `behind-the-scene`, that's why I think `behind-the-scene` rules are not having any effect.

**Comment by gwarser** [comment]
I think `behind-the-scene` should be called now "`orphaned-behind-the-scene`"

**Comment by gwarser** [comment]
I can reproduce this easily, but only if I configure browser to restore previous session on startup and keep page open. Popup shows scripts blocked but page still works. Simple refresh does not help, ctrl+f5 helps only temporarily. I close this tab now, and restore (Undo Closed Tab from right click menu on tab bar) page loads again. New tab -> right click -> "Paste & Go" -> page loads. Keeps loading from cache no mater what, only way to fix it is to clear cache (ctrl+shift+del).

**Comment by uBlock-user** [comment]
What you're reproducing is that AppCache getting downloaded  as a `$other` category of request, and the loading the app offline, with workers, scripts etc.. JavaScript is still blocked with `* * script block` rule, but not when Javascript is loaded offline via AppCache which is a different issue.
