### ISSUE TITLE
Please adjust the popup text to accomodate larger fonts.

### ISSUE THREAD

**Issue by bhrgunatha** [uBlockOrigin/uMatrix-issues#44]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

I changed Firefox's default font size to 18px (poor eyesight) and the the uMatrix popup display is squashed, it **is** readable but missing some text. 

### A specific URL where the issue occurs

All.

### Steps to Reproduce

1. In Firefox open about:preferences 
1.  Click General 
1.  Under Language and Appearance, Fonts & Colours
1. Change default:  Font: Default (Bitstream Veras Sans) - Size  : 18
    1. Click Advanced...  
    1. Fonts for: Latin 
    1. Proportional : Sans Serif  Size: 18
    1. Serif : Georgia  
    1. Sans Serif : Default (Bitstream Veras Sans)
    1. Monospace: Droid Sans Mono Slashed : Size 16 
    1. Minimum Font size: 18

1. Click uMatrix icon on Firefox extension bar  

### Supporting evidence

[Screenshot](https://i.imgur.com/Inm694J.png).

### Your environment

* uMatrix version: 1.3.12
* Browser Name and version: Firefox 61.0.2
* Arch linux: 4.17.13-arch1-1-ARCH x86_64 

---

I understand this is a cosmetic issue and it's hard to cope with all devices and screens, but any improvement is welcome. 
Thanks.

**Comment by bhrgunatha** [comment]
Sorry about that. 
I've updated the post to include those steps - It's the minimum font size that's causing the issue.

**Comment by uBlock-user** [comment]
I can reproduce now. This is most likely a browser behaviour as by setting _Minimum Font Size_, the rule is being enforced by the browser on the extension popup UI too. I will tag this issue as enhancement for gorhill to address.

**Comment by uBlock-user** [comment]
As a workaround, you can lower the size of _Minimum Font Size_ to `13` and it won't happen.

**Comment by uBlock-user** [comment]
You can lower the size of _Minimum Font Size_ to `14` and it won't happen.

**Comment by gorhill** [comment]
Try to set the setting "Test size" to maximum in uMatrix's dashboard.

**Comment by uBlock-user** [comment]
That works, uBO is also affected by this Minimum Font Size setting. Setting `popupFontSize` to 18 or above works as a workaround.

**Comment by bhrgunatha** [comment]
text size :  maximum in uMatrix dashboard settings indeed works. 
Now I'm embarrassed to not have seen that setting, but very happy it's there :)  
Thanks.
