### ISSUE TITLE
What's wrong with idealo.fr ?

### ISSUE THREAD

**Issue by WagnerGMD** [uBlockOrigin/uMatrix-issues#46]
### Description :

As you can see on the both picture : 

- [the first one](https://nsa39.casimages.com/img/2018/09/01/180901110113962081.png) 
- and [the second](https://nsa39.casimages.com/img/2018/09/01/180901110113946352.png)

For the record the url is : 
```
1) https://www.awin1.com/pclick.php?p=22296837511&a=269861&m=12665
2) https://www.awin1.com/pclick.php
3) Where is the safe (or clean) link ? It's missing...
```
Apparently, the addon doesn't seem to handle (or understand etc) because it's block the both pages.
That's why I'm wonder if you could improve uMatrix on this part ?

### Steps to Reproduce :

1. Search one product on the website **idealo** (and if you need [one example](https://www.idealo.fr/prix/6167839/samsung-addwash-wf16j6500ev.html))
2. Click on the button green called "Voir l'offre" (website **fnac.com**)
3. At the end, you should find [the product](https://www.fnac.com/mp30883766/Samsung-WF16J6500EV-machine-a-laver-chargement-frontal-pose-libre-metal-gris/w-4) (or provide the good link (no **UTM**, etc) !

### Your environment

* uMatrix version: **1.3.12**
* Browser Name and version: Firefox_v62_x64
* Operating System and version: Windows 10 2016 LTSB (v1607 x64)

**Comment by uBlock-user** [comment]
> Click on the button green called "Voir l'offre" (website fnac.com)

Clicking on that redirected me to  `https://www.awin1.com/pclick.php?p=22025267799&a=269861&m=6901` which is blocked by HOSTS file. Nothing's wrong.

**Comment by uBlock-user** [comment]
> you should find the product (or provide the good link (no UTM, etc)

That's not uMatrix's job to do.

**Comment by gorhill** [comment]
I don't understand the issue. `awin1.com` is in one of the hosts file, so the page was blocked. If you don't agree with this, just remove the block rule from `awin1.com`.

**Comment by uBlock-user** [comment]
I think he's asking for uMatrix find the real link which must be at `https://www.fnac.com/mp30883766/Samsung-WF16J6500EV-machine-a-laver-chargement-frontal-pose-libre-metal-gris/w-4` and redirecting the user there...

**Comment by gorhill** [comment]
> you should find the product (or provide the good link

That makes no sense, uMatrix is in no position to guess where the `awin1.com` server will redirect, it  does not have access to the server's internal data. The fact that uMatrix offers to parse/decompose what it can see is for convenience only, it's in no position to know more than what it is given, one single URL.

**Comment by uBlock-user** [comment]
> Then could you explain me this ? 

> The fact that uMatrix offers to parse/decompose what it can see is for convenience only, it's in no position to know more than what it is given, one single URL.

**Comment by uBlock-user** [comment]
> You can't give even a little explanation ?
> Why it was block ?
> Which hosts file cause the trouble ?

Because it's an ad-serving domain as I mentioned earlier already, read again. Specific HOSTS file which is blocking it, is not mentioned by uMatrix, so no I can't give you that as it requires me to go on a goose chase.

**Comment by gorhill** [comment]
> Which hosts file cause the trouble ?

This is <https://github.com/gorhill/uMatrix/issues/526>.

To bypass a blocked page: <https://github.com/gorhill/uMatrix/wiki/How-to-get-past-%22uMatrix-has-prevented-the-following-page-from-loading%22>.
