### ISSUE TITLE
Potentially Devistating Security Flaw/Backdoor: Umatrix depreciates & Forces unsafe TLS Ciphers in Firefox, Chrome, and Waterfox according to SSLlabs tests

### ISSUE THREAD

**Issue by rugabunda** [uBlockOrigin/uMatrix-issues#52]
### Prerequisites

- [check] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [check] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [check] uMatrix is the only extension
    - [check] uMatrix with default lists/settings
    - [check] using a new, unmodified browser profile
- [check] I am running the latest version of uMatrix
- [check] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Umatrix enables disabled, and depreciated ciphers; potentially a massive security problem. Around the same time I've also experienced tonnes of ERR_SSL_VERSION_INTERFERENCE errors, 5 out of 10 TLS connections fail.

### Steps to Reproduce

1. Set Chrome and Firefox to use Tls1.2-Tls1.3 strictly!
2. Simply Enable Umatrix
3. goto https://www.ssllabs.com/ssltest/viewMyClient.html and see the depreciated ciphers detected
4. Disable Umatrix & Try again. Note browser reports correctly safe and secure browser specified ciphers.

Forced entries includie ssl3, Tls1.0, Tls1.1.

Looks like a devistating security flaw! BE CAREFUL with your online banking PEOPLE!

### Supporting evidence

Umatrix Enabled: https://image.ibb.co/ide4fU/Umatrix_Enabled.png
Umatrix Disabled: https://image.ibb.co/hWhPfU/Umatrix_Disabled.png

### Your environment

* uMatrix version: Latest 1.3.14
* Browser Name and version: Latest Firefox / Waterfox / Chromium, same issue in all.
* Operating System and version: Windows 7

**Comment by rugabunda** [comment]
Australia To Push For Encryption Backdoors At Next 'Five Eyes' Meeting https://www.techdirt.com/articles/20170625/07135037660/australia-to-push-encryption-backdoors-next-five-eyes-meeting.shtml

**Comment by rugabunda** [comment]
Cannot submit an issue on here https://github.com/uBlockOrigin/uMatrix-issues/issues
unless you contributed to this backdoor enabling app in the past.

**Comment by uBlock-user** [comment]
uMatrix has nothing to do with enabling anything regarding SSL/TLS, whether you enable or disable uMatrix, TLS 1.0/1.1 remains enabled on Chromium.

**Comment by rugabunda** [comment]
You again are incorrect yet again. Commadnline   --ssl-version-min=tls1.2 enforces tls1.2... 

The exact same issue is occuring in Waterfox and Chrome also.

**Comment by gwarser** [comment]
Unblock cloudflare scripts.

**Comment by uBlock-user** [comment]
> Commadnline --ssl-version-min=tls1.2 enforces tls1.2

uMatrix has nothing to do with it.

**Comment by rugabunda** [comment]
gwarser could you elaborate on that a bit, Umatrix is responsible, here it is in action

https://vimeo.com/289712821

**Comment by rugabunda** [comment]
You are the same moron denying the facts over here: https://github.com/henrypp/chromium/issues/47
Time for whoever runs this microsofthub to look for saner staff.
 https://vimeo.com/289712821

**Comment by uBlock-user** [comment]
As gwarser suggested, blocking CF scripts leads to SSLLabs displaying a false positive result where they show TLS 1.1/1.0 and SSL2/3 being enabled. Whitelist CF's script and it doesn't happen.

**Comment by gorhill** [comment]
> You are the same moron denying the facts over here

The page is broken with uMatrix + default settings because it needs 3rd-party scripts from `cdnjs.cloudflare.com`, and thus the page does not actually test anything in the end -- what you see is the page that is served as is. There is a huge warning at the top of the page informing you about this:

> **Without JavaScript, the following tests will not run:** [...]  Please enable JavaScript for best results.

You get the same with `javascript.enabled` set to `true` in `about:config` in Firefox.
