### ISSUE TITLE
Chromium: Page zoom breaks uMatrix dialog, scrolling necessary

### ISSUE THREAD

**Issue by michael-brade** [uBlockOrigin/uMatrix-issues#57]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Go to Chrome settings, under Appearance set the Page zoom to 175%. Then open the uMatrix dialog: not everything is visible anymore, scrolling is necessary. Interestingly enough, setting Page zoom to 100% and locally increasing the zoom of a certain page with Ctrl++ does *not* change/break the uMatrix dialog.

### A specific URL where the issue occurs

Happens everywhere.

### Steps to Reproduce

1. Go to Chrome settings, under Appearance set the Page zoom to 175%.
2. Then open the uMatrix dialog

### Supporting evidence

![u](https://user-images.githubusercontent.com/8768950/45602619-9d448280-ba21-11e8-8644-0031b09e7f1a.png)

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Chromium, 69.0.3497.92 (Developer Build) built on Debian buster/sid
* Operating System and version: Debian unstable

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/220#issuecomment-420939658

https://bugs.chromium.org/p/chromium/issues/detail?id=849821

Browser bug. Happens with uBO too.

**Comment by gorhill** [comment]
The workaround for this browser issue is to reduce the "Text size" setting in uMatrix's dashboard. However even using the minimum size I could not make the popup panel fit wholly in the browser-controlled popup frame. I will further lower the minimal value.

**Comment by uBlock-user** [comment]
Could this be done for uBO too ?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#popupfontsize

**Comment by michael-brade** [comment]
Aha! This link to the Chromium bug is perfect: I found a better kind of workaround. Chromium saves the zoom per page, so you can choose 175% or whatever in the general settings, then go to uMatrix settings, set that page's zoom back to 100% and all is well.

However, the *best* thing to really fix this would be a larger popup. Chrome's limit is 800x600px, but right now the popup is only 523x354px. Where can I increase this size?

**Comment by gorhill** [comment]
uMatrix has not control over the popup's max size, there is no setting for this -- it's the browser enforcing such max size. I merely improve an already existing workaround, there is nothing else I can do.

**Comment by michael-brade** [comment]
Bummer. That means the browser is really dumb, adding scrollbars but not inreasing the popup size :disappointed: 
Thanks for the answer!

**Comment by gorhill** [comment]
For some reasons it limits the popup size to way under 800px when setting the global zoom to 175% -- see <https://bugs.chromium.org/p/chromium/issues/detail?id=851327>.

**Comment by gorhill** [comment]
Actually the popup is not "way under 800px", it is indeed 800px, the min size is just not increased along with the zoom as the issue above explain.

**Comment by michael-brade** [comment]
Wow... what is going on. You are right, if I measure the actual pixels with a ruler, it says 800px wide. But if I right-click into it and open the developer tools (Inspect), then it shows me this:
![t](https://user-images.githubusercontent.com/8768950/45650495-c8d17680-bace-11e8-8f4d-7a5c09220df1.png)

533px... and I thought I can trust those Developer tools :astonished:

**Comment by uBlock-user** [comment]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=851327#c2, 800x600 is the current hardcoded size limit.
