### ISSUE TITLE
CSS and Image cells appear in red for a specific domain

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uMatrix-issues#58]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

CSS and Image cells appear in red for a specific domain after importing a HOSTS list.

### A specific URL where the issue occurs

`https://www.washingtonpost.com/politics/kavanaugh-accuser-willing-to-testify-her-lawyer-says/2018/09/17/21db2860-ba6c-11e8-9812-a389be6690af_story.html?utm_term=.43ddac4327d7`

### Steps to Reproduce

1. Import `https://raw.githubusercontent.com/uBlock-user/uMatrix-Hosts-List/master/hosts.txt` 

2. Add `www.washingtonpost.com posttv.com xhr allow` in _My Rules_ 

3. Visit `https://www.washingtonpost.com/politics/kavanaugh-accuser-willing-to-testify-her-lawyer-says/2018/09/17/21db2860-ba6c-11e8-9812-a389be6690af_story.html?utm_term=.43ddac4327d7`, play the video and pause it.

3. Open the popup UI, look for `d1d3jupgwm7m5r.cloudfront.net`, notice the CSS and Image cells for that domain appear in red despite that specific domain NOT existing in the aformentioned HOSTS list.

### Supporting evidence

![](https://i.gyazo.com/cda479fb7e778c1dbee36f2e2b408a00.png)

### Your environment

* uMatrix version: 1.3.15.2
* Browser Name and version: Chromium 71/Firefox 64
* Operating System and version: Win 10

**Comment by gorhill** [comment]
> look for `d1d3jupgwm7m5r.cloudfront.net`, notice the CSS and Image cells for that domain appear in red despite that specific domain NOT existing in the aformentioned HOSTS list.

That list contains `0.0.0.0 cloudfront.net`.

**Comment by uBlock-user** [comment]
Ah, I see, sorry didn't notice that before it here.
