### ISSUE TITLE
Little Settings Button Tooltip Misplaced.

### ISSUE THREAD

**Issue by Penguin-Guru** [uBlockOrigin/uMatrix-issues#6]
This is not very important, but I thought I should mention it anyway.

After clicking the extension button to open the matrix drop-down, there is a little gear button in the top left corner. Honestly, I only recently noticed it. When hovering cursor over it, the tooltip appears in an unexpected place. All other buttons that have tooltips put the tooltip in a common relative position, so I assume this is a bug. Screenshot attached as requested.

![umatrix-tooltip-placement](https://user-images.githubusercontent.com/22182988/39664907-19a5a2b0-5059-11e8-9b32-ef96b0c29f1b.png)

O.S.: Linux 4.12.12
Browser: Chromium 65.0.3325.146 (Developer Build) (64-bit)

**Comment by uBlock-user** [comment]
I can reproduce. Actually that gear icon doesn't do anything, it used to exist in uBO too and was removed, you can hover over the entire black strip and click anywhere and it will still open the Dashboard menu.

**Comment by Penguin-Guru** [comment]
For what it's worth, I think it would be fine to just always position the tooltip relative to the gear icon rather than (1) centering it, (2) removing it, or (3) tracking the actual cursor position. With that placement, even if the whole bar is the button, the little gear icon would sort of tie it all together. Seems like the easiest option, but I don't know.

**Comment by BoneTone** [comment]
Does this issue need to remain open?  The gear icon has been removed, and the tooltip appears centered on the dialog and directly below the titlebar regardless of where the mouse cursor is.

![uMatrix Tooltip](https://user-images.githubusercontent.com/53881821/67819147-503b3880-fa8a-11e9-9992-cdeb294c145c.png)

Windows 10 Version 1903 (Build 18362.418)
[Vivaldi 2.8.1664.44 (Stable channel) (64-bit)](https://vivaldi.com/)

**Comment by Penguin-Guru** [comment]
Yes, this seems fixed. Thank you. :)
