### ISSUE TITLE
`µm.userSettings.autoUpdate` in `start.js` may stuck in `true`

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uMatrix-issues#63]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

uMatrix may update assets even if "Auto-update assets" is unchecked

### Steps to Reproduce

1. install uMatrix in fresh Firefox profile
2. go to Dashboard and uncheck "Auto-update assets"
3. close Dashboard, close browser
3. reopen browser, open console (adjust filter to show xhr)
3. assets will start updating after ~7 minutes

### Notes

Logging line added just before `µm.scheduleAssetUpdater` here https://github.com/gorhill/uMatrix/blob/db7feed9c5558933aa4962525072c4b1d04633d2/src/js/start.js#L56

    console.log('µm.userSettings.autoUpdate', µm.userSettings.autoUpdate);

will print 

    µm.userSettings.autoUpdate true

to the console if Firefox run with `-jsconsole` parameter.

You can check auto-update, restart, uncheck, restart, and console will always print `true`.

This may (will?) eventually fix itself, but I don't know how yet. (I somehow manged to switch it to `false` but don't know how.)

See also https://old.reddit.com/r/uMatrix/comments/9d8dd9/two_bugs_in_umatrix/

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox ESR 60.2.1, Nightly 20180925100100
* Operating System and version: Mint 18.3

**Comment by gorhill** [comment]
Looks like a race-condition -- `scheduleAssetUpdater` is being called before user settings are confirmed to be loaded, and hence uMatrix ends up using the default value for `autoUpdate`.
