### ISSUE TITLE
When pasting multiple lines into the rules editor they are joined together in a single line

### ISSUE THREAD

**Issue by Taichocre006** [uBlockOrigin/uMatrix-issues#64]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

When pasting multiple lines into the rules editor they are joined together in a single line. This makes it a pain to manage the ruleset. I keep a lot of temporary rules on text files and paste them/load the website/revert when required. It worked properly before the new editor component was added. Tested copying from various text editors, with both line termination standards (Windows and Unix).

### Steps to Reproduce

1. Open the rules editor.
2. Click on the last line.
3. Press enter.
4. Paste
        google.com * block
        yahoo.com * block
5. Instead of adding two lines, the following line will be added:
        google.com * block* yahoo.com * block

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: FF ESR 60.2.0
* Operating System and version: Win 7, 64 bits

**Comment by 7b4a82cee25ea77cbf9f8250fcec650d** [comment]
Your probably have `dom.event.clipboardevents.enabled` set to false in about:config

**Comment by gorhill** [comment]
> google.com * block
> yahoo.com * block

You probably meant:

    * google.com * block
    * yahoo.com * block

As your rules are not valid and are rejected.

Using the valid rules, I could not reproduce. However, I could reproduce after changing `dom.event.clipboardevents.enabled` to `false`, as pointed by @7b4a82cee25ea77cbf9f8250fcec650d .

The pasting of text is entirely handled by CodeMirror's editor, and from what I can understand , and thus setting `dom.event.clipboardevents.enabled` to `false` breaks CodeMirror, and from what's I've gathered, this also breaks  other fancy editors which rely on clipboard events to work properly ([example](https://github.com/pyllyukko/user.js/issues/287))

**Comment by gorhill** [comment]
I was investigating for a fix in CodeMirror, and as I was preparing to create a patch, I found out somebody else already submitted such patch, <https://github.com/codemirror/CodeMirror/pull/5383>, so just updating with the latest CodeMirror library should fix the issue.

**Comment by gorhill** [comment]
The whole time I thought I was dealing with a uBO issue... Anyways, this issue is valid for both uBO and uMatrix, so the fix is the same.
