### ISSUE TITLE
[Bug] Disable Butten Not fully Working

### ISSUE THREAD

**Issue by alvis05** [uBlockOrigin/uMatrix-issues#66]
### Prerequisites

- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ x] uMatrix is the only extension
    - [ x] uMatrix with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uMatrix
- [ x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description
When I use the disable butten is doesn't disable web workers and possibly the other options in the per scope switches.

### A specific URL where the issue occurs
I haven't got one now but, it can be replicated on any page where one of the per scope switches are blocked.

### Steps to Reproduce

1. Use the disable butten on a any page where one of the per scope switches are blocked.
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version: 1.3.15b6
* Browser Name and version:FireFox 62.0 x64
* Operating System and version:Ubuntu 18.04

**Comment by gorhill** [comment]
> When I use the disable butten is doesn't disable web workers and possibly the other options in the per scope switches.

Read the documentation please.
