### ISSUE TITLE
Migrate icons to FontAwesome svg files (from the font file)

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uMatrix-issues#68]
Latest FontAwesome version make available a package[1] where each individual icon is defined in a plain svg file. Given this I want to import only the needed svg files into a single svg `defs` files and use inline svg tags.

I started that conversion work in <https://github.com/gorhill/uMatrix/commit/c6e29be792df116a9b328b74a4b15455ccbe2138#diff-4de122c13cf2cc4e2364626b0acdb2c9>.

[1] https://use.fontawesome.com/releases/v5.3.1/fontawesome-free-5.3.1-web.zip

**Comment by uBlock-user** [comment]
icons in Drop down switches menu broken in rc builds

![untitled](https://user-images.githubusercontent.com/21290713/49354941-58102280-f6eb-11e8-8b8d-d37648714ba5.png)

**Comment by xofe** [comment]
Looks like missing info icon was fixed with https://github.com/gorhill/uMatrix/commit/de56cfe351cdae0a359efdda407bf35dcc4d9212
