### ISSUE TITLE
Requests bypass uMatrix on Firefox start

### ISSUE THREAD

**Issue by glacambre** [uBlockOrigin/uMatrix-issues#69]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Requests that should be caught by uMatrix are not caught.

### A specific URL where the issue occurs

I managed to reproduce this on Github but I do not think this only happens on Github.

### Steps to Reproduce

1) Use a slow computer
2) Use Firefox 62
3) Set `browser.sessionstore.restore_on_demand` to false in about:config
5) In uMatrix, make sure that the website you're testing this on is not allowed to fetch images
4) Open lots of tabs, notice how the images aren't loaded
6) Close firefox and restart it immediately
7) Notice that the images of the active tab have been loaded
8) Reload the page, notice that the images are not loaded

### Supporting evidence

![2018-10-03-211945_958x1078_scrot](https://user-images.githubusercontent.com/11534587/46433833-31b52180-c752-11e8-8b7a-51b8f6b856bb.png)

As you can see my github avatar is loaded while requests to githubusercontent are forbidden.

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox 62.0
* Operating System and version: Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional thoughts
This might be a Firefox problem rather that a uMatrix problem. There could be a race between the extension-loading process and the page-loading one. If this is what's happening here you might not be able to do anything about it except report it to Mozilla.

**Comment by uBlock-user** [comment]
Browser behaviour. See - gorhill/uBlock#1327

**Comment by glacambre** [comment]
Oh, sorry, didn't think about checking uBlock's issues. Thanks for the prompt reply :)

**Comment by gorhill** [comment]
I need to add the same mechanism in uMatrix as that of uBO -- to my surprise the advanced option `suspendTabsUntilReady` is not in uMatrix. I will consider turning it on by default.

**Comment by Cerberus-tm** [comment]
It would be great if this option where available! As to whether it should be enabled by default, I cannot say (I certainly would enable it myself).

**Comment by uBlock-user** [comment]
The [setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental) is going to be experimental, so it may work and may not sometimes.

**Comment by Cerberus-tm** [comment]
Even so, there is currently a privacy/security hiatus, so anything is better than nothing.
