### ISSUE TITLE
Cookies can be leaked when JavaScript is enabled

### ISSUE THREAD

**Issue by taxidriver61** [uBlockOrigin/uMatrix-issues#7]
In your [wiki](https://github.com/gorhill/uMatrix/wiki/Cookies) you describe that uMatrix prevents cookies from LEAVING the browser. This is not correct in all situations. If JavaScript is enabled for a website, "special" scripts can read the related domain cookies and send the content to the server. If the cookie data are transmitted in custom data structures in the HTTP body or maybe custom HTTP headers, uMatrix can't do anything about it.

From my perspective there are 2 possible options:

1. This behavior is intended and the wiki text should be updated to cover this fact. In this case it would also be interesting why this is intended, because it looks like a potential weak point.
2. uMatrix should be changed to prevent cookies from ENTERING the browser. That means the cookie should not be persisted.

What do you think?

**Comment by gorhill** [comment]
Declined.

Disable javascript, and/or enable cookie deletion.

In case you want to argue this, this won't change -- uMatrix has been existing for well over 4 years and this has been discussed well enough. If you do not like the way uMatrix deals with cookies, use a extension that does what you want.

**Comment by uBlock-user** [comment]
> "special" scripts can read the related domain cookies and send the content to the server. 

That's not cookies getting leaked per se, but rather an alternative to fetch cookie information via JS,that has been possible since the beginning and with JavaScript and the solution is block the said javascript.

**Comment by taxidriver61** [comment]
I'm not questioning the software. It's a nice a useful tool and I am thankful that you're doing this. I'm questioning your information management. I read some of the [tickets](https://github.com/gorhill/uMatrix/issues?q=is%3Aissue+cookies+is%3Aclosed+label%3Adeclined). At least I found found this:

> cookies can be set through javascript: there is no way to block the creation of cookies, the APIs to deal with cookies are asynchronous.

It seems like the beginning to explain that uMatrix can't deal with cookies that are set by JavaScript. That would be totally comprehensible to me. So what's the matter to just add that useful information to your wiki, instead of being annoyed by all issues that have something to do with cookies and closing them without any explanation (in some cases)?! If I'd found that information in your wiki, this ticket would't exists by now. Just sayin...

**Comment by gwarser** [comment]
>"special" scripts can read the related domain cookies and send the content to the server

To be sure - you don't have any real world examples?

**Comment by uBlock-user** [comment]
> there is no way to block the creation of cookies

FYI, that's an invalid statement. Browsers themselves can block **ALL** cookies from being inserted simply by editing the cookie settings. As for the wiki, you should be able to edit it and add more information, if that's the case.

**Comment by gwarser** [comment]
Fixed.

**Comment by crssi** [comment]
@uBlock-user 

> Browsers themselves can block ALL cookies from being inserted simply by editing the cookie settings.

How do you do it on Firefox 60 from GUI?

**Comment by gwarser** [comment]
Preferences -> type: cookies

**Comment by crssi** [comment]
In Firefox 60 there are no more cookie settings over GUI.

**Comment by gwarser** [comment]
I do not. Even if I do, that was by accident. I removed my comment because uBlock-user link explains this for old Firefox interface, and there is not too much difference. You can even search in preferences now, so should be easy to find.

**Comment by crssi** [comment]
Once again... Firefox 60 (not Nightly), does not have any cookie settings over GUI. Search does not help at all.

**Comment by gwarser** [comment]
61:
![screenshot_20180513_224043](https://user-images.githubusercontent.com/886325/39971638-cda08dba-56fe-11e8-84cd-be8f7eeb8250.png)
60:
![screenshot_20180513_224204](https://user-images.githubusercontent.com/886325/39971653-e5d6b382-56fe-11e8-87e5-89125069c3cf.png)

**Comment by crssi** [comment]
@gwarser thank you for your kindness and willing to help
I must apologies, the problem was on my side when I was experimenting in the near past and forgot about on preferences:

``` js
user_pref("browser.storageManager.enabled", false);
```

And it should be `true`, otherwise the cookies section is hidden.

Sorry for all the troubles
Cheers

**Comment by baptx** [comment]
Would it be possible to have a switch like the "Spoof <noscript> tags" feature but for cookies, to disable completely read / write cookies through JavaScript and make `navigator.cookieEnabled` return `false` when cookies are blocked (https://github.com/gorhill/uMatrix/issues/855). I guess it is technically possible and the switch will make the feature optional if some people don't want it by default in uMatrix.
