### ISSUE TITLE
logger Not Working in Sidebar

### ISSUE THREAD

**Issue by rebekah65** [uBlockOrigin/uMatrix-issues#70]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description
Accordion to, https://github.com/gorhill/uMatrix/releases/tag/1.2.0 its possible to open uMatrix in the sidebar. But, when I open the sidebar or look else where there isn't any option to open the logger there.
### A specific URL where the issue occurs
Any url, it doesn't make a difference.

### Steps to Reproduce
There isn't any option i can see, to open the logger in the sidebar.

### Your environment

* uMatrix version: 1.3.15b8
* Browser Name and version: 62.0.3 (64-bit)
* Operating System and version: xUbuntu

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix/commit/e02360f096f56bcc7e28365c9f6a539e8ab2afef

Sidebar support has been removed from stable build and it's prevented from opening in dev build.

**Comment by gorhill** [comment]
He is not using stable, he is using dev build.

**Comment by gorhill** [comment]
Issue is in the python script of Firefox version.

**Comment by rebekah65** [comment]
@gorhill 
Thank you.
