### ISSUE TITLE
"Corrupted Content Error"

### ISSUE THREAD

**Issue by TimTomTwo** [uBlockOrigin/uMatrix-issues#72]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

The site "https://forum.manjaro.org/" and all of its subpages shows a "Corrupted Content Error"-Page if and only if loaded via link (e.g. google search). 
The page will load correctly after a simple refresh, or if the link is copied and pasted into a new tab directly.
Even if everything uMatrix is completely allowing everything for this site and is not spoofing anything.

### A specific URL where the issue occurs

Click first link:
https://www.google.com/search?q=manjaro+forum+gnome&ie=utf-8&oe=utf-8

Will work with a direct copy&paste into a new tab:
https://forum.manjaro.org/t/manjaro-gnome-17-0/18993

### Steps to Reproduce

1. www.google.com
2. Manjaro forum gnome
3. Click first link
4. Corrupted Content Error
5. F5 (reload)
6. Site is shown as expected

### Supporting evidence

![screenshot from 2018-10-09 21-48-47](https://user-images.githubusercontent.com/44004842/46694633-b0580600-cc0d-11e8-89a2-2dfd6f3c8584.png)

![screenshot from 2018-10-09 21-49-32](https://user-images.githubusercontent.com/44004842/46694634-b2ba6000-cc0d-11e8-9fd6-3df5cc672275.png)

### Your environment

* uMatrix version: uMatrix 1.3.14
* Browser Name and version: Firefox 62.0.3 (64-bit)
* Operating System and version: Manjaro with Gnome (kernel 4.19.0-1-MANJARO)

Did not test on other browser/OS

**Comment by gorhill** [comment]
Worked all fine here.

I will close as most likely a ruleset issue, which ruleset you did not disclose. As usual, using the logger is key to diagnose such issue, and nowhere did you mention using it.

**Comment by gwarser** [comment]
Service worker requests XHR with context set for current page (github.com, google.com)

![screenshot_20181009_222914](https://user-images.githubusercontent.com/886325/46696880-93becc80-cc13-11e8-9ce6-fbb3abd957ef.png)

**Comment by gorhill** [comment]
I don't see `github.com` anywhere in the logger. How did you end up getting this? With default ruleset I only see three things blocked:

- `Referer` header when loading `www.google.com` spoofed with `https://ssl.gstatic.com/`
- Request from `www.google.com` to `https://adservice.google.com/...` blocked
- `Referer` header when loading `forum.manjaro.org` spoofed with `https://forum.manjaro.org/`

Page loaded fine.

**Comment by gwarser** [comment]
You need to load https://forum.manjaro.org/t/manjaro-gnome-17-0/18993 and wait for service worker to be installed and then try again.

**Comment by gorhill** [comment]
Ok I could reproduce -- I had cookies set to _"Keep until I close Firefox"_, and this setting prevent sites from using workers. I can reproduce with cookies set to _"Keep until they expire"_.

**Comment by gorhill** [comment]
I don't understand how the browser is firing a XHR request before the site is even loaded. This is what is causing the issue because uMatrix thinks the network request if fired from the previous site.

**Comment by gorhill** [comment]
I can't reproduce with Chromium, the 1st network request is that of `doc` for `https://forum.manjaro.org/t/manjaro-gnome-17-0/18993`, _then_ I get `xhr` for `https://forum.manjaro.org/t/manjaro-gnome-17-0/18993`, as expected.

**Comment by gorhill** [comment]
I think there is an issue in Firefox -- Firefox does not report to the webRequest listener that a document is being requested. Blocking workers make no difference, so it's not related to workers. Firefox just does not fire that a document is being requested.

If I globally hard-disable uMatrix, the logger reports:

    forum.manjaro.org |   | script | https://forum.manjaro.org/assets/locales/e
       www.google.com |   |    xhr | https://forum.manjaro.org/t/manjaro-gnome-17-0/18993 | 3p
       www.google.com |   | script | https://www.google.com/url?sa=t&rct=j&q=&

Which still does not make sense.

If I disable only script on `google.com`, the issue does not occur.

So it seems the `navigator.beacon()` called by Google Search when clicking a link is messing up something internally in Firefox.

**Comment by gorhill** [comment]
Possibly related to that weird Firefox issue: loading `view-source:https://forum.manjaro.org/t/manjaro-gnome-17-0/18993/27` in the address bar (without uMatrix and no other extension enabled) causes Firefox to hog the CPU and a spinning disk on the `https://forum.manjaro.org/t/manjaro-gnome-17-0/18993/27` tab. Eventually, the source for the page loads.

**Comment by gwarser** [comment]
This also affects uBO with 3p dynamic block.

**Comment by uBlock-user** [comment]
Cannot reproduce on Nightly..

**Comment by gwarser** [comment]
["main_frame" chrome.webRequest events fail to fire upon returning to a page that uses service workers bugzilla#1499523](https://bugzilla.mozilla.org/show_bug.cgi?id=1499523)
