### ISSUE TITLE
Upgrade uMatrix to handle First Party Isolation

### ISSUE THREAD

**Issue by MaDill** [uBlockOrigin/uMatrix-issues#73]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Supporting evidence

The problem is reportet in the deprecated issue tracker and there was no update since Feb. 2018. Firefox changed the API since version 59 according bugzilla. Is this issue still in progress or do I have to disable First Party Isolation?

https://github.com/gorhill/uMatrix/issues/878

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox 62.0.3
* Operating System and version: Win 10 Pro 64bit

**Comment by uBlock-user** [comment]
Can you still reproduce it with the Steps given in that old issue ?

**Comment by MaDill** [comment]
I still get the error message in the logger that the delete of the cookie failed. Attached a screenshot:
![umatrix](https://user-images.githubusercontent.com/7298934/47041132-4e0c8180-d188-11e8-975b-25ec8f9ddfc1.png)

**Comment by uBlock-user** [comment]
So the issue still exists

**Comment by tartpvule** [comment]
Is this issue still being worked on? The issue is still present in ESR68.1 I am using.

There are error messages in the Browser Console:
`Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.` for the calls to `chrome.cookies.getAll` and `chrome.cookies.remove` in `vAPI.cookies.getAll` and `vAPI.cookies.remove` respectively.

Maybe adding `firstPartyDomain` attribute would finally resolve this issue?
