### ISSUE TITLE
[Suggestion] Name of the blocking filter

### ISSUE THREAD

**Issue by Bundy01** [uBlockOrigin/uMatrix-issues#77]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: firefox 63
* Operating System and version: Arch

Hi,

First of all thanks for uMatrix and uBlockO, the idea is to report the name of the blocking filter as on uBlockO which is very convenient. Do you think it's possible on uMatrix.

I'm talking about the page that appears with a triangle and an exclamation mark: 
**uMatrix has prevented the loading of this page:** 'url blocked'

What would be nice is to add the filter name as on uBlockO.

Thank you.

**Comment by uBlock-user** [comment]
uBO already has that. uMatrix doesn't. uMatrix doesn't have filters, it has HOSTS file based blocking.

**Comment by gorhill** [comment]
> This was declined already gorhill/uMatrix#892 without explanation :(

It's not clear it's related what he is talking about -- this level of vagueness is enough to make the issue invalid. For all I know, he may be referring to the entries in the logger.

Concerning gorhill/uMatrix#892 specifically, just opening the popup panel tells what is blocking the page, hence why I don't see the need -- <https://github.com/gorhill/uMatrix/issues/203#issuecomment-190795113>.

**Comment by gwarser** [comment]
I think, this is about HOST list name. For example uBO shows: "Found in: uBlock filters – Badware risks" Nothing like this in uMatrix.

**Comment by uBlock-user** [comment]
> I think, this is about HOST list name.

Yes, exactly.

**Comment by gorhill** [comment]
Ok, if so then that would be sort of a duplicate of <https://github.com/gorhill/uMatrix/issues/526>?

**Comment by uBlock-user** [comment]
True, that a specific pertaining to the subject at hand.
