### ISSUE TITLE
Custom recipes don't show up when visiting corresponding host

### ISSUE THREAD

**Issue by migueldemoura** [uBlockOrigin/uMatrix-issues#8]
### Prerequisites

* [X] Did you perform a cursory search of the issue tracker?
* Can you reproduce the problem when...
    * [X] uMatrix is the only extension?
    * [ ] uMatrix with default lists/settings? **N/A**
    * [X] using a new, unmodified browser profile?
* [X] Are you running the latest version?
* [X] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

Custom recipes don't show up when visiting corresponding host.

### A specific URL where the issue occurs

https://pastebin.com/

### Steps to Reproduce

1. Import https://pastebin.com/raw/WXch6AqJ in `Ruleset recipes` at `dashboard.html#hosts-files`. Apply and update.
2. Visit https://pastebin.com/

### Supporting evidence

The recipe seems to have been imported:
https://myazo.migueldemoura.com/data/997c9bb461df6538719eb023.png

Yet the puzzle icon does not show any available recipe:
https://myazo.migueldemoura.com/data/569ca57b1cfe3ca4e6fadf8f.png

### Recipe content

```
Pastebin
    pastebin.com *
        ! Required due to Cloudflare's browser check
        _ 1st-party cookie
        _ 1st-party script
```

Is this incorrect? I also tried with the global CDN examples at https://raw.githubusercontent.com/migueldemoura/ublock-umatrix-rulesets/master/uMatrix/recipes and got the same result.

### Your environment

* uMatrix version: 1.3.8
* Browser Name and version: Chromium 66.0.3359.139 64-bit
* Operating System and version: buntu 18.04

**Comment by migueldemoura** [comment]
Might I add that the built-in rulesets work just fine.

**Comment by gorhill** [comment]
There are things to fix on my side. However, even after the fixes your recipe file is still not parseable by uMatrix, because it's missing the mandatory top line:

    ! uMatrix: Ruleset recipes 1.0

This is a requirement of uMatrix to parse the file as a ruleset recipes file. uMatrix will still import files without that mandatory line because it can only know the file is invalid after importing and loading it.

**Comment by migueldemoura** [comment]
Thanks @gorhill!
