### ISSUE TITLE
Reintroduce XUL extension for SeaMonkey, Pale Moon etc.

### ISSUE THREAD

**Issue by jb-wisemo** [uBlockOrigin/uMatrix-issues#82]
This is a simple plea to change the following past issues from "closed" to "open/feature", such that they can inspire pull requests by others (@Gorhill doesn't have the time to implement this himself, neither do I):

https://github.com/gorhill/uMatrix/issues/826 (this one has the best explanations but was marked as a duplicate of a bug about Firefox 52 ESR)
issue #25 (closed as invalid question)

P.S.
I would have posted this in those issues if Github didn't lack the ability to meaningfully comment on "closed" issues.

**Comment by uBlock-user** [comment]
> change the following past issues from "closed" to "open/feature"

There's no reason to do that as support has been dropped a year ago.

See - https://github.com/gorhill/uMatrix/issues/824#issuecomment-346040385

**Comment by uBlock-user** [comment]
just an FYI --SeaMonkey, Palemoon and other such forks were never officially supported in the first place.

**Comment by uBlock-user** [comment]
> This is not "invalid"

It is, because this is not a issue with uMatrix, but rather a "plea"(as you put it in your own words), plea's are not entertained here. Secondly, what you're asking was removed on purpose and is not a feature.
