### ISSUE TITLE
Enable rules for a specific page or page regex within a domain

### ISSUE THREAD

**Issue by Boruch-Baum** [uBlockOrigin/uMatrix-issues#85]
### Prerequisites

- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Many websites uses captchas or other anti-bot verification measures that require {,third-party} javascript, xhm, frames etc, but only for the page that is performing the check. Currenlty, as far as I tell, one can only enables those elements domain-wide, when the need is only for the single verification page.

An obvious vendor of such protection to many sites is ... google, so if one enables scripts etc from google on site xxx.com just in order to pass a captcha page, then one would be enabling google scripts (whatever they're doing) on all pages for that domain.

Currently, I seem to need to manually enable/disable the elements specifically for the page.

In the provided example, the page is html (with a deleted embedded url cookie), but I have seen other websites using php queries.

### A specific URL where the issue occurs

https://streeteasy.com/distil_r_captcha.html?--------------------------------- <url cookie deleted>

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> Currenlty, as far as I tell, one can only enables those elements domain-wide, when the need is only for the single verification page.

and that's the by-design behaviour, whitelisting/blocking page wise is not possible given the nature of the extension, install uBlock Origin for that.

**Comment by Boruch-Baum** [comment]
Can the two extensions live side-by-side well? I thought they were mutually exclusive, with umatrix being the feature-rich superset?

**Comment by uBlock-user** [comment]
Ofcourse then can, I'm using them both and many other are.

**Comment by Boruch-Baum** [comment]
@uBlock-user: Based upon the documentation, your advice is bad. It seems that uBlock origin *can* whitelist a specific url within a host-name, but that seems to be a complete disabling for everything on the whitelisted page, not limited to whitelisting specific resource(s) on the page.

Let me give an example: say the page is an authentication or login page that requires captcha resources from google (which will need to be enabled), and also facebook / doubleclock resources, which are not required for the authentication, and which you definitely don't want to enable. The documentation on the ublock wiki indicates that it won't do the job -  that the whitelist shuts off all blocking for the page.

**Comment by uBlock-user** [comment]
My answer was to to the question you asked -

> Can the two extensions live side-by-side well?

Yes they can as in compatibility if you will. 

> that the whitelist shuts off all blocking for the page.

When running two extensions, if one extension tells to allow and another tells to block, blocking happens as blocking is given higher priority via the browser APIs.

> It seems that uBlock origin can whitelist a specific url within a host-name, but that seems to be a complete disabling for everything on the whitelisted page, not limited to whitelisting specific resource(s) on the page.

Did you the part of Static Filtering syntax ?

**Comment by Boruch-Baum** [comment]
@uBlock-user: Yes, I did read the documentation for static filtering, which is for blocking, although there is an 'exception' rule referenced there, but that also seems not to be resource specific. The documentation there is incomplete.
