### ISSUE TITLE
Request and issue

### ISSUE THREAD

**Issue by generalhanibal** [uBlockOrigin/uMatrix-issues#86]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

On 
https://browserleaks.com/javascript

With only the 4 firts script allow in first party
1 srt party image ccs allow.
All other set blocked
When you click on iframe-contentWindow
iframe is allow or frame is set to block all 

It is possible to ad in setting of uMatrix check box: Iframe constant removal
The best is set to time 0s and no 0.5
Like the working extention:

Iframe constant removal : 
https://chrome.google.com/webstore/detail/iframe-constant-removal/cgbjgnebmafpalandcmmalkncndcfnpo

With uMatrix and iFrame constant removal:
Iframe-contentWindow is block

### A specific URL where the issue occurs

https://browserleaks.com/javascript

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Chromium 70.0.3538.110 with only uMatrix and iFrame-constant-removal extension.
* Operating System and version: Windows 7 Ultimate 32 bit

**Comment by uBlock-user** [comment]
Why would you merge another extension into uMatrix when it itself can block all iframes ? The iframe in question is from third-party domain, block that.

**Comment by gorhill** [comment]
> When you click on iframe-contentWindow
> iframe is allow or frame is set to block all

What does that mean exactly? I am unable to parse that information.

**Comment by gorhill** [comment]
I don't what this issue is about, it's too incoherent for me to be able to make sense of what is being said. Marking as _invalid_, I will re-open if @generalhanibal can actually make a clear case there is an issue with uMatrix.

**Comment by gwarser** [comment]
I think OP means that blocking iframes does not prevent to query `iframe.contentWindow`

iframe queried on this page is just empty tag without `src`:

`<iframe id="sandboxed" sandbox="allow-same-origin" style="display:none"></iframe>`

**Comment by gorhill** [comment]
> I think OP means that blocking iframes does not prevent to query `iframe.contentWindow`

If it's the case, then the querying is done through javascript, so the proper action to prevent the querying is to block javascript, and this work properly. It's an `iframe` without a source URL, there is nothing being fetched, so there is nothing for uMatrix to block.
