### ISSUE TITLE
Age-restricted YouTube videos become unclickable

### ISSUE THREAD

**Issue by Starz0r** [uBlockOrigin/uMatrix-issues#87]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Using a ruleset in which Script and XHR are explicitly unallowed, even on first parties unless explicitly granted, prevents YouTube video frames from being clickable if they aren't entirely loaded. This only happens in cases where the internet was down while loading the page, or when a Age-restricted video is attempted to load. Since you need to be able to click on "I Understand and wish to proceed", in order for the actual video to load.

### A specific URL where the issue occurs

[Mortal Kombat 11 Announcement Trailer](https://www.youtube.com/watch?v=UoTams2yc0s)
[Battlefield V Update](https://www.youtube.com/watch?v=NPB8XFtRjOo)

### Steps to Reproduce

1. Explicitly disable Script and XHR in "all"
2. Visit one of the specified URLs or any YouTube Age-restricted video
3. ONLY allow any Script or XHR attempts from "googlevideo.com" or "www.youtube.com"

### Supporting evidence

Browser Console Log: https://paste.rs/s7t
Current Ruleset: https://pomf.pyonpyon.moe/flhzjb.png

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox Nightly 65a
* Operating System and version: Windows 10 - Redstone 5

**Comment by uBlock-user** [comment]
> Since you need to be able to click on "I Understand and wish to proceed", in order for the actual video to load.

That notice never appears to me even on a age-restricted video.

**Comment by Starz0r** [comment]
> 
> 
> > Since you need to be able to click on "I Understand and wish to proceed", in order for the actual video to load.
> 
> That notice never appears to me even on a age-restricted video.

You can disable the notification in the settings. However, I was on a new YouTube account, and felt the need to point this one out.

**Comment by uBlock-user** [comment]
This is how it looks like with Restricted Mode set to ON -

![](https://i.gyazo.com/5af1dbc1ca36af765148ccd3b129011f.png)

@Starz0r

**Comment by uBlock-user** [comment]
If you can't click a video when resticted mode is not uMatrix's issue, this is youtube blocking everything in that mode. When I disable that mode, everything works as expected and I can click any video to play.

**Comment by Starz0r** [comment]
Restricted Mode Off:
![unknown](https://user-images.githubusercontent.com/3914271/49636787-35228e80-f9c9-11e8-9ef4-642b785d6488.png)

Restricted Mode On:
![unknown](https://user-images.githubusercontent.com/3914271/49636805-4075ba00-f9c9-11e8-88a6-7e4b4d606eb3.png)

I live in the US if it makes any difference, really odd that it appears different for you.

**Comment by uBlock-user** [comment]
> I live in the US

Set my Location to US and language to English(US), still don't see it.

**Comment by Starz0r** [comment]
It appears to be Firefox issue and not a uMatrix issue as it happens even without the extension. Does not appear to happen in other (non-Firefox based) browsers using the extension. Sorry for wasting your time.

**Comment by uBlock-user** [comment]
> Using a ruleset in which Script and XHR are explicitly unallowed, even on first parties unless explicitly granted, prevents YouTube video frames from being clickable if they aren't entirely loaded.

Does that still happen if uMatrix is disabled ? From what I know this is youtube default behaviour, if the video doesn't load, all other videos won't load either.

**Comment by Starz0r** [comment]
> 
> 
> > Using a ruleset in which Script and XHR are explicitly unallowed, even on first parties unless explicitly granted, prevents YouTube video frames from being clickable if they aren't entirely loaded.
> 
> Does that still happen if uMatrix is disabled ? From what I know this is youtube's default behaviour, if the video doesn't load, all other videos won't load either.

I don't believe this to be default behavior, the video won't load if it can't contact the "googlevideo.com" domain. In this case, it doesn't even make an attempt to load the video.

**Comment by uBlock-user** [comment]
By video doesn't load I meant if the page doesn't load, in those pictures the page itself doesn't fully load.
