### ISSUE TITLE
uMatrix crashes Firefox whenever I visit a certain page.

### ISSUE THREAD

**Issue by daveloyall** [uBlockOrigin/uMatrix-issues#90]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Whenever I have uMatrix enabled and visit the page named below, Firefox starts to take up 100% CPU (all cores) and it consumes more and more RAM every second until the browser crashes.

### A specific URL where the issue occurs

https://phys.org/news/2018-12-amoeba-approximate-solutions-np-hard-problem.html

### Steps to Reproduce

1. Open Firefox.  Visit `about:profiles`.
2. Create a fresh profile and launch it.
3. Install uMatrix from AMO.
4. Visit the page.

### Ruleset

I don't know how to answer this question.  I am using whatever the defaults are.

### Supporting evidence

Here is your screenshot, your majesty!
![image](https://user-images.githubusercontent.com/1524866/50308647-84ed6500-0461-11e9-9b06-a3859291210c.png)

There are three red marks.  Starting at the left, that's when I started a new Firefox with a new, empty profile.  The second mark is when I visited the phys.org page.  The third mark is when Firefox crashed.  Note the quick, linear memory usage growth after the second mark...

### Your environment

* uMatrix version:  1.3.15rc1
* Browser Name and version:  Firefox 66.0a1 (2018-12-20) (64-bit) "Nightly"
* Operating System and version: Microsoft Windows [Version 10.0.14393]

**Comment by uBlock-user** [comment]
Browser should generate a crashdump, look at what it says and where it crashes, likely a browser issue.

**Comment by uBlock-user** [comment]
Only happens on a freshly created profile, runs normally on existing profiles.

**Comment by daveloyall** [comment]
It happens on fresh profiles AND existing profiles.  Most importantly, it does NOT happen when I disable uMatrix.

Did you notice that uMatrix blocks more and more attempted resource loads from the page the longer it sits there?  I guess there is some script on the page that goes into a loop?

**Comment by daveloyall** [comment]
Oh, this is interesting... I didn't know uMatrix exists for Chrome, too.  It does.  So, I created a new profile there and installed uMatrix from the web store and visited that page on phys.org ... CPU usage goes high and memory usage starts to grow.  Not suddenly like in Firefox...  I wonder if I wait long enough, will Chrome crash?

Here is a screenshot:
![image](https://user-images.githubusercontent.com/1524866/50312053-b881bc80-046c-11e9-890c-241599438d46.png)

**Comment by daveloyall** [comment]
Oh, Chrome doesn't crash, but the tab does.  (Good work, Chrome.)

![image](https://user-images.githubusercontent.com/1524866/50312234-42ca2080-046d-11e9-9a69-4de79f7f1d74.png)

**Comment by gorhill** [comment]
It's a site issue, it executes an infinite loop through `setTimeout(..., 0)` if you block `ajax.googleapis.com`.

It's not uncommon sites can break this way with content blocker, this is not an extension issue. Just adjust your ruleset to avoid the issue, whether block JavaScript on the site, or allow `ajax.googleapis.com`.

**Comment by uBlock-user** [comment]
> It happens on fresh profiles AND existing profiles. Most importantly, it does NOT happen when I disable uMatrix.

It doesn't happen on existing (FF/Chromium) profiles on my end, tested both. twice without cache. Anyways, block the javascript that runs the infinite setTimeout loop and you're good to go.

**Comment by the8472** [comment]
I've experienced similar issues with phys.org, but in my case it drives up parent process memory consumption, not just the tab's child process.

https://bugzilla.mozilla.org/show_bug.cgi?id=1525170

**Comment by neuroelectronic** [comment]
@gorhill,

Isn't the issue that setTimeout JavaScript is still executing despite scripts being blocked on the domain? Wouldn't that mean that this issue is not resolved?

**Comment by uBlock-user** [comment]
Read -- https://github.com/uBlockOrigin/uMatrix-issues/issues/90#issuecomment-449149879

Not an extension issue. Poorly coded websites tend to cause such issues, blocking the said script prevents the issue from occuring.

**Comment by gorhill** [comment]
> Isn't the issue that setTimeout JavaScript is still executing despite scripts being blocked on the domain?

Did you force reload the page with cache bypass? See <https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22>.

**Comment by neuroelectronic** [comment]
gorhill, thanks for your time.  It appears it's other add-ons interfering with uMatrix's normal functioning.

**Comment by gorhill** [comment]
> It appears it's other add-ons interfering with uMatrix's normal functioning.

Yes I meant to comment about this too, I realized this could also be the issue -- uMatrix's own injected CSP won't be enforced if another extension already injected a CSP.
