### ISSUE TITLE
Some websites are displayed empty for ~5 seconds after loading finished

### ISSUE THREAD

**Issue by Photon89** [uBlockOrigin/uMatrix-issues#93]
### Prerequisites

- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x ] uMatrix is the only extension
    - [x ] uMatrix with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uMatrix (latest stable version 1.3.14)
- [x ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Some websites are displayed empty for around 5 seconds after the throbber finished rotating, then the content is displayed. The rendering seems to be finished already since the scroll bar does not change any more when the website is actually displayed. The problem appears with a freshly created profile, uMatrix being the only extension installed. No changes to the filters are made. The problem appears only for some websites but does not for others.
### A specific URL where the issue occurs

www.spiegel.de
### Steps to Reproduce

1. [First Step] Open www.spiegel.de
2. [Second Step] ???
3. [and so on...] Profit! (observe the browser behavior)

### Ruleset

Default rules as they come with uMatrix 1.3.14 freshly installed.
### Supporting evidence

Logger output attached: [uMatrixLogger.tar.gz](https://github.com/uBlockOrigin/uMatrix-issues/files/2710382/uMatrixLogger.tar.gz)
### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox 64.0
* Operating System and version: Arch Linux (rolling)

**Comment by uBlock-user** [comment]
because it has a delay of 4000 ms defined with `var spSPDelay=4000;`

**Comment by uBlock-user** [comment]
It's inline either block the inline script with uMatrix or use uBlock Origin to disable that delay.

**Comment by Photon89** [comment]
Thanks for the quick reply, guys! 

I didn't look into the website's code, sorry for that. But my observation is that the issue does not appear when uMatrix is disabled. In this case, the website shows immediately after the throbber finished working (quite fast actually, much faster than 4 seconds, including the throbber loading time). How is this consistent with your explanation?

**Comment by uBlock-user** [comment]
@mapx- Wasn't this patched few days ago in uBO ?

**Comment by uBlock-user** [comment]
> But my observation is that the issue does not appear when uMatrix is disabled. In this case, the website shows immediately after the throbber finished working (quite fast actually, much faster than 4 seconds, including the throbber loading time). How is this consistent with your explanation?

The javascript is doing that. uMatrix only can block or allow network connections.

**Comment by Photon89** [comment]
> The javascript(to be specific that inline-script) is doing that. uMatrix only can block or allow network connections.

But I wonder why this JS is triggered with uMatrix and is not without it. Sorry, I'm not experienced in JS so I might overlook something...

**Comment by uBlock-user** [comment]
It's not triggered, it's anti adblock script from SourcePoint. Anti adblock are best left to deal with uBlock Origin.

**Comment by gorhill** [comment]
> why this JS is triggered with uMatrix and is not without it

Because uBO redirects `googletagmanager.com` to a local neutered script. uMatrix blocks that script and prevent uBO from doing the redirect.

**Comment by gorhill** [comment]
@uBlock-user It's not an anti-blocker, it's <https://github.com/gorhill/uBlock/issues/2569>, a by-design "optimization" delay from Google APIs.

**Comment by uBlock-user** [comment]
It's from SourcePoint who runs the anti adblock scripts for the these domains, so presumed that must be the case.

**Comment by gorhill** [comment]
To put this to rest I just investigated and it is indeed `googletagmanager.com`. Simple test: uBO + default settings; have uMatrix block `googletagmanager.com` = delay; allow `googletagmanager.com` in uMatrix = no delay.

**Comment by Photon89** [comment]
Thanks, I can confirm that this fixes the issue for me! Would it be a good idea to remove the googletagmanager filter rule from the default rules for websites which are known to cause such issues?

**Comment by gorhill** [comment]
uMatrix is a "hard" blocker, it's not designed to make sites work out of the box, investigating and fixing such breakage is a normal part of using uMatrix.

**Comment by gorhill** [comment]
Also, read <https://github.com/gorhill/uMatrix/wiki/Preset-whitelisted-and-blacklisted-domains>.

Specific whitelist rules are not, and will not be part of uMatrix.

**Comment by Photon89** [comment]
I see, thanks for the explanation!

**Comment by uBlock-user** [comment]
Even with uBO, the delay will remain as the redirect will not effectively get rid of the delay completely, but  will make it slightly faster and given the race condition, scriptlets won't work on Chromium, so you will have to block the inline-script on Chrome/Chromium as a solution.

**Comment by Photon89** [comment]
The latter problem is fine with me, I use Firefox anyway. :) Concerning the delay remaining, I'm not sure if I understand but after allowing googletagmanager in uMatrix it is not there or at least not bugging me any more.

**Comment by uBlock-user** [comment]
I still face some delay on Chromium, behaviour must be different on Firefox then, fortunate for you if that's the case.

**Comment by Photon89** [comment]
Actually, I have uBlock Origin, uMatrix and NoScript installed on that machine. Originally it was just uBlock Origin and NoScript but then I needed to allow some elements selectively and added uMatrix which does the job greatly. Probably I need to remove NoScript since it's a PITA to configure both NoScript and uMatrix on every new site...

**Comment by uBlock-user** [comment]
You don't need NoScript if you have already have uBO installed, it will only create further complications.

**Comment by gwarser** [comment]
@Photon89 https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide
