### ISSUE TITLE
Matrix overlay numbers missing

### ISSUE THREAD

**Issue by BlueMax** [uBlockOrigin/uMatrix-issues#95]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description
Overlay numbers are missing on Android 8.1/Fx64 since v1.3.16. Tested on clean Firefox profile.

Android:
![umatrix-android](https://user-images.githubusercontent.com/1403092/50522124-9837aa80-0ac9-11e9-8c85-567582c13ba6.png)
Desktop:
![umatrix-desktop](https://user-images.githubusercontent.com/1403092/50522128-a2f23f80-0ac9-11e9-97d1-85aad9692927.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Android 64.0.1
* Operating System and version: Android 8.1

**Comment by BlueMax** [comment]
Try to force-close Firefox beforehand.
I've noticed that umatrix works properly right after installation or when you (re-)enable it. Once you force-close Firefox it will not work for 2-3 site requests. After that it works properly again. 

Not sure if that's related: In the past (for several umatrix/Firefox versions) i've noticed that when Firefox starts freshly (after force-close) the first site invoked is always "grant all" (even though umatrix shows proper matrix/rules). The next invoked site is ok then. I somewhere read that it's normal as add-ons kick-in earliest when the first site has been completely loaded (or something like this). I have to admit though that i haven't approached it lately (but i always start with a "safe" side anyway these days to make sure its working properly so i'm not sure about current state).

**Comment by gwarser** [comment]
Yes. It's again Android first tab problem. I can reproduce on first tab, and it is persistent as long as I use back button to return to home page. If I close first tab, all other work fine.

**Comment by gorhill** [comment]
> Try to force-close Firefox beforehand (Android settings/apps/firefox/force-close).

Ok I can reproduce. It does seem to be the "first tab" problem.

**Comment by gorhill** [comment]
This is the related bugzilla issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1410749>.

I will investigate again however to find out to confirm this is the same exact issue.

**Comment by gwarser** [comment]
@gorhill, movement on bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1410749#c9
and
https://phabricator.services.mozilla.com/D26431

They want tab ID to be starting from 1 instead of 0.

**Comment by gwarser** [comment]
Looks fixed in today's nightly.
