### ISSUE TITLE
Custom recipe does not appear

### ISSUE THREAD

**Issue by SierraKomodo** [uBlockOrigin/uMatrix-issues#97]
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X] uMatrix is the only extension
    - [X] uMatrix with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [X] I used the logger to rule out that the issue is caused by my ruleset

### Description

Similar to #8 - Except in my case I do have the `! uMatrix: Ruleset recipes 1.0` line present at the top of the file.

I'm putting together a custom ruleset recipe that currently only has a recipe for allowing youtube embeds to play (Using specific rules that are compatible with my global restrictions). This recipe does not appear as an option when opening the uMatrix panel on a webpage that contains a youtube embed with this custom recipe set enabled. The youtube recipe provided in the default english set appears to work fine.

### A specific URL where the issue occurs

https://arstechnica.com/gaming/2018/12/the-orville-blends-science-fiction-and-science-fact-into-a-winning-mix/

### Steps to Reproduce

1. Create a ruleset recipe file containing the text contained under Ruleset
2. Import this file into uMatrix in the Assets tab (My method was by uploading it to a private webserver and fetching the link from there.)
3. Enable the ruleset
4. Navigate to a webpage containing a youtube embed
5. Open the uMatrix panel
6. Note the puzzle icon is grayed out (Or missing the new youtube rule if you have another ruleset enabled).

### Ruleset

```
! uMatrix: Ruleset recipes 1.0
! Title: Sierra Rulesets
! Maintainer: SierraKomodo

 Youtube Embeds
    * youtube.com
        _ googlevideo.com xhr
        _ youtube.com css
        _ youtube.com frame
        _ youtube.com script
        _ youtube.com xhr
        _ ytimg.com image
```

### Supporting evidence

![firefox_2018-12-29_18-55-13](https://user-images.githubusercontent.com/11140088/50543974-e9b06a00-0b9b-11e9-9d7a-589a9c9595c8.png)

![firefox_2018-12-29_19-00-03](https://user-images.githubusercontent.com/11140088/50543979-fd5bd080-0b9b-11e9-8b9b-6bcda7a608a2.png)

![firefox_2018-12-29_18-59-21](https://user-images.githubusercontent.com/11140088/50543980-00ef5780-0b9c-11e9-85a8-3e08955e601c.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox Quantum 64.0 (64-bit)
* Operating System and version: Windows 10 Professional 64-bit

**Comment by uBlock-user** [comment]
I uploaded your recipe over my uMatrix repository - https://raw.githubusercontent.com/uBlock-user/uMatrix-Hosts-List/master/recipes.txt

![](https://i.gyazo.com/01e6b6be2bd84f56c30274c191a85ea5.png)

Works for me. You're doing something wrong.

**Comment by uBlock-user** [comment]
Also the recipe is expected to follow the format of the [existing recipes](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/recipes/recipes_en.txt) and be .txt file, instead of .urr.

**Comment by SierraKomodo** [comment]
It _does_ work when I use the recipe off @uBlock-user 's link - I'm not certain why it would not be working off my own server. I was originally using a .txt extension, before changing to .urr after seeing a repository that had that extension instead.

Could this be related to the server not actually having a domain, and the `vpstunnel.ramnode.wan` domain being something hardcoded in my hosts file?

**Comment by uBlock-user** [comment]
The issue seems to be with your host. I tried your host too and it doesn't work.

**Comment by gorhill** [comment]
Each recipe line must be `\n`-terminated. Is it possible your file had `\r` instead of `\n`?

**Comment by SierraKomodo** [comment]
The file is `\r\n` terminated

**Comment by SierraKomodo** [comment]
I believe I see where the issue lies:

https://github.com/gorhill/uMatrix/blob/6958c4ed26ab514cc1faf84d8f2ddf3be5f8cad5/src/js/recipe-manager.js#L32

https://github.com/gorhill/uMatrix/blob/6958c4ed26ab514cc1faf84d8f2ddf3be5f8cad5/src/js/recipe-manager.js#L102

As my file is `\r\n` terminated, it won't pass a check seeing if it matches ` /^! uMatrix: Ruleset recipes [0-9.]+\n/`.

Should I file a new bug report regarding the `\r\n` vs `\n` issue, or have this one re-opened?

**Comment by gorhill** [comment]
Thanks for spotting the issue, will fix asap.
