### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by aawc** [uBlockOrigin/uMatrix-issues#98]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description
When I try to open the popup menu by clicking on the extension icon, instead of showing me the matrix of origins and resource types, I get a text message saying: "No web page found".

This happens due to JavaScript erroring out. See details below. 

### A specific URL where the issue occurs

1. https://github.com/sessions/two-factor/security-key
2. https://mail.google.com/mail/u/0/#inbox

### Steps to Reproduce

1. Try to login on Github with an account with two factor security key based authentication enabled.
2. When you get to https://github.com/sessions/two-factor/security-key, try to open the popup.

### Ruleset

https://gist.github.com/aawc/bfc480d4941d846226426e0592eb78fd

Dan Pollock’s hosts file
hpHosts’ Ad and tracking servers
Malware Domain List​​​​​
Malware domains
MVPS HOSTS​
Peter Lowe’s Ad and tracking server list​

### Supporting evidence

[Screenshots](https://imgur.com/a/fB6Obcr)

This happens in the following code:
```javascript

        vAPI.messaging.send('popup.js', {
            what: 'matrixSnapshot',
            tabId: matrixSnapshot.tabId,
            scope: matrixSnapshot.scope,
            mtxContentModifiedTime: matrixSnapshot.mtxContentModifiedTime,
            mtxCountModifiedTime: matrixSnapshot.mtxCountModifiedTime,
            mtxDiffCount: matrixSnapshot.diff.length,
            pMatrixModifiedTime: matrixSnapshot.pMatrixModifiedTime,
            tMatrixModifiedTime: matrixSnapshot.tMatrixModifiedTime,
        }, onPolled);
```

```matrixSnapshot``` is an empty dictionary so ```matrixSnapshot.diff``` is undefined. Trying to get ```matrixSnapshot.diff.length``` causes this failure.

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Chrome, Version 71.0.3578.94 (Official Build) beta (64-bit)
* Operating System and version: Chrome OS

**Comment by uBlock-user** [comment]
some thing like that https://github.com/uBlockOrigin/uMatrix-issues/issues/9 happen ?

**Comment by uBlock-user** [comment]
> When you get to https://github.com/sessions/two-factor/security-key, try to open the popup.

I never reach there, instead I'm sent to https://github.com/sessions/two-factor/ and I enter the code and I did click the popup there, and it works as expected, no breakage of any kind.

**Comment by aawc** [comment]
> some thing like that #9 happen ?

The cause for #9 and this seems different.
In #9, the user tried to open the popup on a special scheme page (new tab page), but I am running into this on all URLs.

**Comment by aawc** [comment]
> > When you get to https://github.com/sessions/two-factor/security-key, try to open the popup.
> 
> I never reach there, instead I'm sent to https://github.com/sessions/two-factor/ and I enter the code and I did click the popup there, and it works as expected, no breakage of any kind.

Yes, it repros 100% with all other extensions disabled in one profile for me, but I am unable to repro this in a separate profile.

I could try to re-install uMatrix and that might fix the problem for me, but other users may continue to run into it. Should I try that?

**Comment by gorhill** [comment]
I am unable to reproduce because I do not have a 2FA security key. Possibly I could reproduce a case of "No web page found", but I don't know how to get such case. If somebody can provide me with such case, then I will be able to look into it.

**Comment by gorhill** [comment]
I do have 2FA, I could not reproduce.

**Comment by uBlock-user** [comment]
@gorhill I just managed to reproduce a **no web page found** found in Chromium. I will post the STR below.

1) Open the popup-panel by clicking on the extension icon.

2) Hold Left-Ctrl +LeftShift on the keyboard and click on the black bar/dashboard.

3) two tabs will be opened -- one popup.html# which will result in **no web page found** tab and dashboard

![](https://i.gyazo.com/ded535cdfa4b39edb875ffdd9a2ad82a.png)
