### ISSUE TITLE
Scripts are blocked despite filters when new domain loaded

### ISSUE THREAD

**Issue by foxox** [uBlockOrigin/uMatrix-issues#99]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

If I go to a website (any website except my browser's configured search engine), let it load, and then use my browser's address bar to search for anything, some javascript scripts on the search engine results page are blocked from loading. If I refresh the page, those scripts load fine. I can reproduce this every time. Another way to reproduce it is to visit a website on a domain other than duckduckgo.com in a tab, then past in a duckduckgo.com search url and hit [enter] to load the new URL. This causes the same problem. I think the issue is related to switching domains in one tab.

Disabling uMatrix resolves the issue. I have all other extensions disabled and I reset uMatrix settings to default. This happens no matter the filter settings for my search engine webpage. My search engine is duckduckgo.com. I am using uMatrix v 1.3.0. I am using Opera 55.0.2994.47.

### A specific URL where the issue occurs

Example: I can visit test.com, let it load, and then use the address bar to search for "rdrdrdrd" which loads the following page: 
https://duckduckgo.com/?q=rdrdrdrd&t=opera

### Steps to Reproduce

Visit any website that isn't duckduckgo.com and let the page load (even partially).
Then use the address bar to search for "rdrdrdrd" which loads the following page: 
https://duckduckgo.com/?q=rdrdrdrd&t=opera
Some javascript scripts are blocked and the search results do not appear.

Alternatively:
Visit any website that isn't duckduckgo.com and let the page load (even partially).
Then past this into the address bar of Opera and hit the Enter key: https://duckduckgo.com/?q=rdrdrdrd
Some javascript scripts are blocked and the search results do not appear.

### Ruleset

uMatrix default rules:
```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
```

### Supporting evidence

Chromium network panel showing blocked scripts:
![umatrixissue](https://user-images.githubusercontent.com/1156713/50711101-05ec5500-103b-11e9-8ac3-02008d8687f1.png)

Logger showing scripts being blocked:
![umatrixlogger](https://user-images.githubusercontent.com/1156713/50711076-ef45fe00-103a-11e9-8405-b5e4bcce3315.png)

### Your environment

* uMatrix version: 1.3.0
* Browser Name and version: Opera 55.0.2994.47
* Operating System and version: Win 7 x64

Please let me know if any more information is needed.

**Comment by uBlock-user** [comment]
Cannot reproduce on Chrome. Something else is blocking those scripts.

**Comment by foxox** [comment]
Upon further investigation I discovered that my browser's update function was not working, even when I manually told it to check for updates. I downloaded the latest Opera version and installed it and the problem has gone away. Closing issue, sorry for the bother!
